package com.ccb.architecture.persistence;

import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Repository;

/** Named MyBatis persistence operations for deployment units. */
@Repository
public class DeploymentUnitRepository {
    private final DeploymentUnitMapper mapper;
    public DeploymentUnitRepository(DeploymentUnitMapper mapper) { this.mapper = mapper; }
    public long countUnits(Map<String,Object> p){return mapper.countUnits(p);} public List<Map<String,Object>> pageUnits(Map<String,Object> p){return mapper.pageUnits(p);} public List<Map<String,Object>> findUnit(Map<String,Object> p){return mapper.findUnit(p);} public List<Map<String,Object>> lockUnit(Map<String,Object> p){return mapper.lockUnit(p);} public List<Map<String,Object>> findUnitByName(Map<String,Object> p){return mapper.findUnitByName(p);} public long countUnitName(Map<String,Object> p){return mapper.countUnitName(p);} public int insertUnit(Map<String,Object> p){return mapper.insertUnit(p);} public int updateUnitContent(Map<String,Object> p){return mapper.updateUnitContent(p);} public int updateUnitStatus(Map<String,Object> p){return mapper.updateUnitStatus(p);} public int updateUnitCurrentVersion(Map<String,Object> p){return mapper.updateUnitCurrentVersion(p);}
    public List<Map<String,Object>> findPhysical(Map<String,Object> p){return mapper.findPhysical(p);} public List<Map<String,Object>> findPhysicalByCode(Map<String,Object> p){return mapper.findPhysicalByCode(p);} public Integer acquireNumberLock(Map<String,Object> p){return mapper.acquireNumberLock(p);} public Integer releaseNumberLock(Map<String,Object> p){return mapper.releaseNumberLock(p);} public Integer lockNextOrdinal(Map<String,Object> p){return mapper.lockNextOrdinal(p);} public int insertNextOrdinal(Map<String,Object> p){return mapper.insertNextOrdinal(p);} public int incrementNextOrdinal(Map<String,Object> p){return mapper.incrementNextOrdinal(p);}
    public int insertVersion(Map<String,Object> p){return mapper.insertVersion(p);} public List<Map<String,Object>> findVersions(Map<String,Object> p){return mapper.findVersions(p);} public long countVersions(Map<String,Object> p){return mapper.countVersions(p);}
    public List<Map<String,Object>> findRelatedUnits(Map<String,Object> p){return mapper.findRelatedUnits(p);} public List<Map<String,Object>> lockActiveUnits(Map<String,Object> p){return mapper.lockActiveUnits(p);} public List<Long> lockRelatedIds(Map<String,Object> p){return mapper.lockRelatedIds(p);} public int insertRelation(Map<String,Object> p){return mapper.insertRelation(p);} public int deleteRelation(Map<String,Object> p){return mapper.deleteRelation(p);} public int insertRelationHistory(Map<String,Object> p){return mapper.insertRelationHistory(p);} public long countRelations(Map<String,Object> p){return mapper.countRelations(p);} public long countActiveOptions(Map<String,Object> p){return mapper.countActiveOptions(p);} public List<Map<String,Object>> activeOptions(Map<String,Object> p){return mapper.activeOptions(p);}
    public int insertBatch(Map<String,Object> p){return mapper.insertBatch(p);} public int insertItem(Map<String,Object> p){return mapper.insertItem(p);} public int updateItemResult(Map<String,Object> p){return mapper.updateItemResult(p);} public int updateBatchResult(Map<String,Object> p){return mapper.updateBatchResult(p);} public List<Map<String,Object>> findBatch(Map<String,Object> p){return mapper.findBatch(p);} public long countBatches(Map<String,Object> p){return mapper.countBatches(p);} public List<Map<String,Object>> pageBatches(Map<String,Object> p){return mapper.pageBatches(p);} public List<Map<String,Object>> findItems(Map<String,Object> p){return mapper.findItems(p);}
}
