-- 为平台业务表补齐中文表注释和字段注释。
-- 本迁移只修改 COMMENT，不改变字段类型、默认值、索引或数据。

ALTER TABLE sys_org COMMENT = '组织架构表';
ALTER TABLE sys_org
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '组织主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN parent_id BIGINT NOT NULL DEFAULT 0 COMMENT '上级组织ID，0表示根组织',
    MODIFY COLUMN org_code VARCHAR(64) NOT NULL COMMENT '组织编码',
    MODIFY COLUMN org_name VARCHAR(128) NOT NULL COMMENT '组织名称',
    MODIFY COLUMN leader_id BIGINT NULL DEFAULT NULL COMMENT '组织负责人用户ID',
    MODIFY COLUMN sort_no INT NOT NULL DEFAULT 0 COMMENT '同级组织排序号',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0停用',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0未删除，1已删除';

ALTER TABLE sys_user COMMENT = '系统用户表';
ALTER TABLE sys_user
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '用户主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN username VARCHAR(64) NOT NULL COMMENT '登录账号',
    MODIFY COLUMN password_hash VARCHAR(100) NOT NULL COMMENT 'BCrypt密码哈希',
    MODIFY COLUMN display_name VARCHAR(128) NOT NULL COMMENT '用户姓名',
    MODIFY COLUMN email VARCHAR(128) NULL DEFAULT NULL COMMENT '电子邮箱',
    MODIFY COLUMN org_id BIGINT NOT NULL DEFAULT 0 COMMENT '所属组织ID',
    MODIFY COLUMN avatar_object_key VARCHAR(255) NULL DEFAULT NULL COMMENT 'MinIO头像对象键',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0停用',
    MODIFY COLUMN last_login_at TIMESTAMP NULL DEFAULT NULL COMMENT '最后登录时间',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0未删除，1已删除';

ALTER TABLE sys_role COMMENT = '系统角色表';
ALTER TABLE sys_role
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '角色主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN role_code VARCHAR(64) NOT NULL COMMENT '角色编码',
    MODIFY COLUMN role_name VARCHAR(128) NOT NULL COMMENT '角色名称',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0停用',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0未删除，1已删除';

ALTER TABLE sys_user_role COMMENT = '用户角色关联表';
ALTER TABLE sys_user_role
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID',
    MODIFY COLUMN role_id BIGINT NOT NULL COMMENT '角色ID',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户标识，单租户固定为1';

ALTER TABLE sys_menu COMMENT = '系统菜单与动态路由表';
ALTER TABLE sys_menu
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '菜单主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN parent_id BIGINT NOT NULL DEFAULT 0 COMMENT '上级菜单ID，0表示根菜单',
    MODIFY COLUMN menu_type VARCHAR(16) NOT NULL COMMENT '菜单类型：目录、页面或按钮',
    MODIFY COLUMN menu_name VARCHAR(128) NOT NULL COMMENT '菜单中文名称',
    MODIFY COLUMN route_name VARCHAR(128) NULL DEFAULT NULL COMMENT '前端路由名称',
    MODIFY COLUMN route_path VARCHAR(255) NULL DEFAULT NULL COMMENT '前端路由路径',
    MODIFY COLUMN component_path VARCHAR(255) NULL DEFAULT NULL COMMENT '前端组件路径',
    MODIFY COLUMN permission_code VARCHAR(128) NULL DEFAULT NULL COMMENT '菜单权限编码',
    MODIFY COLUMN icon VARCHAR(128) NULL DEFAULT NULL COMMENT '菜单图标编码',
    MODIFY COLUMN sort_no INT NOT NULL DEFAULT 0 COMMENT '同级菜单排序号',
    MODIFY COLUMN visible TINYINT NOT NULL DEFAULT 1 COMMENT '是否显示：1显示，0隐藏',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0停用',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0未删除，1已删除';

ALTER TABLE sys_role_menu COMMENT = '角色菜单关联表';
ALTER TABLE sys_role_menu
    MODIFY COLUMN role_id BIGINT NOT NULL COMMENT '角色ID',
    MODIFY COLUMN menu_id BIGINT NOT NULL COMMENT '菜单ID',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户标识，单租户固定为1';

ALTER TABLE sys_dict_type COMMENT = '参数类别表';
ALTER TABLE sys_dict_type
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '参数类别主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN dict_code VARCHAR(64) NOT NULL COMMENT '参数类别编码',
    MODIFY COLUMN dict_name VARCHAR(128) NOT NULL COMMENT '参数类别名称',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0停用',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0未删除，1已删除';

ALTER TABLE sys_dict_item COMMENT = '参数明细表';
ALTER TABLE sys_dict_item
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '参数明细主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN dict_type_id BIGINT NOT NULL COMMENT '参数类别ID',
    MODIFY COLUMN item_value VARCHAR(128) NOT NULL COMMENT '参数值',
    MODIFY COLUMN item_label VARCHAR(128) NOT NULL COMMENT '参数显示名称',
    MODIFY COLUMN sort_no INT NOT NULL DEFAULT 0 COMMENT '明细排序号',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0停用',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0未删除，1已删除';

ALTER TABLE sys_config COMMENT = '系统参数表';
ALTER TABLE sys_config
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '参数主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN category_id BIGINT NULL DEFAULT NULL COMMENT '参数类别ID',
    MODIFY COLUMN config_key VARCHAR(128) NOT NULL COMMENT '参数键',
    MODIFY COLUMN config_value TEXT NOT NULL COMMENT '参数值',
    MODIFY COLUMN config_type VARCHAR(32) NOT NULL DEFAULT 'string' COMMENT '参数类型',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0停用',
    MODIFY COLUMN remark VARCHAR(255) NULL DEFAULT NULL COMMENT '参数说明',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0未删除，1已删除';

ALTER TABLE sys_login_log COMMENT = '登录日志表';
ALTER TABLE sys_login_log
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '日志主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN username VARCHAR(64) NOT NULL COMMENT '登录账号',
    MODIFY COLUMN success TINYINT NOT NULL COMMENT '是否登录成功：1成功，0失败',
    MODIFY COLUMN failure_reason VARCHAR(255) NULL DEFAULT NULL COMMENT '失败原因',
    MODIFY COLUMN client_ip VARCHAR(64) NULL DEFAULT NULL COMMENT '客户端IP',
    MODIFY COLUMN user_agent VARCHAR(512) NULL DEFAULT NULL COMMENT '客户端User-Agent',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发生时间';

ALTER TABLE sys_operation_log COMMENT = '系统操作日志表';
ALTER TABLE sys_operation_log
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '日志主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN operator_id BIGINT NOT NULL DEFAULT 0 COMMENT '操作人用户ID',
    MODIFY COLUMN operation_code VARCHAR(128) NOT NULL COMMENT '操作编码',
    MODIFY COLUMN request_method VARCHAR(16) NULL DEFAULT NULL COMMENT 'HTTP请求方法',
    MODIFY COLUMN request_path VARCHAR(255) NULL DEFAULT NULL COMMENT '请求路径',
    MODIFY COLUMN success TINYINT NOT NULL COMMENT '是否操作成功：1成功，0失败',
    MODIFY COLUMN error_message VARCHAR(255) NULL DEFAULT NULL COMMENT '错误信息',
    MODIFY COLUMN client_ip VARCHAR(64) NULL DEFAULT NULL COMMENT '客户端IP',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发生时间';

ALTER TABLE sys_menu_permission COMMENT = '菜单操作权限定义表';
ALTER TABLE sys_menu_permission
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '权限主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN menu_id BIGINT NOT NULL COMMENT '所属菜单ID',
    MODIFY COLUMN action_code VARCHAR(32) NOT NULL COMMENT '操作编码：查询、新增、编辑、删除等',
    MODIFY COLUMN permission_code VARCHAR(160) NOT NULL COMMENT '完整权限编码',
    MODIFY COLUMN permission_name VARCHAR(64) NOT NULL COMMENT '权限中文名称',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0停用',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间';

ALTER TABLE sys_role_permission COMMENT = '角色操作权限关联表';
ALTER TABLE sys_role_permission
    MODIFY COLUMN role_id BIGINT NOT NULL COMMENT '角色ID',
    MODIFY COLUMN permission_id BIGINT NOT NULL COMMENT '菜单操作权限ID',
    MODIFY COLUMN tenant_id BIGINT NOT NULL DEFAULT 1 COMMENT '租户标识，单租户固定为1';

ALTER TABLE wf_definition COMMENT = '工作流定义表';
ALTER TABLE wf_definition
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '流程定义主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN code VARCHAR(64) NOT NULL COMMENT '流程编码',
    MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '流程名称',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT '流程状态',
    MODIFY COLUMN current_version INT NOT NULL DEFAULT 0 COMMENT '当前发布版本号',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    MODIFY COLUMN model_schema_version INT NOT NULL DEFAULT 1 COMMENT '设计器模型版本',
    MODIFY COLUMN bpmn_xml LONGTEXT NULL DEFAULT NULL COMMENT 'Flowable BPMN XML',
    MODIFY COLUMN deployment_id VARCHAR(64) NULL DEFAULT NULL COMMENT 'Flowable部署ID',
    MODIFY COLUMN node_mapping_json JSON NULL DEFAULT NULL COMMENT '设计器节点映射';

ALTER TABLE wf_version COMMENT = '工作流版本表';
ALTER TABLE wf_version
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '流程版本主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN definition_id BIGINT NOT NULL COMMENT '流程定义ID',
    MODIFY COLUMN version_no INT NOT NULL COMMENT '版本号',
    MODIFY COLUMN definition_json JSON NOT NULL COMMENT '流程设计器模型JSON',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT '版本状态',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN model_schema_version INT NOT NULL DEFAULT 1 COMMENT '设计器模型版本',
    MODIFY COLUMN bpmn_xml LONGTEXT NULL DEFAULT NULL COMMENT 'Flowable BPMN XML',
    MODIFY COLUMN deployment_id VARCHAR(64) NULL DEFAULT NULL COMMENT 'Flowable部署ID',
    MODIFY COLUMN node_mapping_json JSON NULL DEFAULT NULL COMMENT '设计器节点映射';

ALTER TABLE wf_instance COMMENT = '工作流实例表';
ALTER TABLE wf_instance
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '流程实例主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN definition_id BIGINT NOT NULL COMMENT '流程定义ID',
    MODIFY COLUMN version_no INT NOT NULL COMMENT '流程版本号',
    MODIFY COLUMN business_key VARCHAR(128) NOT NULL COMMENT '业务单据标识',
    MODIFY COLUMN status VARCHAR(16) NOT NULL COMMENT '实例状态',
    MODIFY COLUMN starter_id BIGINT NOT NULL COMMENT '发起人用户ID',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发起时间',
    MODIFY COLUMN flowable_process_instance_id VARCHAR(64) NULL DEFAULT NULL COMMENT 'Flowable流程实例ID',
    MODIFY COLUMN flowable_process_definition_id VARCHAR(64) NULL DEFAULT NULL COMMENT 'Flowable流程定义ID',
    MODIFY COLUMN variables_json JSON NULL DEFAULT NULL COMMENT '流程变量';

ALTER TABLE wf_task COMMENT = '工作流任务表';
ALTER TABLE wf_task
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '任务主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN instance_id BIGINT NOT NULL COMMENT '流程实例ID',
    MODIFY COLUMN task_key VARCHAR(64) NOT NULL COMMENT '任务节点编码',
    MODIFY COLUMN node_id VARCHAR(64) NULL DEFAULT NULL COMMENT '设计器节点ID',
    MODIFY COLUMN task_type VARCHAR(16) NOT NULL DEFAULT 'APPROVAL' COMMENT '任务类型',
    MODIFY COLUMN task_group_key VARCHAR(64) NULL DEFAULT NULL COMMENT '任务组编码',
    MODIFY COLUMN parent_task_id BIGINT NULL DEFAULT NULL COMMENT '父任务ID',
    MODIFY COLUMN assignee_type VARCHAR(16) NOT NULL DEFAULT 'USER' COMMENT '审批人类型',
    MODIFY COLUMN assignee_name VARCHAR(128) NULL DEFAULT NULL COMMENT '审批人显示名称',
    MODIFY COLUMN assignee_id BIGINT NOT NULL COMMENT '审批人用户ID',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '任务状态',
    MODIFY COLUMN comment VARCHAR(500) NULL DEFAULT NULL COMMENT '审批意见',
    MODIFY COLUMN completed_at TIMESTAMP NULL DEFAULT NULL COMMENT '完成时间',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '任务创建时间',
    MODIFY COLUMN flowable_task_id VARCHAR(64) NULL DEFAULT NULL COMMENT 'Flowable任务ID',
    MODIFY COLUMN action_key VARCHAR(64) NULL DEFAULT NULL COMMENT '最近一次动作编码';

ALTER TABLE wf_task_action COMMENT = '工作流任务动作记录表';
ALTER TABLE wf_task_action
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '动作记录主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN instance_id BIGINT NOT NULL COMMENT '流程实例ID',
    MODIFY COLUMN task_id BIGINT NOT NULL COMMENT '任务ID',
    MODIFY COLUMN action_code VARCHAR(16) NOT NULL COMMENT '动作编码：同意、拒绝、退回等',
    MODIFY COLUMN operator_id BIGINT NOT NULL COMMENT '操作人用户ID',
    MODIFY COLUMN target_user_id BIGINT NULL DEFAULT NULL COMMENT '目标用户ID',
    MODIFY COLUMN comment VARCHAR(500) NULL DEFAULT NULL COMMENT '动作意见',
    MODIFY COLUMN payload_json JSON NULL DEFAULT NULL COMMENT '动作扩展参数',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '动作时间';

ALTER TABLE wf_audit_event COMMENT = '工作流审计事件表';
ALTER TABLE wf_audit_event
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '审计事件主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN definition_id BIGINT NULL DEFAULT NULL COMMENT '流程定义ID',
    MODIFY COLUMN version_no INT NULL DEFAULT NULL COMMENT '流程版本号',
    MODIFY COLUMN instance_id BIGINT NULL DEFAULT NULL COMMENT '流程实例ID',
    MODIFY COLUMN task_id BIGINT NULL DEFAULT NULL COMMENT '任务ID',
    MODIFY COLUMN event_type VARCHAR(32) NOT NULL COMMENT '事件类型',
    MODIFY COLUMN operator_id BIGINT NULL DEFAULT NULL COMMENT '操作人用户ID',
    MODIFY COLUMN reason VARCHAR(500) NULL DEFAULT NULL COMMENT '事件原因',
    MODIFY COLUMN payload_json JSON NULL DEFAULT NULL COMMENT '事件载荷',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '事件时间';

ALTER TABLE ai_provider COMMENT = 'AI服务提供商表';
ALTER TABLE ai_provider
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '提供商主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN provider_code VARCHAR(64) NOT NULL COMMENT '提供商编码',
    MODIFY COLUMN provider_name VARCHAR(128) NOT NULL COMMENT '提供商名称',
    MODIFY COLUMN endpoint VARCHAR(255) NULL DEFAULT NULL COMMENT '服务端点',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0停用',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE ai_model COMMENT = 'AI模型配置表';
ALTER TABLE ai_model
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '模型主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN provider_id BIGINT NOT NULL COMMENT '服务提供商ID',
    MODIFY COLUMN model_code VARCHAR(128) NOT NULL COMMENT '模型编码',
    MODIFY COLUMN model_name VARCHAR(128) NOT NULL COMMENT '模型名称',
    MODIFY COLUMN capabilities VARCHAR(1000) NULL DEFAULT NULL COMMENT '模型能力列表',
    MODIFY COLUMN credential_secret TEXT NULL DEFAULT NULL COMMENT '模型凭据密文',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0停用',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE ai_route COMMENT = 'AI能力路由表';
ALTER TABLE ai_route
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '路由主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN capability VARCHAR(128) NOT NULL COMMENT '能力编码',
    MODIFY COLUMN model_id BIGINT NOT NULL COMMENT '目标模型ID',
    MODIFY COLUMN priority INT NOT NULL DEFAULT 100 COMMENT '路由优先级，数值越小越优先',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0停用',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE ai_execution COMMENT = 'AI调用执行审计表';
ALTER TABLE ai_execution
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '执行记录主键',
    MODIFY COLUMN tenant_id BIGINT NOT NULL COMMENT '租户标识，单租户固定为1',
    MODIFY COLUMN operator_id BIGINT NOT NULL COMMENT '操作人用户ID',
    MODIFY COLUMN capability VARCHAR(128) NOT NULL COMMENT '调用能力编码',
    MODIFY COLUMN model_id BIGINT NOT NULL COMMENT '实际调用模型ID',
    MODIFY COLUMN input_summary VARCHAR(500) NULL DEFAULT NULL COMMENT '输入摘要',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '执行状态',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '执行时间';

-- Flowable 和事件注册表由引擎维护，统一标注表用途；其字段定义保持官方兼容。
ALTER TABLE flyway_schema_history COMMENT = 'Flyway数据库迁移历史表';
ALTER TABLE ACT_GE_PROPERTY COMMENT = 'Flowable通用属性表';
ALTER TABLE ACT_GE_BYTEARRAY COMMENT = 'Flowable通用二进制资源表';
ALTER TABLE ACT_RE_DEPLOYMENT COMMENT = 'Flowable流程部署表';
ALTER TABLE ACT_RE_MODEL COMMENT = 'Flowable流程模型表';
ALTER TABLE ACT_RU_EXECUTION COMMENT = 'Flowable运行时执行表';
ALTER TABLE ACT_RE_PROCDEF COMMENT = 'Flowable流程定义运行表';
ALTER TABLE ACT_EVT_LOG COMMENT = 'Flowable事件日志表';
ALTER TABLE ACT_PROCDEF_INFO COMMENT = 'Flowable流程定义扩展信息表';
ALTER TABLE ACT_RU_ACTINST COMMENT = 'Flowable运行时活动实例表';
ALTER TABLE ACT_HI_PROCINST COMMENT = 'Flowable历史流程实例表';
ALTER TABLE ACT_HI_ACTINST COMMENT = 'Flowable历史活动实例表';
ALTER TABLE ACT_HI_DETAIL COMMENT = 'Flowable历史明细表';
ALTER TABLE ACT_HI_COMMENT COMMENT = 'Flowable历史意见表';
ALTER TABLE ACT_HI_ATTACHMENT COMMENT = 'Flowable历史附件表';
ALTER TABLE ACT_RU_VARIABLE COMMENT = 'Flowable运行时变量表';
ALTER TABLE ACT_HI_VARINST COMMENT = 'Flowable历史变量表';
ALTER TABLE ACT_RU_TASK COMMENT = 'Flowable运行时任务表';
ALTER TABLE ACT_HI_TASKINST COMMENT = 'Flowable历史任务表';
ALTER TABLE ACT_HI_TSK_LOG COMMENT = 'Flowable任务日志表';
ALTER TABLE ACT_RU_IDENTITYLINK COMMENT = 'Flowable运行时身份关联表';
ALTER TABLE ACT_HI_IDENTITYLINK COMMENT = 'Flowable历史身份关联表';
ALTER TABLE ACT_RU_EVENT_SUBSCR COMMENT = 'Flowable运行时事件订阅表';
ALTER TABLE ACT_RU_ENTITYLINK COMMENT = 'Flowable运行时实体关联表';
ALTER TABLE ACT_HI_ENTITYLINK COMMENT = 'Flowable历史实体关联表';
ALTER TABLE ACT_RU_JOB COMMENT = 'Flowable异步作业表';
ALTER TABLE ACT_RU_TIMER_JOB COMMENT = 'Flowable定时作业表';
ALTER TABLE ACT_RU_SUSPENDED_JOB COMMENT = 'Flowable挂起作业表';
ALTER TABLE ACT_RU_DEADLETTER_JOB COMMENT = 'Flowable死信作业表';
ALTER TABLE ACT_RU_HISTORY_JOB COMMENT = 'Flowable历史作业表';
ALTER TABLE ACT_RU_EXTERNAL_JOB COMMENT = 'Flowable外部作业表';
ALTER TABLE FLW_RU_BATCH COMMENT = 'Flowable批处理表';
ALTER TABLE FLW_RU_BATCH_PART COMMENT = 'Flowable批处理分片表';
ALTER TABLE ACT_ID_PROPERTY COMMENT = 'Flowable身份属性表';
ALTER TABLE ACT_ID_BYTEARRAY COMMENT = 'Flowable身份二进制资源表';
ALTER TABLE ACT_ID_GROUP COMMENT = 'Flowable身份组表';
ALTER TABLE ACT_ID_MEMBERSHIP COMMENT = 'Flowable身份成员关系表';
ALTER TABLE ACT_ID_USER COMMENT = 'Flowable身份用户表';
ALTER TABLE ACT_ID_INFO COMMENT = 'Flowable身份扩展信息表';
ALTER TABLE ACT_ID_TOKEN COMMENT = 'Flowable身份令牌表';
ALTER TABLE ACT_ID_PRIV COMMENT = 'Flowable身份权限表';
ALTER TABLE ACT_ID_PRIV_MAPPING COMMENT = 'Flowable身份权限映射表';
ALTER TABLE FLW_EVENT_DEPLOYMENT COMMENT = 'Flowable事件部署表';
ALTER TABLE FLW_EVENT_RESOURCE COMMENT = 'Flowable事件资源表';
ALTER TABLE FLW_EVENT_DEFINITION COMMENT = 'Flowable事件定义表';
ALTER TABLE FLW_CHANNEL_DEFINITION COMMENT = 'Flowable事件通道定义表';
