server {
    listen 80;
    listen [::]:80;
    server_name rddmp.jfsyb.com files.jfsyb.com preview.jfsyb.com;

    client_max_body_size 50m;

    location / {
        proxy_pass http://127.0.0.1:8088;
        include /etc/nginx/snippets/georank-proxy.conf;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name rddmp.jfsyb.com files.jfsyb.com preview.jfsyb.com;

    ssl_certificate /etc/letsencrypt/live/rddmp.jfsyb.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rddmp.jfsyb.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 50m;

    location / {
        proxy_pass http://127.0.0.1:8088;
        include /etc/nginx/snippets/georank-proxy.conf;
    }
}
