<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Delete, Edit, Plus, Refresh } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { apiErrorMessage } from '../../../api/error'
import { createReleaseDrillEnvironment, deleteReleaseDrillEnvironment, listReleaseDrillEnvironments, updateReleaseDrillEnvironment, type ReleaseDrillEnvironmentDto, type ReleaseDrillEnvironmentWrite } from '../../../api/release'
import { useAuthStore } from '../../../stores/auth'
import UiEmptyState from '../../../components/ui/UiEmptyState.vue'

const props = defineProps<{ projectId: number }>()
const auth = useAuthStore(); const rows = ref<ReleaseDrillEnvironmentDto[]>([]); const loading = ref(false); const error = ref(''); const forbidden = ref(false); const dialogOpen = ref(false); const saving = ref(false); const editing = ref<ReleaseDrillEnvironmentDto | null>(null)
const form = reactive<ReleaseDrillEnvironmentWrite>({ environmentName: '', description: '', carryDataLineEnvironment: '', infrastructureDeployment: '', hardwareCheck: '', networkOpening: '', middlewareCheck: '', componentCheck: '', databaseCheck: '', rowVersion: 0 })
const canManage = () => auth.hasPermission('release-operations:environment:manage')
const fields: Array<{ key: keyof ReleaseDrillEnvironmentWrite; label: string }> = [{ key: 'carryDataLineEnvironment', label: '沿用数据线专项环境' }, { key: 'infrastructureDeployment', label: '基础架构部署' }, { key: 'hardwareCheck', label: '硬件' }, { key: 'networkOpening', label: '网络开通' }, { key: 'middlewareCheck', label: '中间件' }, { key: 'componentCheck', label: '组件' }, { key: 'databaseCheck', label: '数据库检查' }]
function isForbidden(cause: unknown) { return (cause as { response?: { status?: number } }).response?.status === 403 }
async function load() { loading.value = true; error.value = ''; forbidden.value = false; try { rows.value = (await listReleaseDrillEnvironments(props.projectId)).data.data } catch (cause) { rows.value = []; error.value = apiErrorMessage(cause, '投产演练环境加载失败，请稍后重试'); forbidden.value = isForbidden(cause) } finally { loading.value = false } }
function open(item?: ReleaseDrillEnvironmentDto) { editing.value = item || null; Object.assign(form, { environmentName: item?.environmentName || '', description: item?.description || '', carryDataLineEnvironment: item?.carryDataLineEnvironment || '', infrastructureDeployment: item?.infrastructureDeployment || '', hardwareCheck: item?.hardwareCheck || '', networkOpening: item?.networkOpening || '', middlewareCheck: item?.middlewareCheck || '', componentCheck: item?.componentCheck || '', databaseCheck: item?.databaseCheck || '', rowVersion: item?.rowVersion || 0 }); dialogOpen.value = true }
async function save() { if (!form.environmentName.trim() || saving.value) return; saving.value = true; try { const response = editing.value ? await updateReleaseDrillEnvironment(props.projectId, editing.value.id, { ...form }) : await createReleaseDrillEnvironment(props.projectId, { ...form }); const value = response.data.data; rows.value = editing.value ? rows.value.map(item => item.id === value.id ? value : item) : [...rows.value, value]; dialogOpen.value = false; ElMessage.success(editing.value ? '演练环境已更新' : '演练环境已创建') } catch (cause) { ElMessage.error(apiErrorMessage(cause, '演练环境保存失败，请重试')) } finally { saving.value = false } }
async function remove(item: ReleaseDrillEnvironmentDto) { try { await ElMessageBox.confirm(`将删除“${item.environmentName}”，删除后不可恢复。`, '删除演练环境', { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' }); await deleteReleaseDrillEnvironment(props.projectId, item.id, item.rowVersion); rows.value = rows.value.filter(value => value.id !== item.id); ElMessage.success('演练环境已删除') } catch (cause) { if (cause !== 'cancel' && cause !== 'close') ElMessage.error(apiErrorMessage(cause, '演练环境删除失败，请刷新后重试')) } }
onMounted(load)
</script>

<template>
  <div v-if="forbidden" class="release-operations-state"><el-result icon="warning" title="无权查看投产演练环境" sub-title="请联系项目管理员申请查看权限。" /></div>
  <div v-else-if="error" class="release-operations-state release-operations-state--error"><el-result icon="error" title="投产演练环境加载失败" :sub-title="error"><template #extra><el-button type="primary" @click="load">重新加载</el-button></template></el-result></div>
  <section v-else v-loading="loading" class="release-operations-panel"><header class="release-operations-panel__header"><div><span class="release-operations-kicker">DRILL ENVIRONMENTS</span><h2>投产演练环境</h2><p>维护多套环境及基础架构检查项，供演练轮次选择。</p></div><div class="release-operations-header-actions"><el-button :icon="Refresh" circle aria-label="刷新演练环境" @click="load" /><el-button v-if="canManage()" type="primary" :icon="Plus" @click="open()">新增环境</el-button></div></header><div class="release-operations-panel__body"><UiEmptyState v-if="!rows.length && !loading" title="暂无投产演练环境" description="创建第一套环境并填写检查项。"><template #action><el-button v-if="canManage()" type="primary" @click="open()">新增环境</el-button></template></UiEmptyState><div v-else class="release-operations-table-scroll"><el-table :data="rows" stripe row-key="id"><el-table-column label="环境名称" min-width="180"><template #default="scope"><div class="release-primary-cell is-static"><strong>{{ scope.row.environmentName }}</strong><span>{{ scope.row.description || '未填写环境说明' }}</span></div></template></el-table-column><el-table-column v-for="field in fields" :key="field.key" :label="field.label" min-width="150" show-overflow-tooltip><template #default="scope">{{ scope.row[field.key] || '未填写' }}</template></el-table-column><el-table-column v-if="canManage()" label="操作" width="100" fixed="right"><template #default="scope"><el-button link :icon="Edit" aria-label="编辑演练环境" @click="open(scope.row)" /><el-button link type="danger" :icon="Delete" aria-label="删除演练环境" @click="remove(scope.row)" /></template></el-table-column></el-table></div></div></section>
  <el-drawer v-model="dialogOpen" :title="editing ? '编辑投产演练环境' : '新增投产演练环境'" direction="rtl" size="min(760px, 94vw)" destroy-on-close><el-form label-position="top" class="release-operations-form-grid release-drawer-form"><el-form-item label="环境名称" required><el-input v-model="form.environmentName" maxlength="128" /></el-form-item><el-form-item label="环境说明"><el-input v-model="form.description" maxlength="1000" /></el-form-item><el-form-item v-for="field in fields" :key="field.key" :label="field.label" class="is-wide"><el-input v-model="form[field.key]" type="textarea" :rows="2" maxlength="2000" /></el-form-item></el-form><template #footer><div class="release-drawer-actions"><el-button @click="dialogOpen = false">取消</el-button><el-button type="primary" :loading="saving" :disabled="!form.environmentName.trim()" @click="save">保存</el-button></div></template></el-drawer>
</template>
