package com.ccb.system.internal.capability;
import org.springframework.stereotype.Repository;
import java.util.List; import java.util.Map;
@Repository public class SystemCapabilityRepository {
    private final SystemCapabilityMapper mapper; public SystemCapabilityRepository(SystemCapabilityMapper mapper) { this.mapper = mapper; }
    public Map<String,Object> projectByRef(Map<String,Object> p){return mapper.projectByRef(p);} public int superAdminCount(Map<String,Object> p){Integer v=mapper.superAdminCount(p);return v==null?0:v;} public int activeMemberCount(Map<String,Object> p){Integer v=mapper.activeMemberCount(p);return v==null?0:v;} public int projectCount(Map<String,Object> p){Integer v=mapper.projectCount(p);return v==null?0:v;} public int manageableProjectCount(Map<String,Object> p){Integer v=mapper.manageableProjectCount(p);return v==null?0:v;}
    public List<Map<String,Object>> activeProjectMembers(Map<String,Object> p){return mapper.activeProjectMembers(p);} public Map<String,Object> activeProjectMember(Map<String,Object> p){return mapper.activeProjectMember(p);} public List<Map<String,Object>> activeUsers(Map<String,Object> p){return mapper.activeUsers(p);} public long activeUserCount(Map<String,Object> p){Long v=mapper.activeUserCount(p);return v==null?0:v;} public Map<String,Object> user(Map<String,Object> p){return mapper.user(p);} public List<Map<String,Object>> activeParameters(Map<String,Object> p){return mapper.activeParameters(p);}
    public List<Long> allProjectIds(long t){return mapper.allProjectIds(t);} public List<Long> memberProjectIds(Map<String,Object> p){return mapper.memberProjectIds(p);} public List<Map<String,Object>> workflowMembers(Map<String,Object> p){return mapper.workflowMembers(p);} public List<Map<String,Object>> workflowRoles(Map<String,Object> p){return mapper.workflowRoles(p);} public List<Long> activeProjectUserIds(Map<String,Object> p){return mapper.activeProjectUserIds(p);} public int projectRoleCount(Map<String,Object> p){Integer v=mapper.projectRoleCount(p);return v==null?0:v;} public List<Map<String,Object>> workflowMembersForRoles(Map<String,Object> p){return mapper.workflowMembersForRoles(p);}
}
