package com.ccb.testmanagement.service;

import org.springframework.stereotype.Repository;
import java.util.List;
import java.util.Map;

@Repository
class BusinessDayRepository {
    private final BusinessDayMapper mapper;
    BusinessDayRepository(BusinessDayMapper mapper){this.mapper=mapper;}
    long environmentCount(Map<String,Object> p){return value(mapper.environmentCount(p));} List<Map<String,Object>> environmentPage(Map<String,Object> p){return mapper.environmentPage(p);} List<Map<String,Object>> activeEnvironments(Map<String,Object> p){return mapper.activeEnvironments(p);} Map<String,Object> environment(Map<String,Object> p){return mapper.environment(p);} void insertEnvironment(Map<String,Object> p){mapper.insertEnvironment(p);} void updateEnvironment(Map<String,Object> p){mapper.updateEnvironment(p);} void renameSchedules(Map<String,Object> p){mapper.renameSchedules(p);} void renameRequirements(Map<String,Object> p){mapper.renameRequirements(p);} long scheduleReferenceCount(Map<String,Object> p){return value(mapper.scheduleReferenceCount(p));} long requirementReferenceCount(Map<String,Object> p){return value(mapper.requirementReferenceCount(p));} void deleteEnvironment(Map<String,Object> p){mapper.deleteEnvironment(p);} long uniqueEnvironmentCount(Map<String,Object> p){return value(mapper.uniqueEnvironmentCount(p));} long activeEnvironmentCount(Map<String,Object> p){return value(mapper.activeEnvironmentCount(p));}
    long scheduleCount(Map<String,Object> p){return value(mapper.scheduleCount(p));} List<Map<String,Object>> schedulePage(Map<String,Object> p){return mapper.schedulePage(p);} List<Map<String,Object>> overview(Map<String,Object> p){return mapper.overview(p);} Map<String,Object> schedule(Map<String,Object> p){return mapper.schedule(p);} List<Map<String,Object>> scheduleByNaturalKey(Map<String,Object> p){return mapper.scheduleByNaturalKey(p);} void insertSchedule(Map<String,Object> p){mapper.insertSchedule(p);} void updateSchedule(Map<String,Object> p){mapper.updateSchedule(p);} int deleteSchedule(Map<String,Object> p){return mapper.deleteSchedule(p);} long scheduleExists(Map<String,Object> p){return value(mapper.scheduleExists(p));}
    long requirementCount(Map<String,Object> p){return value(mapper.requirementCount(p));} List<Map<String,Object>> requirementPage(Map<String,Object> p){return mapper.requirementPage(p);} Map<String,Object> requirement(Map<String,Object> p){return mapper.requirement(p);} void insertRequirement(Map<String,Object> p){mapper.insertRequirement(p);} void updateRequirement(Map<String,Object> p){mapper.updateRequirement(p);} int reviewRequirement(Map<String,Object> p){return mapper.reviewRequirement(p);} int deleteRequirement(Map<String,Object> p){return mapper.deleteRequirement(p);} long requirementExists(Map<String,Object> p){return value(mapper.requirementExists(p));} void insertAudit(Map<String,Object> p){mapper.insertAudit(p);} private long value(Long value){return value==null?0:value;}
}
