package com.ccb.testmanagement.service;

import com.ccb.common.api.PageQuery;
import com.ccb.common.api.PageResult;
import com.ccb.common.exception.BusinessException;
import com.ccb.common.exception.ErrorCode;
import com.ccb.security.model.AuthUser;
import com.ccb.system.model.UserDirectoryItem;
import com.ccb.system.model.UserDirectoryPort;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.sql.Date;
import java.time.LocalDate;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.atomic.AtomicLong;

@Service
public class TestConfigurationService {
 private static final Set<String> DOMAINS=Set.of("application-assembly","user-testing","non-functional","security"), ROLE_CODES=Set.of("TEST_MANAGER","TESTER","DEVELOPER"), ROUND_STATUSES=Set.of("DRAFT","ACTIVE","CLOSED");
 private static final AtomicLong IDS=new AtomicLong(System.currentTimeMillis()*1000);
 private static final List<DictionarySeed> DEFAULT_DICTIONARIES=List.of(dictionary("case_type","案例类型","LOCAL","建设案例|BUILD,投产案例|RELEASE,优化案例|OPTIMIZE"),dictionary("case_nature","案例性质","LOCAL","正向|POSITIVE,反向|NEGATIVE"),dictionary("case_priority","案例优先级","LOCAL","高|HIGH,中|MEDIUM,低|LOW"),dictionary("func_type","功能类型","LOCAL","联机交易|ONLINE,批处理|BATCH,报表|REPORT"),dictionary("change_status","变动状态","LOCAL","新增|NEW,修改|CHANGE"),dictionary("importance","业务重要程度","LOCAL","高|HIGH,中|MEDIUM,低|LOW"),dictionary("accounting_flag","是否核算相关","LOCAL","是|YES,否|NO"),dictionary("defect_category","缺陷分类","LOCAL","功能缺陷|FUNCTION,数据缺陷|DATA,界面缺陷|UI,性能缺陷|PERFORMANCE,安全缺陷|SECURITY,环境问题|ENVIRONMENT,需求问题|REQUIREMENT,操作理解|OPERATION,其他|OTHER"),dictionary("severity","缺陷严重程度","LOCAL","致命|FATAL,严重|SERIOUS,一般|NORMAL,轻微|MINOR"),dictionary("defect_priority","缺陷优先级","LOCAL","高|HIGH,中|MEDIUM,低|LOW"),dictionary("urgency","紧急程度","LOCAL","高|HIGH,中|MEDIUM,低|LOW"),dictionary("report_type","报告类型","SYSTEM","轮次报告|ROUND,周期报告|CYCLE"),dictionary("test_env","测试环境","EXTERNAL","SIT环境|SIT,UAT环境|UAT,性能环境|PERFORMANCE,灾备环境|DR"));
 private final TestConfigurationRepository repository; private final ObjectMapper objectMapper; private final UserDirectoryPort users;
 public TestConfigurationService(TestConfigurationRepository repository,ObjectMapper objectMapper,UserDirectoryPort users){this.repository=repository;this.objectMapper=objectMapper;this.users=users;}
 public List<Map<String,Object>> projectOptions(AuthUser user){return repository.projectOptions(p("tenantId",user.tenantId()));}
 public PageResult<Map<String,Object>> systems(String domain,long projectId,PageQuery page,String keyword,AuthUser user){domain(domain);requireProject(projectId,user.tenantId());Map<String,Object> q=p("domain",domain,"projectId",projectId,"tenantId",user.tenantId(),"keyword",hasText(keyword)?keyword.trim():null,"offset",offset(page),"size",page.size());return new PageResult<>(repository.physicalSystemPage(q),repository.physicalSystemCount(q),page.page(),page.size());}
 @Transactional public Map<String,Object> setSystem(String domain,long projectId,long physicalId,Map<String,Object> body,AuthUser user){domain(domain);requireProject(projectId,user.tenantId());requirePhysical(physicalId,user.tenantId());boolean enabled=bool(body.get("enabled"),false);if(!enabled&&!bool(body.get("confirmed"),false))return Map.of("confirmation_required",true,"impact",systemImpact(domain,projectId,physicalId,user.tenantId()));Map<String,Object> q=p("tenantId",user.tenantId(),"domain",domain,"projectId",projectId,"physicalId",physicalId,"enabled",enabled?1:0,"remark",text(body.get("remark"),500,"备注"),"userId",user.id());Map<String,Object> old=repository.participatingSystemId(q);long id=old==null?nextId():number(old.get("id"));q.put("id",id);if(old==null)repository.insertParticipatingSystem(q);else repository.updateParticipatingSystem(q);audit(domain,projectId,"SYSTEM",id,enabled?"ENABLE":"DISABLE",Map.of("physical_subsystem_id",physicalId),user);return repository.participatingSystem(q);}
 public Map<String,Object> systemImpact(String domain,long projectId,long physicalId,long tenant){domain(domain);requireProject(projectId,tenant);requirePhysical(physicalId,tenant);return Map.of("unfinished_defects",0,"latest_executions",0,"message","后续缺陷和执行模块尚未启用，当前无受影响业务数据");}
 public PageResult<Map<String,Object>> roles(String domain,long projectId,long physicalId,PageQuery page,AuthUser user){domain(domain);requireParticipatingSystem(domain,projectId,physicalId,user.tenantId());Map<String,Object> q=p("tenantId",user.tenantId(),"domain",domain,"projectId",projectId,"physicalId",physicalId,"offset",offset(page),"size",page.size());return new PageResult<>(repository.rolePage(q),repository.roleCount(q),page.page(),page.size());}
 @Transactional public Map<String,Object> assignRole(String domain,long projectId,long physicalId,Map<String,Object> body,AuthUser user){domain(domain);requireParticipatingSystem(domain,projectId,physicalId,user.tenantId());long memberId=positive(body.get("user_id"),"用户");UserDirectoryItem member=users.findActive(user.tenantId(),memberId).orElseThrow(()->bad("用户不存在、未启用或不属于当前租户"));String code=roleCode(body.get("role_code"));Map<String,Object> q=p("tenantId",user.tenantId(),"domain",domain,"projectId",projectId,"physicalId",physicalId,"memberId",memberId,"roleCode",code,"roleName",roleName(code),"userId",user.id());if(repository.roleExists(q)>0)throw conflict("该用户已拥有此系统角色");long id=nextId();q.put("id",id);repository.insertRole(q);audit(domain,projectId,"SYSTEM_ROLE",id,"CREATE",Map.of("user_id",memberId,"username",member.username()),user);return repository.role(p("id",id,"tenantId",user.tenantId(),"domain",domain));}
 @Transactional public Map<String,Object> deleteRole(String domain,long id,Map<String,Object> body,AuthUser user){Map<String,Object> role=role(id,domain,user.tenantId());if(!bool(body.get("confirmed"),false))return Map.of("confirmation_required",true,"impact",Map.of("unfinished_defects",0,"latest_executions",0));repository.deleteRole(p("id",id,"tenantId",user.tenantId(),"userId",user.id()));audit(domain,number(role.get("project_id")),"SYSTEM_ROLE",id,"DELETE",Map.of("user_id",number(role.get("user_id"))),user);return Map.of("deleted",true);}
 public List<UserDirectoryItem> users(String keyword,AuthUser user){return users.listActive(user.tenantId(),keyword,50);}
 @Transactional public Map<String,Object> importSystems(String domain,long projectId,List<Map<String,Object>> rows,AuthUser user){domain(domain);requireProject(projectId,user.tenantId());Map<String,Map<String,Object>> prepared=new LinkedHashMap<>();List<Map<String,Object>> errors=new ArrayList<>();for(Map<String,Object> row:rows){String code=text(row.get("physical_code"),32,"物理子系统编号");Long physicalId=findPhysicalByCode(code,user.tenantId());if(code==null)errors.add(importError(row,"物理子系统编号不能为空"));else if(physicalId==null)errors.add(importError(row,"物理子系统不存在或不属于当前租户："+code));else try{prepared.put(code,p("physical_id",physicalId,"enabled",importBoolean(row.get("enabled"),"是否参测"),"remark",row.get("remark")));}catch(BusinessException e){errors.add(importError(row,e.getMessage()));}}if(!errors.isEmpty())return importResult(rows.size(),prepared.size(),0,errors);for(Map<String,Object> item:prepared.values())setSystem(domain,projectId,number(item.get("physical_id")),p("enabled",item.get("enabled"),"confirmed",true,"remark",item.get("remark")),user);audit(domain,projectId,"SYSTEM",0,"IMPORT",Map.of("rows",prepared.size()),user);return importResult(rows.size(),prepared.size(),prepared.size(),List.of());}
 @Transactional public Map<String,Object> importRoles(String domain,long projectId,List<Map<String,Object>> rows,AuthUser user){domain(domain);requireProject(projectId,user.tenantId());Map<String,Map<String,Object>> prepared=new LinkedHashMap<>();List<Map<String,Object>> errors=new ArrayList<>();for(Map<String,Object> row:rows){String physicalCode=text(row.get("physical_code"),32,"物理子系统编号");Long physicalId=findPhysicalByCode(physicalCode,user.tenantId()),memberId=importPositive(row.get("user_id"));String code=String.valueOf(row.getOrDefault("role_code","")).trim().toUpperCase(Locale.ROOT);String error=physicalCode==null?"物理子系统编号不能为空":physicalId==null?"物理子系统不存在或不属于当前租户："+physicalCode:memberId==null?"用户ID无效":!ROLE_CODES.contains(code)?"角色编码无效":null;if(error==null&&users.findActive(user.tenantId(),memberId).isEmpty())error="用户不存在、未启用或不属于当前租户";if(error==null)try{requireParticipatingSystem(domain,projectId,physicalId,user.tenantId());}catch(BusinessException e){error="物理子系统尚未设为参测系统";}if(error!=null)errors.add(importError(row,error));else prepared.put(physicalId+":"+memberId+":"+code,p("physicalId",physicalId,"memberId",memberId,"roleCode",code));}if(!errors.isEmpty())return importResult(rows.size(),prepared.size(),0,errors);int created=0;for(Map<String,Object> item:prepared.values()){Map<String,Object> q=p("tenantId",user.tenantId(),"domain",domain,"projectId",projectId,"physicalId",item.get("physicalId"),"memberId",item.get("memberId"),"roleCode",item.get("roleCode"),"roleName",roleName(String.valueOf(item.get("roleCode"))),"userId",user.id());if(repository.roleExists(q)>0)continue;q.put("id",nextId());repository.insertRole(q);created++;}audit(domain,projectId,"SYSTEM_ROLE",0,"IMPORT",Map.of("rows",prepared.size(),"created",created),user);return importResult(rows.size(),prepared.size(),created,List.of());}
 public PageResult<Map<String,Object>> rounds(String domain,long projectId,PageQuery page,AuthUser user){domain(domain);requireProject(projectId,user.tenantId());Map<String,Object> q=pageParams(domain,projectId,page,user);return new PageResult<>(repository.roundPage(q),repository.roundCount(q),page.page(),page.size());}
 @Transactional public Map<String,Object> saveRound(String domain,long projectId,Long id,Map<String,Object> body,AuthUser user){domain(domain);requireProject(projectId,user.tenantId());String requested=text(body.get("round_code"),64,"轮次编码"),code=requested==null&&id==null?nextRoundCode(domain,projectId,user.tenantId()):code(requested,"轮次编码"),name=required(body.get("round_name"),"轮次名称",128),status=roundStatus(body.get("status"));DateRange dates=dates(body);uniqueRound(code,name,id,domain,projectId,user.tenantId());long saved=id==null?nextId():id;Map<String,Object> q=p("id",saved,"tenantId",user.tenantId(),"domain",domain,"projectId",projectId,"roundCode",code,"roundName",name,"startDate",dates.start(),"endDate",dates.end(),"status",status,"sortNo",integer(body.get("sort_no")),"remark",text(body.get("remark"),500,"备注"),"userId",user.id());if(id==null)repository.insertRound(q);else{requireRound(id,domain,projectId,user.tenantId());repository.updateRound(q);}audit(domain,projectId,"ROUND",saved,id==null?"CREATE":"UPDATE",Map.of("round_code",code),user);return repository.round(q);}
 @Transactional public void deleteRound(String domain,long projectId,long id,AuthUser user){requireRound(id,domain(domain),projectId,user.tenantId());if(repository.cycleReferenceCount(p("tenantId",user.tenantId(),"roundId",id))>0)throw conflict("轮次仍包含测试周期，不能删除");repository.deleteRound(p("id",id,"tenantId",user.tenantId(),"userId",user.id()));audit(domain,projectId,"ROUND",id,"DELETE",Map.of(),user);}
 public PageResult<Map<String,Object>> cycles(String domain,long projectId,long roundId,PageQuery page,AuthUser user){requireRound(roundId,domain(domain),projectId,user.tenantId());Map<String,Object> q=p("tenantId",user.tenantId(),"roundId",roundId,"offset",offset(page),"size",page.size());return new PageResult<>(repository.cyclePage(q),repository.cycleCount(q),page.page(),page.size());}
 @Transactional public Map<String,Object> saveCycle(String domain,long projectId,long roundId,Long id,Map<String,Object> body,AuthUser user){requireRound(roundId,domain(domain),projectId,user.tenantId());String requested=text(body.get("cycle_code"),64,"周期编码"),code=requested==null&&id==null?nextCycleCode(roundId,user.tenantId()):code(requested,"周期编码"),name=required(body.get("cycle_name"),"周期名称",128);DateRange dates=dates(body);uniqueCycle(code,name,id,roundId,user.tenantId());long saved=id==null?nextId():id;Map<String,Object> q=p("id",saved,"tenantId",user.tenantId(),"roundId",roundId,"cycleCode",code,"cycleName",name,"startDate",dates.start(),"endDate",dates.end(),"status",roundStatus(body.get("status")),"sortNo",integer(body.get("sort_no")),"remark",text(body.get("remark"),500,"备注"),"userId",user.id());if(id==null)repository.insertCycle(q);else{requireCycle(id,roundId,user.tenantId());repository.updateCycle(q);}audit(domain,projectId,"CYCLE",saved,id==null?"CREATE":"UPDATE",Map.of("cycle_code",code),user);Map<String,Object> result=new LinkedHashMap<>(repository.cycle(q));result.put("outside_round_warning",outsideRound(roundId,dates,user.tenantId()));return result;}
 @Transactional public void deleteCycle(String domain,long projectId,long roundId,long id,AuthUser user){requireRound(roundId,domain(domain),projectId,user.tenantId());requireCycle(id,roundId,user.tenantId());repository.deleteCycle(p("id",id,"tenantId",user.tenantId(),"userId",user.id()));audit(domain,projectId,"CYCLE",id,"DELETE",Map.of(),user);}
 public PageResult<Map<String,Object>> dictionaries(String domain,long projectId,PageQuery page,AuthUser user){domain(domain);requireProject(projectId,user.tenantId());ensureDefaultDictionaries(domain,projectId,user);Map<String,Object> q=pageParams(domain,projectId,page,user);return new PageResult<>(repository.dictionaryPage(q),repository.dictionaryCount(q),page.page(),page.size());}
 @Transactional public Map<String,Object> saveDictionary(String domain,long projectId,Long id,Map<String,Object> body,AuthUser user){domain(domain);requireProject(projectId,user.tenantId());String code=code(body.get("dictionary_code"),"字典编码"),name=required(body.get("dictionary_name"),"字典名称",128);if(repository.dictionaryUniqueCodeCount(p("tenantId",user.tenantId(),"domain",domain,"projectId",projectId,"value",code,"exceptId",id))>0)throw conflict("字典编码已存在");long saved=id==null?nextId():id;Map<String,Object> q=p("id",saved,"tenantId",user.tenantId(),"domain",domain,"projectId",projectId,"dictionaryCode",code,"dictionaryName",name,"sourceType","LOCAL","enabled",bool(body.get("enabled"),true)?1:0,"remark",text(body.get("remark"),500,"备注"),"userId",user.id());if(id==null)repository.insertDictionary(q);else{requireDictionary(id,domain,projectId,user.tenantId());repository.updateDictionary(q);}audit(domain,projectId,"DICTIONARY",saved,id==null?"CREATE":"UPDATE",Map.of("dictionary_code",code),user);return repository.dictionary(q);}
 @Transactional public void deleteDictionary(String domain,long projectId,long id,AuthUser user){requireDictionary(id,domain(domain),projectId,user.tenantId());if(repository.dictionaryOptionReferenceCount(p("tenantId",user.tenantId(),"dictionaryId",id))>0)throw conflict("字典仍包含选项，不能删除");repository.deleteDictionary(p("id",id,"tenantId",user.tenantId(),"userId",user.id()));audit(domain,projectId,"DICTIONARY",id,"DELETE",Map.of(),user);}
 public PageResult<Map<String,Object>> options(String domain,long projectId,long dictionaryId,PageQuery page,AuthUser user){requireDictionary(dictionaryId,domain(domain),projectId,user.tenantId());Map<String,Object> q=p("tenantId",user.tenantId(),"dictionaryId",dictionaryId,"offset",offset(page),"size",page.size());return new PageResult<>(repository.optionPage(q),repository.optionCount(q),page.page(),page.size());}
 @Transactional public Map<String,Object> saveOption(String domain,long projectId,long dictionaryId,Long id,Map<String,Object> body,AuthUser user){requireDictionary(dictionaryId,domain(domain),projectId,user.tenantId());String code=code(body.get("option_code"),"选项编码"),name=required(body.get("option_name"),"选项名称",128);if(repository.optionUniqueCodeCount(p("tenantId",user.tenantId(),"dictionaryId",dictionaryId,"value",code,"exceptId",id))>0)throw conflict("选项编码已存在");long saved=id==null?nextId():id;Map<String,Object> q=p("id",saved,"tenantId",user.tenantId(),"dictionaryId",dictionaryId,"optionCode",code,"optionName",name,"enabled",bool(body.get("enabled"),true)?1:0,"sortNo",integer(body.get("sort_no")),"remark",text(body.get("remark"),500,"备注"),"userId",user.id());if(id==null)repository.insertOption(q);else{requireOption(id,dictionaryId,user.tenantId());repository.updateOption(q);}audit(domain,projectId,"DICTIONARY_OPTION",saved,id==null?"CREATE":"UPDATE",Map.of("option_code",code),user);return repository.option(q);}
 @Transactional public void deleteOption(String domain,long projectId,long dictionaryId,long id,AuthUser user){requireDictionary(dictionaryId,domain(domain),projectId,user.tenantId());requireOption(id,dictionaryId,user.tenantId());repository.deleteOption(p("id",id,"tenantId",user.tenantId(),"userId",user.id()));audit(domain,projectId,"DICTIONARY_OPTION",id,"DELETE",Map.of(),user);}
 private void requireProject(long id,long tenant){if(repository.projectExists(p("id",id,"tenantId",tenant))==0)throw bad("项目不存在或不属于当前租户");} private void requirePhysical(long id,long tenant){if(repository.physicalExists(p("id",id,"tenantId",tenant))==0)throw bad("物理子系统不存在或不属于当前租户");} private void requireParticipatingSystem(String d,long project,long physical,long tenant){if(repository.enabledParticipatingSystemExists(p("tenantId",tenant,"domain",d,"projectId",project,"physicalId",physical))==0)throw bad("请先启用该参测系统");} private void requireRound(long id,String domain,long project,long tenant){if(repository.roundExists(p("id",id,"tenantId",tenant,"domain",domain,"projectId",project))==0)throw bad("测试轮次不存在");} private void requireCycle(long id,long round,long tenant){if(repository.cycleExists(p("id",id,"roundId",round,"tenantId",tenant))==0)throw bad("测试周期不存在");} private void requireDictionary(long id,String domain,long project,long tenant){if(repository.dictionaryExists(p("id",id,"tenantId",tenant,"domain",domain,"projectId",project))==0)throw bad("字典不存在");} private void requireOption(long id,long dictionary,long tenant){if(repository.optionExists(p("id",id,"dictionaryId",dictionary,"tenantId",tenant))==0)throw bad("字典选项不存在");}
 private Map<String,Object> role(long id,String domain,long tenant){Map<String,Object> row=repository.role(p("id",id,"tenantId",tenant,"domain",domain));if(row==null)throw bad("系统角色不存在");return row;} private boolean outsideRound(long roundId,DateRange cycle,long tenant){Map<String,Object> r=repository.roundDates(p("id",roundId,"tenantId",tenant));Date start=(Date)r.get("planned_start_date"),end=(Date)r.get("planned_end_date");return start!=null&&cycle.start()!=null&&cycle.start().before(start)||end!=null&&cycle.end()!=null&&cycle.end().after(end);} private void uniqueRound(String code,String name,Long id,String domain,long project,long tenant){Map<String,Object> q=p("tenantId",tenant,"domain",domain,"projectId",project,"exceptId",id,"value",code);if(repository.roundUniqueCodeCount(q)>0)throw conflict("轮次编码已存在");q.put("value",name);if(repository.roundUniqueNameCount(q)>0)throw conflict("轮次名称已存在");} private void uniqueCycle(String code,String name,Long id,long round,long tenant){Map<String,Object> q=p("tenantId",tenant,"roundId",round,"exceptId",id,"value",code);if(repository.cycleUniqueCodeCount(q)>0)throw conflict("周期编码已存在");q.put("value",name);if(repository.cycleUniqueNameCount(q)>0)throw conflict("周期名称已存在");}
 private void audit(String domain,long project,String type,long id,String action,Map<String,Object> detail,AuthUser user){try{repository.insertAudit(p("id",nextId(),"tenantId",user.tenantId(),"domain",domain,"projectId",project,"entityType",type,"entityId",id,"action",action,"userId",user.id(),"detailJson",objectMapper.writeValueAsString(detail)));}catch(JsonProcessingException e){throw new BusinessException(ErrorCode.INTERNAL_ERROR,"配置审计序列化失败");}}
 private String domain(String value){if(!DOMAINS.contains(value))throw bad("测试大类无效");return value;} private String roleCode(Object value){String code=String.valueOf(value==null?"":value).trim().toUpperCase(Locale.ROOT);if(!ROLE_CODES.contains(code))throw bad("系统角色无效");return code;} private String roleName(String c){return Map.of("TEST_MANAGER","测试经理","TESTER","测试人员","DEVELOPER","开发人员").get(c);} private static DictionarySeed dictionary(String code,String name,String source,String items){return new DictionarySeed(code,name,source,items);}
 @Transactional private void ensureDefaultDictionaries(String domain,long projectId,AuthUser user){for(DictionarySeed seed:DEFAULT_DICTIONARIES){List<Map<String,Object>> existing=repository.dictionaryByCode(p("tenantId",user.tenantId(),"domain",domain,"projectId",projectId,"dictionaryCode",seed.code()));long dictionaryId;if(existing.isEmpty()){dictionaryId=nextId();repository.insertDictionary(p("id",dictionaryId,"tenantId",user.tenantId(),"domain",domain,"projectId",projectId,"dictionaryCode",seed.code(),"dictionaryName",seed.name(),"sourceType",seed.source(),"enabled",1,"remark","系统预置字典","userId",user.id()));}else dictionaryId=number(existing.get(0).get("id"));int sort=1;for(String item:seed.items().split(",")){String[] parts=item.split("\\|",2);String optionName=parts[0],optionCode=parts[1];if(repository.optionUniqueCodeCount(p("tenantId",user.tenantId(),"dictionaryId",dictionaryId,"value",optionCode,"exceptId",null))==0)repository.insertOption(p("id",nextId(),"tenantId",user.tenantId(),"dictionaryId",dictionaryId,"optionCode",optionCode,"optionName",optionName,"enabled",1,"sortNo",sort,"remark","系统预置选项","userId",user.id()));sort++;}}}
 private String nextRoundCode(String domain,long project,long tenant){for(int n=1;n<1_000_000;n++){String c="R"+String.format("%03d",n);if(repository.roundUniqueCodeCount(p("tenantId",tenant,"domain",domain,"projectId",project,"value",c,"exceptId",null))==0)return c;}throw conflict("轮次编号已用尽");} private String nextCycleCode(long round,long tenant){for(int n=1;n<1_000_000;n++){String c="C"+String.format("%03d",n);if(repository.cycleUniqueCodeCount(p("tenantId",tenant,"roundId",round,"value",c,"exceptId",null))==0)return c;}throw conflict("周期编号已用尽");}
 private String roundStatus(Object v){String s=v==null?"DRAFT":String.valueOf(v).trim().toUpperCase(Locale.ROOT);if(!ROUND_STATUSES.contains(s))throw bad("状态无效");return s;} private String code(Object v,String label){String s=String.valueOf(v==null?"":v).trim().toUpperCase(Locale.ROOT);if(!s.matches("[A-Z0-9_-]{1,64}"))throw bad(label+"仅支持 1-64 位字母、数字、下划线和短横线");return s;} private String required(Object v,String label,int max){String s=text(v,max,label);if(s==null)throw bad("请填写"+label);return s;} private String text(Object v,int max,String label){if(v==null)return null;String s=String.valueOf(v).trim();if(s.length()>max)throw bad(label+"不能超过 "+max+" 个字符");return s.isEmpty()?null:s;} private long positive(Object v,String label){try{long n=Long.parseLong(String.valueOf(v));if(n<=0)throw new NumberFormatException();return n;}catch(RuntimeException e){throw bad(label+"无效");}} private long number(Object v){return ((Number)v).longValue();} private int integer(Object v){if(v==null||String.valueOf(v).isBlank())return 0;try{return Integer.parseInt(String.valueOf(v));}catch(RuntimeException e){throw bad("排序号必须是整数");}} private boolean bool(Object v,boolean fallback){if(v==null)return fallback;if(v instanceof Boolean b)return b;if(v instanceof Number n)return n.intValue()!=0;return Set.of("true","1","yes").contains(String.valueOf(v).toLowerCase(Locale.ROOT));}
 private DateRange dates(Map<String,Object> b){Date start=date(b.get("planned_start_date"),"计划开始日期"),end=date(b.get("planned_end_date"),"计划结束日期");if(start!=null&&end!=null&&start.after(end))throw bad("计划结束日期不能早于开始日期");return new DateRange(start,end);} private Date date(Object v,String label){if(v==null||String.valueOf(v).isBlank())return null;try{return Date.valueOf(LocalDate.parse(String.valueOf(v)));}catch(RuntimeException e){throw bad(label+"格式应为 YYYY-MM-DD");}} private long nextId(){long floor=System.currentTimeMillis()*1000+ThreadLocalRandom.current().nextInt(1000);return IDS.updateAndGet(previous->Math.max(previous+1,floor));} private Long findPhysicalByCode(String code,long tenant){if(code==null)return null;List<Map<String,Object>> rows=repository.physicalByCode(p("tenantId",tenant,"code",code));return rows.isEmpty()?null:number(rows.get(0).get("id"));} private Map<String,Object> importError(Map<String,Object> row,String message){return Map.of("row_number",row.getOrDefault("row_number",0),"message",message);} private Map<String,Object> importResult(int total,int valid,int written,List<Map<String,Object>> errors){return Map.of("total",total,"valid",valid,"written",written,"errors",errors,"success",errors.isEmpty());} private boolean importBoolean(Object value,String label){String text=String.valueOf(value==null?"":value).trim().toLowerCase(Locale.ROOT);if(Set.of("是","true","1","yes").contains(text))return true;if(Set.of("否","false","0","no").contains(text))return false;throw bad(label+"仅支持 是/否");} private Long importPositive(Object v){try{long n=Long.parseLong(String.valueOf(v).trim());return n>0?n:null;}catch(RuntimeException e){return null;}} private boolean hasText(String s){return s!=null&&!s.isBlank();} private long offset(PageQuery p){return(p.page()-1)*p.size();} private Map<String,Object> pageParams(String domain,long project,PageQuery page,AuthUser user){return p("tenantId",user.tenantId(),"domain",domain,"projectId",project,"offset",offset(page),"size",page.size());} private Map<String,Object> p(Object... values){Map<String,Object> r=new LinkedHashMap<>();for(int i=0;i<values.length;i+=2)r.put(String.valueOf(values[i]),values[i+1]);return r;} private BusinessException bad(String s){return new BusinessException(ErrorCode.BAD_REQUEST,s);} private BusinessException conflict(String s){return new BusinessException(ErrorCode.CONFLICT,s);} private record DictionarySeed(String code,String name,String source,String items){} private record DateRange(Date start,Date end){}
}
