/*
 * 文件：server/src/modules/test-management/src/main/java/com/ccb/testmanagement/service/TestReportDocumentService.java
 * 说明：测试管理的服务、策略或接口实现。
 * 用途：承载模块边界内的查询、校验、事务、权限或文件处理职责。
 * 作者：hengguan
 */
package com.ccb.testmanagement.service;

// 关键逻辑：文件输入输出在模块内限制格式、大小和字段边界；异常内容不能绕过既有业务校验。

import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.springframework.stereotype.Service;
import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.util.*;

/** 报告导出使用真正的 OOXML Word；PDF 使用 Adobe CJK Type0 字体，避免中文降级为问号。 */
@Service public class TestReportDocumentService {
 public byte[] docx(Map<String,Object> detail){try(XWPFDocument doc=new XWPFDocument();ByteArrayOutputStream out=new ByteArrayOutputStream()){title(doc,"测试报告："+String.valueOf(((Map<?,?>)detail.get("report")).get("report_name")));Map<?,?> facts=(Map<?,?>)detail.get("snapshot");for(String k:FACTS){line(doc,label(k)+"："+String.valueOf(facts.get(k)==null?"0":facts.get(k)));}for(String code:CHAPTERS){title(doc,chapter(code));line(doc,narrative(code,facts));}for(Map<?,?> s:(List<Map<?,?>>)detail.getOrDefault("supplements",List.of())){line(doc,"补充说明："+strip(String.valueOf(s.get("content_html")==null?"":s.get("content_html"))));}doc.write(out);return out.toByteArray();}catch(Exception e){throw new IllegalStateException("Word 导出失败",e);}}
 public byte[] pdf(Map<String,Object> detail){List<String> lines=new ArrayList<>();Map<?,?> report=(Map<?,?>)detail.get("report");lines.add("测试报告："+report.get("report_name"));Map<?,?> facts=(Map<?,?>)detail.get("snapshot");for(String key:FACTS)lines.add(label(key)+"："+String.valueOf(facts.get(key)==null?"0":facts.get(key)));for(String code:CHAPTERS){lines.add(chapter(code));lines.add(narrative(code,facts));}StringBuilder content=new StringBuilder("BT /F1 11 Tf 50 790 Td ");for(String line:lines){content.append("<").append(utf16be(line)).append("> Tj 0 -16 Td ");}content.append("ET");String body=content.toString();List<String> objects=List.of("<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>","<< /Length "+body.getBytes(StandardCharsets.ISO_8859_1).length+" >>\nstream\n"+body+"\nendstream","<< /Type /Font /Subtype /Type0 /BaseFont /STSong-Light /Encoding /UniGB-UCS2-H /DescendantFonts [6 0 R] >>","<< /Type /Font /Subtype /CIDFontType0 /BaseFont /STSong-Light /CIDSystemInfo << /Registry (Adobe) /Ordering (GB1) /Supplement 2 >> >>");StringBuilder out=new StringBuilder("%PDF-1.4\n");List<Integer> pos=new ArrayList<>();for(int i=0;i<objects.size();i++){pos.add(out.length());out.append(i+1).append(" 0 obj\n").append(objects.get(i)).append("\nendobj\n");}int start=out.length();out.append("xref\n0 ").append(objects.size()+1).append("\n0000000000 65535 f \n");for(int p:pos)out.append(String.format(Locale.ROOT,"%010d 00000 n \n",p));out.append("trailer << /Size ").append(objects.size()+1).append(" /Root 1 0 R >>\nstartxref\n").append(start).append("\n%%EOF");return out.toString().getBytes(StandardCharsets.ISO_8859_1);}
 private static final List<String> FACTS=List.of("effective_case_total","invalid_case_total","execution_total","execution_unexecuted","execution_in_progress","execution_success","execution_failed","execution_blocked","execution_rate","case_success_rate","executed_case_success_rate","defect_total","defect_open","defect_density","defect_repair_rate");
 private static final List<String> CHAPTERS=List.of("OVERVIEW","ENVIRONMENT_CONFIG","SCOPE_STRATEGY","EXECUTION_PROGRESS","DEFECT_ANALYSIS","QUALITY_ASSESSMENT","RISKS_ISSUES","CONCLUSION_RECOMMENDATION");
 private void title(XWPFDocument d,String s){XWPFParagraph p=d.createParagraph();p.createRun().setBold(true);p.createRun().setText(s);}private void line(XWPFDocument d,String s){d.createParagraph().createRun().setText(s);}private String strip(String s){return s.replaceAll("<[^>]*>"," ").replace("&nbsp;"," ").trim();}private String utf16be(String value){StringBuilder result=new StringBuilder("FEFF");for(char character:value.toCharArray())result.append(String.format(Locale.ROOT,"%04X",(int)character));return result.toString();}private String fact(Map<?,?> facts,String key){return String.valueOf(facts.get(key)==null?"0":facts.get(key));}private String narrative(String code,Map<?,?> facts){return switch(code){case "OVERVIEW"->"本报告汇总当前统计范围内的测试事实，测试范围 "+fact(facts,"scope_total")+" 项，案例 "+fact(facts,"case_total")+" 条。";case "ENVIRONMENT_CONFIG"->"测试环境与配置以当前测试大类、项目和报告范围的已保存配置为准。";case "SCOPE_STRATEGY"->"有效案例 "+fact(facts,"effective_case_total")+" 条，无效案例 "+fact(facts,"invalid_case_total")+" 条；无效案例不计入相关比率分母。";case "EXECUTION_PROGRESS"->"已执行 "+fact(facts,"execution_total")+" 条，成功 "+fact(facts,"execution_success")+" 条，失败 "+fact(facts,"execution_failed")+" 条，阻塞 "+fact(facts,"execution_blocked")+" 条，执行中 "+fact(facts,"execution_in_progress")+" 条。";case "DEFECT_ANALYSIS"->"缺陷总数 "+fact(facts,"defect_total")+" 个，未关闭 "+fact(facts,"defect_open")+" 个，严重缺陷 "+fact(facts,"severe_defect_count")+" 个。";case "QUALITY_ASSESSMENT"->"质量评估只依据本报告版本冻结时生效的质量阈值指标。";case "RISKS_ISSUES"->"请优先跟踪失败、阻塞、未关闭和严重缺陷事项。";case "CONCLUSION_RECOMMENDATION"->"完成风险事项处理和复测后，可重新生成报告版本确认质量结论。";default->"";};}private String label(String key){return switch(key){case "effective_case_total"->"有效案例数";case "invalid_case_total"->"无效案例数";case "execution_total"->"已执行案例数";case "execution_unexecuted"->"未执行案例数";case "execution_in_progress"->"执行中案例数";case "execution_success"->"成功案例数";case "execution_failed"->"失败案例数";case "execution_blocked"->"阻塞案例数";case "execution_rate"->"执行率";case "case_success_rate"->"案例成功率";case "executed_case_success_rate"->"已执行案例成功率";case "defect_total"->"缺陷总数";case "defect_open"->"未关闭缺陷数";case "severe_defect_count"->"严重缺陷数";case "defect_density"->"缺陷密度";case "defect_repair_rate"->"缺陷修复率";default->key;};}private String chapter(String code){return switch(code){case "OVERVIEW"->"报告概述";case "ENVIRONMENT_CONFIG"->"测试环境与配置";case "SCOPE_STRATEGY"->"测试范围与策略";case "EXECUTION_PROGRESS"->"测试执行与进度";case "DEFECT_ANALYSIS"->"缺陷分析";case "QUALITY_ASSESSMENT"->"质量评估";case "RISKS_ISSUES"->"风险与问题";case "CONCLUSION_RECOMMENDATION"->"结论与建议";case "SCOPE_STAT"->"测试范围统计";case "EXECUTION_STAT"->"案例执行统计";case "DEFECT_STAT"->"缺陷统计";case "QUALITY_STAT"->"质量阈值判定";case "SCOPE_DETAIL"->"测试范围明细";case "EXECUTION_DETAIL"->"案例执行明细";case "DEFECT_DETAIL"->"缺陷明细";default->code;};}
}
