package com.ccb.datamigration.service;

import com.ccb.attachment.integration.AttachmentBindingCommand;
import com.ccb.attachment.integration.AttachmentGateway;
import com.ccb.attachment.integration.AttachmentItem;
import com.ccb.common.exception.BusinessException;
import com.ccb.common.exception.ErrorCode;
import com.ccb.security.model.AuthUser;
import com.ccb.system.model.UserDirectoryPort;
import com.ccb.common.api.PageResult;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;
import java.util.concurrent.ThreadLocalRandom;

/**
 * 文件型内容资产服务（REQ-20260831-050）：表名按资产类型参数化，
 * 承接原 AssetService 的 upsert、主文件替换（dm_content_attachment sort_order=0）、
 * 下载、软删/恢复/彻底删除。REPORT 由 ReportService 复用本服务的附件能力，其余结构化类型由
 * StructuredAssetService 承接。
 */
@Service
public class ContentFileAssetService {
    public static final String BUSINESS_TYPE = "DATA_MIGRATION_ASSET";
    /** 本服务直接承接的文件型类型（PLAN/RELEASE_DRILL/SCRIPT 均走专属服务，REPORT 走 ReportService，结构化类型走 StructuredAssetService）。 */
    // PLAN/RELEASE_DRILL/SCRIPT 已剥离至 PlanService/ReleaseDrillService/ProgramService（REQ-20260820-031 增量）；表仍留在 FILE_TABLES（看板计数）。
    public static final Set<String> MANAGED_TYPES = Set.of("DEPENDENCY");
    private static final long MAX_FILE_SIZE = 50L * 1024 * 1024;

    private final ContentFileAssetRepository repository;
    private final AttachmentGateway attachmentGateway;
    private final ContentAttachmentService attachments;
    private final DataMigrationPermissionService permissions;
    private final UserDirectoryPort userDirectory;
    private final ContentDocCodeGenerator docCodes;

    @Autowired
    public ContentFileAssetService(ContentFileAssetRepository repository, AttachmentGateway attachmentGateway,
                                   ContentAttachmentService attachments, DataMigrationPermissionService permissions,
                                   UserDirectoryPort userDirectory, ContentDocCodeGenerator docCodes) {
        this.repository = repository;
        this.attachmentGateway = attachmentGateway;
        this.attachments = attachments;
        this.permissions = permissions;
        this.userDirectory = userDirectory;
        this.docCodes = docCodes;
    }


    /** T32：列表必须落在单个可访问项目内，SQL 恒定 {@code project_id} 过滤。 */
    public PageResult<Map<String, Object>> list(String type, Long projectId, String systemCode, String keyword,
                                                int page, int size, AuthUser user) {
        String table = requireManagedTable(type);
        long scope = permissions.requireProject(projectId, user);
        String normalizedSystemCode = systemCode == null ? null : systemCode.trim();
        String normalizedKeyword = keyword == null ? null : keyword.trim();
        long total = repository.count(table, type, user.tenantId(), scope, normalizedSystemCode, normalizedKeyword);
        int safePage = Math.max(1, page);
        int safeSize = normalizePageSize(size);
        List<Map<String, Object>> rows = repository.page(table, type, user.tenantId(), scope, normalizedSystemCode, normalizedKeyword, safeSize, (long) (safePage - 1) * safeSize);
        for (Map<String, Object> row : rows) {
            Object rawAttachmentId = row.get("attachment_id");
            if (rawAttachmentId instanceof Number number) {
                try {
                    AttachmentItem item = attachmentGateway.get(number.longValue(), user);
                    row.put("content_type", item.contentType());
                    row.put("file_size", item.fileSize());
                    row.put("file_name", item.fileName());
                } catch (BusinessException ignored) {
                    // 关系行可能已与平台附件状态发生变化，列表仍返回业务记录。
                }
            }
        }
        return new PageResult<>(rows, total, safePage, safeSize);
    }

    /** Creates a file asset. The business code is always generated by the server. */
    @Transactional
    public Map<String, Object> create(String type, long projectId, String systemCode,
                                      Long attachmentId, AuthUser user) {
        String table = requireManagedTable(type);
        ensureProject(projectId, user);
        if (systemCode != null && !systemCode.isBlank()) ensureComponent(systemCode.trim(), projectId, user);
        AttachmentItem attachment = resolveAttachment(attachmentId, user);
        if (attachment.fileSize() <= 0 || attachment.fileSize() > MAX_FILE_SIZE) throw new BusinessException(ErrorCode.BAD_REQUEST, "File is empty or exceeds 50 MB");
        long id = nextId();
        try {
            repository.insert(table, Map.of("id", id, "tenantId", user.tenantId(), "projectId", projectId, "systemCode", systemCode == null || systemCode.isBlank() ? "" : systemCode.trim(), "docCode", docCodes.generate(type), "docName", attachment.fileName(), "ownerId", user.id(), "createdBy", user.id(), "updatedBy", user.id()));
        } catch (DataIntegrityViolationException ex) {
            throw new BusinessException(ErrorCode.CONFLICT, "文档编号在该项目下已存在，请刷新后重试");
        }
        replaceMainFile(type, id, projectId, attachment, user);
        audit(user, "ASSET_UPLOAD", projectId, id);
        return repository.active(table, user.tenantId(), id);
    }

    /** Replaces the main file of an existing asset without changing its project or business code. */
    @Transactional
    public Map<String, Object> replace(String type, long id, String systemCode,
                                       Long attachmentId, AuthUser user) {
        String table = requireManagedTable(type);
        Map<String, Object> current = repository.active(table, user.tenantId(), id);
        if (current == null) throw new BusinessException(ErrorCode.BAD_REQUEST, "Asset not found");
        long projectId = permissions.requireStoredProject(current.get("project_id"), user);
        permissions.requireWrite(user, ((Number) current.get("owner_id")).longValue());
        String nextSystemCode = systemCode != null && !systemCode.isBlank() ? systemCode.trim()
                : current.get("system_code") == null ? "" : String.valueOf(current.get("system_code"));
        if (!nextSystemCode.isBlank()) ensureComponent(nextSystemCode, projectId, user);
        AttachmentItem attachment = resolveAttachment(attachmentId, user);
        if (attachment.fileSize() <= 0 || attachment.fileSize() > MAX_FILE_SIZE) throw new BusinessException(ErrorCode.BAD_REQUEST, "File is empty or exceeds 50 MB");
        repository.update(table, Map.of("systemCode", nextSystemCode, "docName", attachment.fileName(), "actorId", user.id(), "id", id, "tenantId", user.tenantId()));
        replaceMainFile(type, id, projectId, attachment, user);
        audit(user, "ASSET_REPLACE", projectId, id);
        return repository.active(table, user.tenantId(), id);
    }

    @Transactional
    public void delete(String type, Collection<Long> ids, AuthUser user) {
        String table = requireManagedTable(type);
        for (Long id : ids) {
            Map<String, Object> row = repository.active(table, user.tenantId(), id);
            if (row == null) throw new BusinessException(ErrorCode.BAD_REQUEST, "Asset not found");
            // T32：按记录库中归属做项目隔离，跨项目 id 直接拒绝
            long projectId = permissions.requireStoredProject(row.get("project_id"), user);
            permissions.requireWrite(user, ((Number) row.get("owner_id")).longValue());
            int changed = repository.softDelete(table, user.tenantId(), id, user.id());
            if (changed != 1) throw new BusinessException(ErrorCode.CONFLICT, "Asset state changed, please retry");
            audit(user, "ASSET_DELETE", projectId, id);
        }
    }

    @Transactional
    public void restore(String type, Collection<Long> ids, AuthUser user) {
        permissions.requireAdmin(user);
        String table = requireManagedTable(type);
        for (Long id : ids) {
            long projectId = requireDeletedProjectScope(table, id, user);
            try {
                int changed = repository.restore(table, user.tenantId(), id, user.id());
                if (changed != 1) throw new BusinessException(ErrorCode.CONFLICT, "Asset state changed, please retry");
            } catch (DataIntegrityViolationException ex) {
                // 恢复后活动行 doc_code 与既有活动行冲突（uk_dm_*_active_code）：与统一方案同构，翻译为 CONFLICT(40900)。
                throw new BusinessException(ErrorCode.CONFLICT, "内容编号在该项目下已存在，无法恢复");
            }
            audit(user, "ASSET_RESTORE", projectId, id);
        }
    }

    @Transactional
    public void purge(String type, Collection<Long> ids, AuthUser user) {
        permissions.requireAdmin(user);
        String table = requireManagedTable(type);
        for (Long id : ids) {
            if (repository.deletedProjectIds(table, user.tenantId(), id).isEmpty()) {
                throw new BusinessException(ErrorCode.BAD_REQUEST, "Asset not found");
            }
            long projectId = requireDeletedProjectScope(table, id, user);
            attachments.unbindAndRemoveAll(type, BUSINESS_TYPE, id, user);
            repository.purge(table, user.tenantId(), id);
            audit(user, "ASSET_PURGE", projectId, id);
        }
    }

    public long downloadAttachmentId(String type, long id, AuthUser user) {
        String table = requireManagedTable(type);
        List<Long> attachmentIds = repository.mainAttachmentIds(table, type, user.tenantId(), id);
        if (attachmentIds.isEmpty()) throw new BusinessException(ErrorCode.BAD_REQUEST, "资产未绑定公共附件");
        // T32：下载前按资产库中归属做项目隔离
        Map<String, Object> asset = repository.active(table, user.tenantId(), id);
        if (asset == null) throw new BusinessException(ErrorCode.BAD_REQUEST, "Asset not found");
        permissions.requireStoredProject(asset.get("project_id"), user);
        return attachmentIds.get(0);
    }

    /** 统一回收站：某类型软删记录总数（T32 按项目统计，SQL COUNT，不拉明细）。 */
    public long countDeleted(String type, long projectId, String keyword, AuthUser user) {
        String table = requireManagedTable(type);
        return repository.deletedCount(table, user.tenantId(), projectId, keyword == null ? null : keyword.trim());
    }

    /** 统一回收站原生分页（T32 按项目）：某类型软删记录按业务编号（doc_code）升序、空值末尾，取前 {@code limit} 行。 */
    public List<Map<String, Object>> listDeletedPage(String type, long projectId, String keyword, int limit, AuthUser user) {
        String table = requireManagedTable(type);
        if (limit <= 0) return List.of();
        List<Map<String, Object>> rows = repository.deletedPage(table, type, user.tenantId(), projectId, keyword == null ? null : keyword.trim(), limit);
        if (userDirectory != null) {
            for (Map<String, Object> row : rows) {
                Object raw = row.get("deleted_by");
                if (raw instanceof Number number) userDirectory.findActive(user.tenantId(), number.longValue())
                        .ifPresent(item -> row.put("deleted_by_name", item.displayName()));
            }
        }
        return rows;
    }

    /** 查询文件型内容的软删除详情，不触发附件下载。 */
    public Map<String, Object> findDeletedDetail(String type, long id, AuthUser user) {
        String table = requireManagedTable(type);
        Map<String, Object> row = repository.deleted(table, type, user.tenantId(), id);
        if (row == null) throw new BusinessException(ErrorCode.BAD_REQUEST, "Asset not found in recycle bin");
        permissions.requireStoredProject(row.get("project_id"), user);
        if (userDirectory != null && row.get("deleted_by") instanceof Number number) {
            userDirectory.findActive(user.tenantId(), number.longValue()).ifPresent(item -> row.put("deleted_by_name", item.displayName()));
        }
        // 添加附件列表
        List<Map<String, Object>> attachmentList = attachments.list(type, id, user.tenantId());
        row.put("attachments", attachmentList);
        return row;
    }

    /** 回收站行定位（跨内容表统一入口）：返回 id/doc_name/deleted 行，未找到返回空。 */
    public Optional<Map<String, Object>> findRecycleBinRow(String table, long id, long tenantId) {
        return Optional.ofNullable(repository.any(requireKnownTable(table), tenantId, id));
    }

    /** 附件投影写入口：文件型资产主文件替换（sort_order=0），旧主文件解绑。 */
    @Transactional
    public void replaceMainFile(String businessType, long businessId, long projectId, AttachmentItem attachment, AuthUser user) {
        List<Long> oldIds = repository.currentMainAttachmentIds(user.tenantId(), businessType, businessId);
        Map<String, Object> entry = new LinkedHashMap<>();
        entry.put("attachmentId", attachment.id());
        entry.put("fileName", attachment.fileName());
        attachments.replaceAll(businessType, BUSINESS_TYPE, businessId, projectId, List.of(entry), user);
        for (Long oldId : oldIds) {
            if (oldId != attachment.id()) attachmentGateway.deleteBound(oldId, BUSINESS_TYPE, String.valueOf(businessId), user);
        }
    }

    /** 内容表 owner/软删状态定位，供附件访问策略跨表校验。 */
    public Optional<Map<String, Object>> locateOwner(String table, long id, long tenantId) {
        String checked = requireKnownTable(table);
        return Optional.ofNullable(repository.any(checked, tenantId, id));
    }

    public AttachmentItem resolveAttachment(Long attachmentId, AuthUser user) {
        if (attachmentId == null || attachmentId <= 0) throw new BusinessException(ErrorCode.BAD_REQUEST, "请先通过公共附件接口上传文件");
        AttachmentItem item = attachmentGateway.get(attachmentId, user);
        if (item.uploaderId() != user.id() || !"TEMP".equals(item.status())) throw new BusinessException(ErrorCode.FORBIDDEN, "附件必须是当前用户上传的临时附件");
        return item;
    }

    public void audit(AuthUser user, String operation, long projectId, long id) {
        repository.audit(user.tenantId(), user.id(), projectId, operation, id);
    }

    private String requireManagedTable(String type) {
        if (type == null || !MANAGED_TYPES.contains(type)) throw new BusinessException(ErrorCode.BAD_REQUEST, "Unsupported asset type");
        return ContentAssetTables.tableFor(type);
    }

    private int normalizePageSize(int size) {
        return Set.of(20, 50, 100).contains(size) ? size : 20;
    }

    private String requireKnownTable(String table) {
        if (!ContentAssetTables.ALL_TABLES.contains(table)) throw new BusinessException(ErrorCode.BAD_REQUEST, "Unsupported content table");
        return table;
    }

    private void ensureProject(long id, AuthUser user) {
        // T32：统一委托模块内项目隔离守卫（租户内存在未删 + 管理员或活动成员）
        permissions.requireAccessible(id, user);
    }

    /** T32：回收站运维操作前的项目归属校验（软删行仍保留 project_id），返回项目 id。 */
    private long requireDeletedProjectScope(String table, long id, AuthUser user) {
        List<Long> projectIds = repository.deletedProjectIds(table, user.tenantId(), id);
        if (projectIds.isEmpty()) throw new BusinessException(ErrorCode.BAD_REQUEST, "Asset not found");
        return permissions.requireStoredProject(projectIds.get(0), user);
    }

    private void ensureComponent(String systemCode, long projectId, AuthUser user) {
        if (!repository.enabledComponent(user.tenantId(), projectId, systemCode)) {
            throw new BusinessException(ErrorCode.BAD_REQUEST, "Component not found");
        }
    }

    protected long nextId() { return System.currentTimeMillis() * 1000 + ThreadLocalRandom.current().nextInt(1000); }
}
