package com.ccb.datamigration.service;

import com.ccb.common.api.PageResult;
import com.ccb.common.exception.BusinessException;
import com.ccb.common.exception.ErrorCode;
import com.ccb.security.model.AuthUser;
import com.ccb.system.model.UserDirectoryPort;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class MeetingService {
  public static final String BUSINESS_TYPE="DATA_MIGRATION_MEETING"; private static final String TYPE="MEETING"; private static final Set<Integer> SIZES=Set.of(20,50,100);
  private final MeetingRepository repository; private final ContentAttachmentService attachments; private final DataMigrationPermissionService permissions; private final UserDirectoryPort users; private final DataMigrationCodeValueService values;
  public MeetingService(MeetingRepository repository,ContentAttachmentService attachments,DataMigrationPermissionService permissions,UserDirectoryPort users,DataMigrationCodeValueService values){this.repository=repository;this.attachments=attachments;this.permissions=permissions;this.users=users;this.values=values;}
  public PageResult<Map<String,Object>> list(Long project,String source,String granularity,String system,String keyword,int page,int size,AuthUser user){long projectId=permissions.requireProject(project,user);int current=Math.max(1,page),limit=pageSize(size);Map<String,Object> q=query(user.tenantId(),projectId,0,source,granularity,system,keyword);long count=repository.count(q);q.put("limit",limit);q.put("offset",(current-1)*limit);return new PageResult<>(decorate(repository.list(q),user.tenantId()),count,current,limit);}
  public Map<String,Object> findById(long id,AuthUser user){Map<String,Object> row=find(id,user.tenantId(),false);permissions.requireStoredProject(row.get("project_id"),user);return row;}
  public Map<String,Object> findRecycleBinDetail(long id,AuthUser user){Map<String,Object> row=find(id,user.tenantId(),true);permissions.requireStoredProject(row.get("project_id"),user);return row;}
  @Transactional public Map<String,Object> create(Map<String,Object> body,AuthUser user){long project=permissions.requireProject(number(body.get("projectId"),"projectId"),user);String title=text(body.get("meetingTitle"),"meetingTitle"),granularity=text(body.get("granularity"),"granularity"),source=text(body.get("meetingSource"),"meetingSource");validate(granularity,source,user);long id=nextId();String code=nullable(body.get("meetingCode"));if(code==null)code="MEET-"+id;else unique(project,code,null,user);try{repository.insert(data(id,project,code,title,granularity,source,body,user));}catch(DataIntegrityViolationException ex){throw codeConflict();}saveAttachments(id,project,body,user);saveSystems(id,project,body,user);saveIssues(id,project,body,user);audit(user,"MEETING_CREATE",project,id);return find(id,user.tenantId(),false);}
  @Transactional public Map<String,Object> update(long id,Map<String,Object> body,AuthUser user){Map<String,Object> old=find(id,user.tenantId(),false);permissions.requireWrite(user,((Number)old.get("created_by")).longValue());long project=permissions.requireStoredProject(old.get("project_id"),user);String title=text(body.getOrDefault("meetingTitle",old.get("meeting_title")),"meetingTitle"),granularity=text(body.getOrDefault("granularity",old.get("granularity")),"granularity"),source=text(body.getOrDefault("meetingSource",old.get("meeting_source")),"meetingSource"),code=text(body.getOrDefault("meetingCode",old.get("meeting_code")),"meetingCode");validate(granularity,source,user);unique(project,code,id,user);try{if(repository.update(data(id,project,code,title,granularity,source,body,user))!=1)throw conflict();}catch(DataIntegrityViolationException ex){throw codeConflict();}saveAttachments(id,project,body,user);saveSystems(id,project,body,user);saveIssues(id,project,body,user);audit(user,"MEETING_UPDATE",project,id);return find(id,user.tenantId(),false);}
  @Transactional public void delete(List<Long> ids,AuthUser user){for(Long id:ids(ids)){Map<String,Object> row=find(id,user.tenantId(),false);long project=permissions.requireStoredProject(row.get("project_id"),user);permissions.requireWrite(user,((Number)row.get("created_by")).longValue());if(repository.delete(user.tenantId(),id,user.id())!=1)throw conflict();audit(user,"MEETING_DELETE",project,id);}}
  public long countRecycleBin(long project,String keyword,AuthUser user){permissions.requireAdmin(user);permissions.requireAccessible(project,user);return repository.count(query(user.tenantId(),project,1,null,null,null,keyword));}
  public List<Map<String,Object>> fetchRecycleBinPage(long project,String keyword,int limit,AuthUser user){permissions.requireAdmin(user);permissions.requireAccessible(project,user);if(limit<=0)return List.of();Map<String,Object> q=query(user.tenantId(),project,1,null,null,null,keyword);q.put("limit",limit);return decorate(repository.list(q),user.tenantId());}
  @Transactional public void restore(List<Long> ids,AuthUser user){permissions.requireAdmin(user);for(Long id:ids(ids)){Map<String,Object> row=find(id,user.tenantId(),true);long project=permissions.requireStoredProject(row.get("project_id"),user);try{if(repository.restore(user.tenantId(),id,user.id())!=1)throw conflict();}catch(DataIntegrityViolationException ex){throw codeConflict();}audit(user,"MEETING_RESTORE",project,id);}}
  @Transactional public void purge(List<Long> ids,AuthUser user){permissions.requireAdmin(user);for(Long id:ids(ids)){Map<String,Object> row=find(id,user.tenantId(),true);long project=permissions.requireStoredProject(row.get("project_id"),user);attachments.unbindAndRemoveAll(TYPE,BUSINESS_TYPE,id,user);if(repository.purge(user.tenantId(),id)!=1)throw conflict();audit(user,"MEETING_PURGE",project,id);}}
  @Transactional public void purgeAll(Long project,AuthUser user){permissions.requireAdmin(user);long scope=permissions.requireProject(project,user);for(Long id:repository.deletedIds(user.tenantId(),scope))attachments.unbindAndRemoveAll(TYPE,BUSINESS_TYPE,id,user);repository.purgeDeletedProject(user.tenantId(),scope);audit(user,"MEETING_PURGE_ALL",scope,0);}
  public List<Map<String,Object>> getIssueOptions(Long project,AuthUser user){return repository.issueOptions(user.tenantId(),permissions.requireProject(project,user));}
  public List<Map<String,Object>> getMeetingAttachments(long id,AuthUser user){scope(id,user);return attachments.list(TYPE,id,user.tenantId());}
  @Transactional public void deleteAttachment(long meeting,long attachment,AuthUser user){Map<String,Object> row=find(meeting,user.tenantId(),false);long project=permissions.requireStoredProject(row.get("project_id"),user);permissions.requireWrite(user,((Number)row.get("created_by")).longValue());if(attachments.softDelete(TYPE,meeting,attachment,user)!=1)throw new BusinessException(ErrorCode.BAD_REQUEST,"附件不存在或已删除");audit(user,"MEETING_ATTACHMENT_DELETE",project,meeting);}
  public List<Map<String,Object>> getAttachmentRecycleBin(long id,AuthUser user){scope(id,user);return attachments.listDeleted(TYPE,id,user.tenantId());}
  @Transactional public void restoreAttachment(long meeting,long attachment,AuthUser user){permissions.requireAdmin(user);long project=scope(meeting,user);if(repository.restoreAttachment(user.tenantId(),meeting,attachment)!=1)throw new BusinessException(ErrorCode.BAD_REQUEST,"附件不存在或未删除");audit(user,"MEETING_ATTACHMENT_RESTORE",project,meeting);}
  public PageResult<Map<String,Object>> attachmentRecycleBinList(Long project,String keyword,int page,int size,AuthUser user){permissions.requireAdmin(user);long scope=permissions.requireProject(project,user);int current=Math.max(1,page),limit=pageSize(size);Map<String,Object> q=new LinkedHashMap<>();q.put("tenantId",user.tenantId());q.put("projectId",scope);q.put("keyword",keyword);q.put("limit",limit);q.put("offset",(current-1)*limit);return new PageResult<>(decorate(repository.deletedAttachments(q),user.tenantId()),repository.deletedAttachmentCount(q),current,limit);}
  @Transactional public void restoreAttachments(List<Long> ids,AuthUser user){permissions.requireAdmin(user);for(Long id:ids(ids)){long meeting=attachments.requireSoftDeletedRow(id,user);long project=scope(meeting,user);attachments.restoreByIds(List.of(id),user);audit(user,"MEETING_ATTACHMENT_RESTORE",project,meeting);}}
  @Transactional public void purgeAttachments(List<Long> ids,AuthUser user){permissions.requireAdmin(user);for(Long id:ids(ids)){long meeting=attachments.requireSoftDeletedRow(id,user);long project=scope(meeting,user);attachments.purgeByIds(List.of(id),user);audit(user,"MEETING_ATTACHMENT_PURGE",project,meeting);}}
  @Transactional public void purgeAllAttachments(Long project,AuthUser user){permissions.requireAdmin(user);long scope=permissions.requireProject(project,user);attachments.purgeByIds(repository.deletedAttachmentRows(user.tenantId(),scope),user);audit(user,"MEETING_ATTACHMENT_PURGE_ALL",scope,0);}
  private Map<String,Object> find(long id,long tenant,boolean deleted){Map<String,Object> row=deleted?repository.requireDeleted(tenant,id):repository.require(tenant,id);decorate(List.of(row),tenant);row.put("attachments",attachments.list(TYPE,id,tenant));return row;}
  private void saveSystems(long id,long project,Map<String,Object> body,AuthUser user){if(!body.containsKey("systemCodes"))return;List<String> codes=new ArrayList<>();for(Object raw:list(body.get("systemCodes"))){String code=String.valueOf(raw).trim();if(!code.isEmpty()&&!codes.contains(code))codes.add(code);}for(String code:codes)if(!repository.system(user.tenantId(),project,code))throw new BusinessException(ErrorCode.BAD_REQUEST,"系统编号不属于所选项目");repository.replaceSystems(user.tenantId(),id,project,codes,user.id());}
  private void saveIssues(long id,long project,Map<String,Object> body,AuthUser user){if(!body.containsKey("issueIds"))return;List<Long> ids=new ArrayList<>();for(Object raw:list(body.get("issueIds"))){long issue;try{issue=Long.parseLong(String.valueOf(raw));}catch(NumberFormatException ex){throw new BusinessException(ErrorCode.BAD_REQUEST,"问题ID无效");}if(!ids.contains(issue))ids.add(issue);}for(Long issue:ids)if(!repository.issue(user.tenantId(),project,issue))throw new BusinessException(ErrorCode.BAD_REQUEST,"问题不存在或不属于当前项目");repository.replaceIssues(user.tenantId(),id,ids,user.id());}
  @SuppressWarnings("unchecked") private void saveAttachments(long id,long project,Map<String,Object> body,AuthUser user){if(!body.containsKey("attachments")&&body.get("attachmentId")==null)return;List<Map<String,Object>> rows=new ArrayList<>();Object raw=body.get("attachments");if(raw instanceof Collection<?> c)for(Object item:c)if(item instanceof Map<?,?>)rows.add((Map<String,Object>)item);if(rows.isEmpty()&&body.get("attachmentId")!=null){Map<String,Object> one=new LinkedHashMap<>();one.put("attachmentId",body.get("attachmentId"));one.put("fileName",body.get("fileName"));rows.add(one);}for(Map<String,Object> row:rows)if(row.get("attachmentId")!=null)attachments.ensureAttachmentExists(number(row.get("attachmentId"),"attachmentId"),user);attachments.replaceAll(TYPE,BUSINESS_TYPE,id,project,rows,user);}
  private void unique(long project,String code,Long exclude,AuthUser user){Map<String,Object> p=new LinkedHashMap<>();p.put("tenantId",user.tenantId());p.put("projectId",project);p.put("code",code);p.put("excludeId",exclude);if(repository.code(p))throw new BusinessException(ErrorCode.CONFLICT,"会议编号在该项目下已存在");}
  private Map<String,Object> query(long tenant,long project,int deleted,String source,String granularity,String system,String keyword){Map<String,Object> p=new LinkedHashMap<>();p.put("tenantId",tenant);p.put("projectId",project);p.put("deleted",deleted);p.put("meetingSource",source);p.put("granularity",granularity);p.put("systemCode",system);p.put("keyword",keyword);return p;}
  private Map<String,Object> data(long id,long project,String code,String title,String granularity,String source,Map<String,Object> body,AuthUser user){Map<String,Object> p=new LinkedHashMap<>();p.put("id",id);p.put("tenantId",user.tenantId());p.put("projectId",project);p.put("code",code);p.put("title",title);p.put("granularity",granularity);p.put("meetingSource",source);p.put("content",nullable(body.get("meetingContent")));p.put("conclusion",nullable(body.get("meetingConclusion")));p.put("scenario",nullable(body.get("businessScenario")));p.put("keywords",keywords(body.get("keywords")));p.put("actorId",user.id());return p;}
  private long scope(long id,AuthUser user){return permissions.requireStoredProject(repository.project(user.tenantId(),id),user);} private void validate(String g,String s,AuthUser u){values.requireActive(DataMigrationCodeValueService.DM_MEETING_GRANULARITY,"会议纪要颗粒度",g,u);values.requireActive(DataMigrationCodeValueService.DM_MEETING_SOURCE,"会议纪要来源",s,u);} private void audit(AuthUser u,String op,long project,long id){repository.audit(u.tenantId(),u.id(),project,op,id);} private BusinessException conflict(){return new BusinessException(ErrorCode.CONFLICT,"会议纪要状态已变化，请刷新后重试");} private BusinessException codeConflict(){return new BusinessException(ErrorCode.CONFLICT,"会议编号在该项目下已存在");}
  private static int pageSize(int size){return SIZES.contains(size)?size:20;} private static long nextId(){return System.currentTimeMillis()*1000+ThreadLocalRandom.current().nextInt(1000);} private static String nullable(Object o){if(o==null)return null;String s=String.valueOf(o).trim();return s.isEmpty()?null:s;} private static String text(Object o,String f){String s=nullable(o);if(s==null)throw new BusinessException(ErrorCode.BAD_REQUEST,f+"不能为空");return s;} private static long number(Object o,String f){try{if(o==null)throw new NumberFormatException();return Long.parseLong(String.valueOf(o).trim());}catch(NumberFormatException ex){throw new BusinessException(ErrorCode.BAD_REQUEST,f+"无效");}} private static List<?> list(Object o){return o instanceof Collection<?> c?new ArrayList<>(c):o==null?List.of():List.of(o);} private static List<Long> ids(List<Long> ids){return ids==null?List.of():ids.stream().filter(Objects::nonNull).distinct().toList();} private static String keywords(Object raw){if(raw instanceof Collection<?> c){List<String> values=c.stream().filter(Objects::nonNull).map(String::valueOf).filter(s->!s.isBlank()).toList();return values.isEmpty()?null:"["+values.stream().map(s->"\""+s.replace("\\","\\\\").replace("\"","\\\"")+"\"").reduce((a,b)->a+","+b).orElse("")+"]";}String value=nullable(raw);return value==null?null:(value.startsWith("[")?value:"[\""+value.replace("\\","\\\\").replace("\"","\\\"")+"\"]");}
  private List<Map<String,Object>> decorate(List<Map<String,Object>> rows,long tenant){if(users!=null)for(Map<String,Object> row:rows){name(row,"created_by","created_by_name",tenant);name(row,"updated_by","updated_by_name",tenant);name(row,"deleted_by","deleted_by_name",tenant);}return rows;} private void name(Map<String,Object> row,String key,String output,long tenant){if(row.get(key) instanceof Number n)users.findActive(tenant,n.longValue()).ifPresent(user->row.put(output,user.displayName()));}
}
