package com.ccb.datamigration.service;

import com.ccb.attachment.integration.AttachmentItem;
import com.ccb.common.api.PageResult;
import com.ccb.common.exception.BusinessException;
import com.ccb.common.exception.ErrorCode;
import com.ccb.security.model.AuthUser;
import com.ccb.system.model.UserDirectoryPort;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class PlanService {
  public static final String BUSINESS_TYPE=ContentFileAssetService.BUSINESS_TYPE; private static final String TYPE="PLAN"; private static final long MAX=50L*1024*1024; private static final String NONE="";
  private final PlanRepository repository; private final ContentAttachmentService attachments; private final ContentFileAssetService fileAssets; private final DataMigrationPermissionService permissions; private final UserDirectoryPort users; private final ContentDocCodeGenerator codes; private final DataMigrationCodeValueService values;
  public PlanService(PlanRepository repository,ContentAttachmentService attachments,ContentFileAssetService fileAssets,DataMigrationPermissionService permissions,UserDirectoryPort users,ContentDocCodeGenerator codes,DataMigrationCodeValueService values){this.repository=repository;this.attachments=attachments;this.fileAssets=fileAssets;this.permissions=permissions;this.users=users;this.codes=codes;this.values=values;}
  public PageResult<Map<String,Object>> list(Long projectId,String granularity,String planType,String systemCode,String keyword,int page,int size,AuthUser user){long project=permissions.requireProject(projectId,user);int current=Math.max(1,page);Map<String,Object> q=query(user.tenantId(),project,0,granularity,planType,systemCode,keyword);long total=repository.count(q);q.put("limit",size);q.put("offset",Math.max(0,(current-1)*size));return new PageResult<>(decorate(repository.list(q),user.tenantId()),total,current,size);}
  public Map<String,Object> detail(long id,AuthUser user){Map<String,Object> row=repository.require(user.tenantId(),id);permissions.requireStoredProject(row.get("project_id"),user);decorate(List.of(row),user.tenantId());row.put("attachments",attachments.list(TYPE,id,user.tenantId()));return row;}
  @Transactional public Map<String,Object> create(Map<String,Object> body,AuthUser user){long project=requireLong(body.get("projectId"),"所属项目不能为空");String granularity=requireText(body.get("granularity"),"资产颗粒度不能为空");String type=requireText(first(body.get("planType"),body.get("plan_type")),"迁移方案类型不能为空");String system=system(granularity,optional(first(body.get("systemCode"),body.get("system_code"))));values.requireActive(DataMigrationCodeValueService.DM_PLAN_GRANULARITY,"资产颗粒度",granularity,user);values.requireActive(DataMigrationCodeValueService.DM_PLAN_TYPE,"迁移方案类型",type,user);permissions.requireAccessible(project,user);if("SYSTEM".equals(granularity))requireSystem(system,project,user);List<Map<String,Object>> files=entries(files(body),Set.of(),user,true);if(files.isEmpty())throw new BusinessException(ErrorCode.BAD_REQUEST,"至少上传一个源文件");String name=optional(body.get("planName"));if(name==null)name=withoutExtension(String.valueOf(files.get(0).get("fileName")));if(name==null||name.isBlank())throw new BusinessException(ErrorCode.BAD_REQUEST,"方案名称不能为空");assertDimension(user.tenantId(),project,granularity,type,system,null);long id=nextId();try{repository.insert(p(id,user,project,granularity,type,system,name.trim(),optional(first(body.get("summary"),body.get("planSummary"),body.get("plan_summary")))));}catch(DataIntegrityViolationException ex){throw dimensionConflict();}attachments.replaceAll(TYPE,BUSINESS_TYPE,id,project,files,user);audit(user,"PLAN_UPLOAD",project,id);return detail(id,user);}
  @Transactional public Map<String,Object> update(long id,Map<String,Object> body,AuthUser user){Map<String,Object> old=repository.requireRaw(user.tenantId(),id);permissions.requireWrite(user,((Number)old.get("owner_id")).longValue());long project=permissions.requireStoredProject(old.get("project_id"),user);String granularity=body.containsKey("granularity")?requireText(body.get("granularity"),"资产颗粒度不能为空"):(String)old.get("granularity");String type=body.containsKey("planType")||body.containsKey("plan_type")?requireText(first(body.get("planType"),body.get("plan_type")),"迁移方案类型不能为空"):(String)old.get("plan_type");boolean hasSystem=body.containsKey("systemCode")||body.containsKey("system_code");String system=hasSystem?system(granularity,optional(first(body.get("systemCode"),body.get("system_code")))):(String)old.get("system_code");values.requireActive(DataMigrationCodeValueService.DM_PLAN_GRANULARITY,"资产颗粒度",granularity,user);values.requireActive(DataMigrationCodeValueService.DM_PLAN_TYPE,"迁移方案类型",type,user);permissions.requireAccessible(project,user);if("SYSTEM".equals(granularity))requireSystem(system,project,user);assertDimension(user.tenantId(),project,granularity,type,system,id);Map<String,Object> data=p(id,user,project,granularity,type,system,body.containsKey("planName")?requireText(body.get("planName"),"方案名称不能为空"):null,optional(first(body.get("summary"),body.get("planSummary"),body.get("plan_summary"))));data.put("planSummarySet",body.containsKey("summary")||body.containsKey("planSummary")||body.containsKey("plan_summary"));List<Map<String,Object>> input=files(body);if(!input.isEmpty()){update(data);attachments.replaceAll(TYPE,BUSINESS_TYPE,id,project,entries(input,repository.attachmentIds(user.tenantId(),id),user,false),user);}else update(data);audit(user,"PLAN_UPDATE",project,id);return detail(id,user);}
  @Transactional public void delete(List<Long> ids,AuthUser user){for(Long id:ids){Map<String,Object> row=repository.requireRaw(user.tenantId(),id);long project=permissions.requireStoredProject(row.get("project_id"),user);permissions.requireWrite(user,((Number)row.get("owner_id")).longValue());if(repository.softDelete(user.tenantId(),id,user.id())!=1)throw conflict();audit(user,"PLAN_DELETE",project,id);}}
  public String download(long id,AuthUser user){permissions.requireStoredProject(repository.requireRaw(user.tenantId(),id).get("project_id"),user);List<Long> ids=repository.mainAttachmentIds(user.tenantId(),id);if(ids.isEmpty())throw new BusinessException(ErrorCode.BAD_REQUEST,"迁移方案未绑定源文件");return "/api/attachments/"+ids.get(0)+"/download";}
  public List<Map<String,Object>> listAttachments(long id,AuthUser user){permissions.requireStoredProject(repository.requireRaw(user.tenantId(),id).get("project_id"),user);return attachments.list(TYPE,id,user.tenantId());}
  public long countRecycleBin(long project,String keyword,AuthUser user){permissions.requireAdmin(user);permissions.requireAccessible(project,user);return repository.count(query(user.tenantId(),project,1,null,null,null,keyword));}
  public List<Map<String,Object>> fetchRecycleBinPage(long project,String keyword,int limit,AuthUser user){permissions.requireAdmin(user);permissions.requireAccessible(project,user);if(limit<=0)return List.of();Map<String,Object> q=query(user.tenantId(),project,1,null,null,null,keyword);q.put("limit",limit);return decorate(repository.list(q),user.tenantId());}
  public Map<String,Object> findRecycleBinDetail(long id,AuthUser user){Map<String,Object> row=repository.requireDeleted(user.tenantId(),id);permissions.requireStoredProject(row.get("project_id"),user);decorate(List.of(row),user.tenantId());row.put("attachments",attachments.list(TYPE,id,user.tenantId()));return row;}
  @Transactional public void restore(List<Long> ids,AuthUser user){permissions.requireAdmin(user);for(Long id:ids){long project=permissions.requireStoredProject(repository.requireDeletedProject(user.tenantId(),id),user);try{if(repository.restore(user.tenantId(),id)!=1)throw conflict();}catch(DataIntegrityViolationException ex){throw dimensionConflict();}audit(user,"PLAN_RESTORE",project,id);}}
  @Transactional public void purge(List<Long> ids,AuthUser user){permissions.requireAdmin(user);for(Long id:ids){long project=permissions.requireStoredProject(repository.requireDeletedProject(user.tenantId(),id),user);attachments.unbindAndRemoveAll(TYPE,BUSINESS_TYPE,id,user);if(repository.purge(user.tenantId(),id)!=1)throw conflict();audit(user,"PLAN_PURGE",project,id);}}
  private Map<String,Object> query(long tenant,long project,int deleted,String granularity,String type,String system,String keyword){Map<String,Object> q=new LinkedHashMap<>();q.put("tenantId",tenant);q.put("projectId",project);q.put("deleted",deleted);q.put("granularity",granularity);q.put("planType",type);q.put("systemCode",system);q.put("keyword",keyword);return q;}
  private Map<String,Object> p(long id,AuthUser user,long project,String granularity,String type,String system,String name,String summary){Map<String,Object> q=query(user.tenantId(),project,0,granularity,type,system,null);q.put("id",id);q.put("docCode",codes.generate(TYPE));q.put("docName",name);q.put("planSummary",summary);q.put("actorId",user.id());return q;}
  private void update(Map<String,Object> p){try{if(repository.update(p)!=1)throw conflict();}catch(DataIntegrityViolationException ex){throw dimensionConflict();}}
  private void assertDimension(long tenant,long project,String granularity,String type,String system,Long exclude){Map<String,Object> q=query(tenant,project,0,granularity,type,system,null);q.put("excludeId",exclude);if(repository.dimensionExists(q))throw dimensionConflict();}
  private void requireSystem(String system,long project,AuthUser user){if(!repository.enabledComponent(user.tenantId(),project,system))throw new BusinessException(ErrorCode.BAD_REQUEST,"关联系统不存在或不属于当前项目");}
  private List<Map<String,Object>> decorate(List<Map<String,Object>> rows,long tenant){if(users!=null)for(Map<String,Object> row:rows){name(row,"created_by","created_by_name",tenant);name(row,"updated_by","updated_by_name",tenant);name(row,"deleted_by","deleted_by_name",tenant);}return rows;}private void name(Map<String,Object> row,String key,String out,long tenant){if(row.get(key) instanceof Number n)users.findActive(tenant,n.longValue()).ifPresent(u->row.put(out,u.displayName()));}
  private List<Map<String,Object>> entries(List<Map<String,Object>> files,Set<Long> bound,AuthUser user,boolean all){List<Map<String,Object>> out=new ArrayList<>();for(Map<String,Object> file:files){long id=requireLong(file.get("attachmentId"),"附件不能为空");if(all||!bound.contains(id)){AttachmentItem item=fileAssets.resolveAttachment(id,user);if(item.fileSize()<=0||item.fileSize()>MAX)throw new BusinessException(ErrorCode.BAD_REQUEST,"文件 "+item.fileName()+" 为空或超过 50 MB");out.add(Map.of("attachmentId",item.id(),"fileName",item.fileName()));}else{Map<String,Object> row=new LinkedHashMap<>();row.put("attachmentId",id);row.put("fileName",file.get("fileName"));out.add(row);}}return out;}
  @SuppressWarnings("unchecked") private List<Map<String,Object>> files(Map<String,Object> body){List<Map<String,Object>> out=new ArrayList<>();Object raw=first(body.get("files"),body.get("attachments"));if(raw instanceof Collection<?> c)for(Object item:c)if(item instanceof Map<?,?>)out.add((Map<String,Object>)item);if(out.isEmpty()&&body.get("attachmentId")!=null){Map<String,Object> one=new LinkedHashMap<>();one.put("attachmentId",body.get("attachmentId"));one.put("fileName",body.get("fileName"));out.add(one);}return out;}
  private String system(String granularity,String system){if("SYSTEM".equals(granularity)){if(system==null)throw new BusinessException(ErrorCode.BAD_REQUEST,"系统级方案必须选择关联系统");return system;}return NONE;} private void audit(AuthUser u,String op,long project,long id){repository.audit(u.tenantId(),u.id(),project,op,id);} private BusinessException conflict(){return new BusinessException(ErrorCode.CONFLICT,"迁移方案状态已变化，请刷新后重试");}private BusinessException dimensionConflict(){return new BusinessException(ErrorCode.CONFLICT,"同一项目下该(颗粒度+方案类型+关联系统)已存在迁移方案，仅允许一条");}
  private static long nextId(){return System.currentTimeMillis()*1000+ThreadLocalRandom.current().nextInt(1000);}private static Object first(Object... vs){for(Object v:vs)if(v!=null)return v;return null;}private static long requireLong(Object raw,String msg){try{if(raw==null)throw new NumberFormatException();return Long.parseLong(String.valueOf(raw).trim());}catch(NumberFormatException ex){throw new BusinessException(ErrorCode.BAD_REQUEST,msg);}}private static String optional(Object raw){if(raw==null)return null;String v=String.valueOf(raw).trim();return v.isEmpty()?null:v;}private static String requireText(Object raw,String msg){String v=optional(raw);if(v==null)throw new BusinessException(ErrorCode.BAD_REQUEST,msg);return v;}private static String withoutExtension(String v){int dot=v.lastIndexOf('.');return dot>0?v.substring(0,dot):v;}
}
