/*
 * 文件：server/src/modules/test-management/src/main/java/com/ccb/testmanagement/analytics/TestAnalyticsAdvancedService.java
 * 说明：分析统计的服务、策略或接口实现。
 * 用途：承载模块边界内的查询、校验、事务、权限或文件处理职责。
 * 作者：hengguan
 */
package com.ccb.testmanagement.analytics;

// 关键逻辑：所有读写以认证用户的租户、测试大类和项目为共同边界；写入由事务与审计保持一致性。

import com.ccb.common.exception.BusinessException;
import com.ccb.common.exception.ErrorCode;
import com.ccb.security.model.AuthUser;
import com.ccb.testmanagement.report.TestReportService;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDate;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;

/** 四张预置报表的专属统计、筛选元数据和归档快照对比。 */
@Service public class TestAnalyticsAdvancedService {
 private final JdbcTemplate jdbc;private final ObjectMapper json;private final TestReportService reports;
 public TestAnalyticsAdvancedService(JdbcTemplate jdbc,ObjectMapper json,TestReportService reports){this.jdbc=jdbc;this.json=json;this.reports=reports;}
 public Map<String,Object> filters(String d,long p,AuthUser u){Map<String,Object> root=reports.tree(d,p,u);List<Map<String,Object>> systems=(List<Map<String,Object>>)root.get("systems");List<Map<String,Object>> rounds=jdbc.queryForList("SELECT id,round_name,planned_start_date,planned_end_date,status FROM tm_test_round WHERE tenant_id=? AND test_domain=? AND project_id=? AND deleted=0 ORDER BY sort_no,id",u.tenantId(),d,p);List<Map<String,Object>> cycles=jdbc.queryForList("SELECT c.id,c.round_id,c.cycle_name,c.planned_start_date,c.planned_end_date,c.status FROM tm_test_cycle c JOIN tm_test_round r ON r.id=c.round_id AND r.tenant_id=c.tenant_id WHERE c.tenant_id=? AND r.test_domain=? AND r.project_id=? AND c.deleted=0 AND r.deleted=0 ORDER BY c.sort_no,c.id",u.tenantId(),d,p);return Map.of("systems",systems,"rounds",rounds,"cycles",cycles,"case_types",options(d,p,"case_type",u),"defect_categories",options(d,p,"defect_category",u),"severities",options(d,p,"severity",u),"priorities",options(d,p,"priority",u),"urgencies",options(d,p,"urgency",u));}
 public Map<String,Object> preset(String d,long p,String key,Map<String,Object> f,AuthUser u){reports.tree(d,p,u);Long sys=num(f.get("physical_subsystem_id"));Long round=num(f.get("round_id"));Long cycle=num(f.get("cycle_id"));String view=String.valueOf(f.getOrDefault("view","TABLE")).toUpperCase(Locale.ROOT);Map<String,Object> out=new LinkedHashMap<>();out.put("key",key);out.put("view",view);out.put("filters",f);switch(key){case "SCOPE_COVERAGE"->coverage(d,p,sys,out,u);case "EXECUTION_PROGRESS"->execution(d,p,sys,round,cycle,out,u);case "DEFECT_DISTRIBUTION"->defects(d,p,sys,round,cycle,view,out,u);case "PERSONNEL_WORKLOAD"->workload(d,p,sys,round,cycle,String.valueOf(f.getOrDefault("perspective","EXECUTOR")),out,u);default->throw bad("预置报表不存在");}return out;}
 @Transactional public List<Map<String,Object>> archive(String d,long p,long round,AuthUser u){reports.tree(d,p,u);Long exists=jdbc.queryForObject("SELECT COUNT(*) FROM tm_test_round WHERE id=? AND tenant_id=? AND test_domain=? AND project_id=? AND deleted=0",Long.class,round,u.tenantId(),d,p);if(exists==null||exists==0)throw bad("轮次不存在");List<Map<String,Object>> saved=new ArrayList<>();for(String key:List.of("SCOPE_COVERAGE","EXECUTION_PROGRESS","DEFECT_DISTRIBUTION","PERSONNEL_WORKLOAD")){Map<String,Object> data=preset(d,p,key,Map.of("round_id",round),u);long id=next();jdbc.update("INSERT INTO tm_test_analytics_snapshot(id,tenant_id,test_domain,project_id,round_id,report_key,snapshot_json,archived_by) VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE snapshot_json=VALUES(snapshot_json),archived_by=VALUES(archived_by),archived_at=CURRENT_TIMESTAMP",id,u.tenantId(),d,p,round,key,encode(data),u.id());saved.add(Map.of("report_key",key,"archived_at",String.valueOf(java.time.LocalDateTime.now())));}return saved;}
 public List<Map<String,Object>> compare(String d,long p,List<Long> rounds,AuthUser u){reports.tree(d,p,u);if(rounds==null||rounds.size()<2)throw bad("请选择至少两个已归档轮次");List<Map<String,Object>> out=new ArrayList<>();for(Long r:rounds){List<Map<String,Object>> rows=jdbc.queryForList("SELECT report_key,snapshot_json,archived_at FROM tm_test_analytics_snapshot WHERE tenant_id=? AND test_domain=? AND project_id=? AND round_id=? ORDER BY report_key",u.tenantId(),d,p,r);Map<String,Object> item=new LinkedHashMap<>();item.put("round_id",r);item.put("round_name",jdbc.queryForObject("SELECT round_name FROM tm_test_round WHERE id=? AND tenant_id=?",String.class,r,u.tenantId()));item.put("archived_at",rows.isEmpty()?null:rows.get(0).get("archived_at"));for(Map<String,Object> row:rows){Map<String,Object> source=map(row.get("snapshot_json"));Map<String,Object> summary=map(source.get("summary"));String key=String.valueOf(row.get("report_key"));item.put(key+"_scope_total",summary.getOrDefault("scope_total",0));item.put(key+"_case_total",summary.getOrDefault("case_total",0));item.put(key+"_success_rate",summary.getOrDefault("success_rate",0));item.put(key+"_defect_total",summary.getOrDefault("defect_total",0));}out.add(item);}return out;}
 private void coverage(String d,long p,Long sys,Map<String,Object> out,AuthUser u){String extra=sys==null?"":" AND s.physical_subsystem_id="+sys;List<Map<String,Object>> rows=jdbc.queryForList("SELECT COALESCE(NULLIF(ps.short_name,''),REPLACE(ps.name,'物理子系统','')) AS dimension,COUNT(s.id) AS scope_total,SUM(CASE WHEN EXISTS(SELECT 1 FROM tm_test_case c WHERE c.tenant_id=s.tenant_id AND c.scope_id=s.id AND c.deleted=0 AND c.invalidated=0) THEN 1 ELSE 0 END) AS covered_total,SUM(CASE WHEN NOT EXISTS(SELECT 1 FROM tm_test_case c WHERE c.tenant_id=s.tenant_id AND c.scope_id=s.id AND c.deleted=0 AND c.invalidated=0) THEN 1 ELSE 0 END) AS uncovered_total FROM tm_test_scope s JOIN tm_test_participating_system part ON part.tenant_id=s.tenant_id AND part.test_domain=s.test_domain AND part.project_id=s.project_id AND part.physical_subsystem_id=s.physical_subsystem_id AND part.enabled=1 AND part.deleted=0 JOIN arch_physical_subsystem ps ON ps.id=s.physical_subsystem_id WHERE s.tenant_id=? AND s.test_domain=? AND s.project_id=? AND s.deleted=0 AND s.invalidated=0"+extra+" GROUP BY s.physical_subsystem_id,ps.name,ps.short_name ORDER BY dimension",u.tenantId(),d,p);for(Map<String,Object> row:rows){long total=n(row.get("scope_total"));row.put("coverage_rate",total==0?0:Math.round(n(row.get("covered_total"))*10000D/total)/100D);}out.put("rows",rows);out.put("charts",Map.of("BAR",rows,"TABLE",rows));}
 private void execution(String d,long p,Long sys,Long round,Long cycle,Map<String,Object> out,AuthUser u){String x=(sys==null?"":" AND e.physical_subsystem_id="+sys)+(round==null?"":" AND e.round_id="+round)+(cycle==null?"":" AND e.cycle_id="+cycle);List<Map<String,Object>> rows=jdbc.queryForList("SELECT COALESCE(NULLIF(ps.short_name,''),REPLACE(ps.name,'物理子系统','')) AS dimension,COUNT(e.id) AS execution_total,SUM(e.execution_status='UNEXECUTED') AS unexecuted_count,SUM(e.execution_status='RUNNING') AS running_count,SUM(e.execution_status='SUCCESS') AS success_count,SUM(e.execution_status='FAILED') AS failed_count,SUM(e.execution_status='BLOCKED') AS blocked_count FROM tm_test_execution e JOIN tm_test_participating_system part ON part.tenant_id=e.tenant_id AND part.test_domain=e.test_domain AND part.project_id=e.project_id AND part.physical_subsystem_id=e.physical_subsystem_id AND part.enabled=1 AND part.deleted=0 JOIN arch_physical_subsystem ps ON ps.id=e.physical_subsystem_id WHERE e.tenant_id=? AND e.test_domain=? AND e.project_id=? AND e.deleted=0"+x+" GROUP BY e.physical_subsystem_id,ps.name,ps.short_name ORDER BY dimension",u.tenantId(),d,p);for(Map<String,Object> r:rows){long total=n(r.get("execution_total"));r.put("execution_rate",total==0?0:Math.round((n(r.get("success_count"))+n(r.get("failed_count"))+n(r.get("blocked_count")))*10000D/total)/100D);r.put("success_rate",total==0?0:Math.round(n(r.get("success_count"))*10000D/total)/100D);}out.put("rows",rows);out.put("trend",jdbc.queryForList("SELECT DATE(COALESCE(executed_at,created_at)) AS dimension,SUM(execution_status IN ('SUCCESS','FAILED','BLOCKED')) AS completed_count FROM tm_test_execution WHERE tenant_id=? AND test_domain=? AND project_id=? AND deleted=0"+x+" GROUP BY DATE(COALESCE(executed_at,created_at)) ORDER BY dimension",u.tenantId(),d,p));}
 private void defects(String d,long p,Long sys,Long round,Long cycle,String view,Map<String,Object> out,AuthUser u){String x=(sys==null?"":" AND physical_subsystem_id="+sys)+(round==null?"":" AND round_id="+round)+(cycle==null?"":" AND cycle_id="+cycle);String sql; if("MATRIX".equals(view))sql="SELECT severity AS row_dimension,urgency AS column_dimension,COUNT(*) AS value FROM tm_test_defect WHERE tenant_id=? AND test_domain=? AND project_id=? AND deleted=0"+x+" GROUP BY severity,urgency";else if("OVERDUE".equals(view))sql="SELECT defect_code,summary,status,(SELECT display_name FROM sys_user u WHERE u.id=d.handler_id AND u.tenant_id=d.tenant_id) AS handler_name,DATEDIFF(CURRENT_DATE,DATE(proposed_at)) AS overdue_days FROM tm_test_defect d WHERE tenant_id=? AND test_domain=? AND project_id=? AND deleted=0 AND status NOT IN ('RESOLVED','CLOSED')"+x+" ORDER BY overdue_days DESC";else if("SYSTEM".equals(view))sql="SELECT COALESCE(NULLIF(ps.short_name,''),REPLACE(ps.name,'物理子系统','')) AS dimension,COUNT(*) AS value FROM tm_test_defect d JOIN arch_physical_subsystem ps ON ps.id=d.physical_subsystem_id WHERE d.tenant_id=? AND d.test_domain=? AND d.project_id=? AND d.deleted=0"+x.replace("physical_subsystem_id","d.physical_subsystem_id").replace("round_id","d.round_id").replace("cycle_id","d.cycle_id")+" GROUP BY d.physical_subsystem_id,ps.name,ps.short_name ORDER BY value DESC";else {String column="STATUS".equals(view)?"status":"CATEGORY".equals(view)?"defect_category":"severity";sql="SELECT "+column+" AS dimension,COUNT(*) AS value FROM tm_test_defect WHERE tenant_id=? AND test_domain=? AND project_id=? AND deleted=0"+x+" GROUP BY "+column+" ORDER BY value DESC";}out.put("rows",jdbc.queryForList(sql,u.tenantId(),d,p));out.put("trend",jdbc.queryForList("SELECT DATE(proposed_at) AS dimension,COUNT(*) AS raised_count,SUM(status IN ('RESOLVED','CLOSED')) AS resolved_count FROM tm_test_defect WHERE tenant_id=? AND test_domain=? AND project_id=? AND deleted=0"+x+" GROUP BY DATE(proposed_at) ORDER BY dimension",u.tenantId(),d,p));}
 private void workload(String d,long p,Long sys,Long round,Long cycle,String perspective,Map<String,Object> out,AuthUser u){String x=(sys==null?"":" AND e.physical_subsystem_id="+sys)+(round==null?"":" AND e.round_id="+round)+(cycle==null?"":" AND e.cycle_id="+cycle);if("HANDLER".equalsIgnoreCase(perspective)){out.put("rows",jdbc.queryForList("SELECT COALESCE(u.display_name,'待分派') AS dimension,COUNT(d.id) AS handled_defects,SUM(d.status NOT IN ('RESOLVED','CLOSED')) AS pending_defects FROM tm_test_defect d LEFT JOIN sys_user u ON u.id=d.handler_id AND u.tenant_id=d.tenant_id WHERE d.tenant_id=? AND d.test_domain=? AND d.project_id=? AND d.deleted=0"+x.replace("e.","d.")+" GROUP BY u.display_name ORDER BY handled_defects DESC",u.tenantId(),d,p));}else out.put("rows",jdbc.queryForList("SELECT COALESCE(u.display_name,'未执行') AS dimension,COUNT(e.id) AS execution_total,SUM(e.execution_status='SUCCESS') AS success_count,SUM(e.execution_status='FAILED') AS failed_count,SUM(e.execution_status='RUNNING') AS running_count,SUM(e.execution_status='UNEXECUTED') AS unexecuted_count FROM tm_test_execution e LEFT JOIN sys_user u ON u.id=e.executor_id AND u.tenant_id=e.tenant_id WHERE e.tenant_id=? AND e.test_domain=? AND e.project_id=? AND e.deleted=0"+x+" GROUP BY u.display_name ORDER BY execution_total DESC",u.tenantId(),d,p));}
 private List<Map<String,Object>> options(String d,long p,String code,AuthUser u){return jdbc.queryForList("SELECT o.option_code,o.option_name FROM tm_test_dictionary_option o JOIN tm_test_dictionary x ON x.id=o.dictionary_id AND x.tenant_id=o.tenant_id WHERE x.tenant_id=? AND x.test_domain=? AND x.project_id=? AND x.dictionary_code=? AND x.deleted=0 AND o.deleted=0 AND o.enabled=1 ORDER BY o.sort_no,o.id",u.tenantId(),d,p,code);}private long n(Object v){return v instanceof Number x?x.longValue():0;}private Long num(Object x){try{return x==null||String.valueOf(x).isBlank()?null:Long.valueOf(String.valueOf(x));}catch(Exception e){throw bad("筛选编号无效");}}private String encode(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw bad("统计快照序列化失败");}}private Map<String,Object> map(Object value){try{return value==null?Map.of():json.readValue(String.valueOf(value),new TypeReference<>(){});}catch(Exception e){return Map.of();}}private static long next(){return System.currentTimeMillis()*1000+ThreadLocalRandom.current().nextInt(1000);}private static BusinessException bad(String s){return new BusinessException(ErrorCode.BAD_REQUEST,s);}
}
