package com.ccb.testmanagement.analytics;

import com.ccb.common.exception.BusinessException;
import com.ccb.common.exception.ErrorCode;
import com.ccb.security.model.AuthUser;
import com.ccb.testmanagement.report.TestReportService;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;

/** Analysis orchestration; TestAnalyticsRepository owns all persistence SQL. */
@Service public class TestAnalyticsService {
 public static final List<Map<String,String>> PRESETS=List.of(Map.of("key","SCOPE_COVERAGE","name","范围覆盖率"),Map.of("key","EXECUTION_PROGRESS","name","执行进度与成功率"),Map.of("key","DEFECT_DISTRIBUTION","name","缺陷多维分布"),Map.of("key","PERSONNEL_WORKLOAD","name","人员工作量"));
 private final TestAnalyticsRepository repository;private final ObjectMapper mapper;private final TestReportService reports;
 public TestAnalyticsService(TestAnalyticsRepository repository,ObjectMapper mapper,TestReportService reports){this.repository=repository;this.mapper=mapper;this.reports=reports;}
 public Map<String,Object> tree(String d,long p,AuthUser u){reports.tree(d,p,u);return Map.of("presets",PRESETS,"mine",repository.mine(params(d,p,u)),"shared",repository.shared(params(d,p,u)));}
 public Map<String,Object> analyze(String d,long p,String key,Map<String,Object> filters,AuthUser u){reports.tree(d,p,u);Long system=number(filters.get("physical_subsystem_id"));Long round=number(filters.get("round_id"));Long cycle=number(filters.get("cycle_id"));List<String> sections=List.of("OVERVIEW","SCOPE_STAT","EXECUTION_STAT","DEFECT_STAT");Map<String,Object> summary=reports.snapshot(d,p,system,round,cycle,sections,u);Map<String,Object> out=new LinkedHashMap<>();out.put("report_key",key);out.put("summary",summary);out.put("table",table(d,p,key,system,round,cycle,u));out.put("filters",Map.of("physical_subsystem_id",system==null?"":system,"round_id",round==null?"":round,"cycle_id",cycle==null?"":cycle));out.put("chart",chart(key,out));return out;}
 public List<Map<String,Object>> drilldown(String d,long p,String entity,Map<String,Object> filters,AuthUser u){reports.tree(d,p,u);Map<String,Object> x=params(d,p,u);x.put("systemId",number(filters.get("physical_subsystem_id")));x.put("roundId",number(filters.get("round_id")));x.put("cycleId",number(filters.get("cycle_id")));return switch(entity.toUpperCase(Locale.ROOT)){case "SCOPE"->repository.scopeDrilldown(x);case "CASE"->repository.caseDrilldown(x);case "EXECUTION"->repository.executionDrilldown(x);default->repository.defectDrilldown(x);};}
 @Transactional public Map<String,Object> save(String d,long p,Long id,Map<String,Object> body,AuthUser u){reports.tree(d,p,u);String name=required(body.get("report_name"),"报表名称",50);String key=String.valueOf(body.getOrDefault("report_key","CUSTOM")).trim().toUpperCase(Locale.ROOT);Map<String,Object> config=body.get("config") instanceof Map<?,?> raw?copy(raw):Map.of("dimensions",List.of(),"metrics",List.of(),"charts",List.of("TABLE"));Map<String,Object> x=params(d,p,u);x.put("name",name);x.put("reportKey",key);x.put("configJson",json(config));if(id==null){if(n(repository.namedReportCount(x))>0)throw conflict("个人报表名称已存在");id=next();x.put("id",id);repository.insertReport(x);}else{x.put("id",id);own(id,d,p,u);repository.updateReport(x);}audit(d,p,id,"SAVE",u);return repository.report(Map.of("id",id,"tenantId",u.tenantId()));}
 @Transactional public void publish(String d,long p,long id,boolean shared,AuthUser u){reports.tree(d,p,u);own(id,d,p,u);Map<String,Object>x=params(d,p,u);x.put("id",id);x.put("shared",shared);repository.publishReport(x);audit(d,p,id,shared?"PUBLISH":"UNPUBLISH",u);}
 @Transactional public void delete(String d,long p,long id,AuthUser u){own(id,d,p,u);repository.deleteReport(Map.of("id",id,"tenantId",u.tenantId()));audit(d,p,id,"DELETE",u);}
 @Transactional public List<Map<String,Object>> archive(String d,long p,long round,AuthUser u){reports.tree(d,p,u);Map<String,Object>x=params(d,p,u);x.put("roundId",round);if(n(repository.roundCount(x))==0)throw bad("轮次不存在");List<Map<String,Object>> saved=new ArrayList<>();for(Map<String,String> preset:PRESETS){Map<String,Object> data=analyze(d,p,preset.get("key"),Map.of("round_id",round),u);Map<String,Object> snapshot=params(d,p,u);snapshot.put("id",next());snapshot.put("roundId",round);snapshot.put("reportKey",preset.get("key"));snapshot.put("snapshotJson",json(data));repository.upsertSnapshot(snapshot);saved.add(Map.of("report_key",preset.get("key"),"archived_at",LocalDateTime.now().toString()));}audit(d,p,null,"ARCHIVE",u);return saved;}
 public List<Map<String,Object>> snapshots(String d,long p,Long round,AuthUser u){reports.tree(d,p,u);Map<String,Object>x=params(d,p,u);x.put("roundId",round);return repository.snapshots(x);}
 private List<Map<String,Object>> table(String d,long p,String key,Long sys,Long round,Long cycle,AuthUser u){Map<String,Object>x=params(d,p,u);x.put("systemId",sys);x.put("roundId",round);x.put("cycleId",cycle);if("DEFECT_DISTRIBUTION".equals(key))return repository.defectDistribution(x);if("PERSONNEL_WORKLOAD".equals(key))return repository.personnelWorkload(x);return repository.executionProgress(x);}
 private Map<String,Object> chart(String key,Map<String,Object> data){return Map.of("type","DEFECT_DISTRIBUTION".equals(key)?"PIE":"BAR","title",PRESETS.stream().filter(x->x.get("key").equals(key)).findFirst().map(x->x.get("name")).orElse("自定义统计"),"rows",data.get("table"));}
 private void own(long id,String d,long p,AuthUser u){Map<String,Object>x=params(d,p,u);x.put("id",id);if(n(repository.ownedReportCount(x))==0)throw bad("报表不存在或无修改权限");}
 private void audit(String d,long p,Long id,String action,AuthUser u){Map<String,Object>x=params(d,p,u);x.put("id",next());x.put("reportId",id);x.put("action",action);repository.insertTrace(x);}
 private static Map<String,Object> params(String d,long p,AuthUser u){Map<String,Object>x=new HashMap<>();x.put("tenantId",u.tenantId());x.put("domain",d);x.put("projectId",p);x.put("userId",u.id());return x;}private String json(Object o){try{return mapper.writeValueAsString(o);}catch(Exception e){throw bad("配置保存失败");}}private Map<String,Object> copy(Map<?,?> input){Map<String,Object> out=new LinkedHashMap<>();input.forEach((k,v)->out.put(String.valueOf(k),v));return out;}private static long n(Long v){return v==null?0:v;}private static Long number(Object v){try{return v==null||String.valueOf(v).isBlank()?null:Long.parseLong(String.valueOf(v));}catch(Exception e){throw bad("编号无效");}}private static String required(Object v,String n,int max){String s=v==null?"":String.valueOf(v).trim();if(s.isBlank()||s.length()>max)throw bad(n+"无效");return s;}private static long next(){return System.currentTimeMillis()*1000+ThreadLocalRandom.current().nextInt(1000);}private static BusinessException bad(String s){return new BusinessException(ErrorCode.BAD_REQUEST,s);}private static BusinessException conflict(String s){return new BusinessException(ErrorCode.CONFLICT,s);}
}
