/*
 * 文件：server/src/modules/test-management/src/main/java/com/ccb/testmanagement/analytics/TestAnalyticsService.java
 * 说明：分析统计的服务、策略或接口实现。
 * 用途：承载模块边界内的查询、校验、事务、权限或文件处理职责。
 * 作者：hengguan
 */
package com.ccb.testmanagement.analytics;

// 关键逻辑：所有读写以认证用户的租户、测试大类和项目为共同边界；写入由事务与审计保持一致性。

import com.ccb.common.exception.BusinessException;
import com.ccb.common.exception.ErrorCode;
import com.ccb.security.model.AuthUser;
import com.ccb.testmanagement.report.TestReportService;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;

/** 分析统计：预置报表直接聚合当前业务数据，自定义报表保存设计而不复制原始数据。 */
@Service public class TestAnalyticsService {
 public static final List<Map<String,String>> PRESETS=List.of(Map.of("key","SCOPE_COVERAGE","name","范围覆盖率"),Map.of("key","EXECUTION_PROGRESS","name","执行进度与成功率"),Map.of("key","DEFECT_DISTRIBUTION","name","缺陷多维分布"),Map.of("key","PERSONNEL_WORKLOAD","name","人员工作量"));
 private static final Set<String> DOMAINS=Set.of("application-assembly","user-testing","non-functional","security");private final JdbcTemplate jdbc;private final ObjectMapper mapper;private final TestReportService reports;
 public TestAnalyticsService(JdbcTemplate jdbc,ObjectMapper mapper,TestReportService reports){this.jdbc=jdbc;this.mapper=mapper;this.reports=reports;}
 public Map<String,Object> tree(String d,long p,AuthUser u){reports.tree(d,p,u);List<Map<String,Object>> mine=jdbc.queryForList("SELECT id,report_name,report_key,shared,config_json,updated_at FROM tm_test_analytics_report WHERE tenant_id=? AND test_domain=? AND project_id=? AND owner_id=? ORDER BY updated_at DESC",u.tenantId(),d,p,u.id());List<Map<String,Object>> shared=jdbc.queryForList("SELECT id,report_name,report_key,shared,config_json,updated_at,(SELECT display_name FROM sys_user u WHERE u.id=r.owner_id AND u.tenant_id=r.tenant_id AND u.deleted=0) AS owner_name FROM tm_test_analytics_report r WHERE tenant_id=? AND test_domain=? AND project_id=? AND shared=1 ORDER BY updated_at DESC",u.tenantId(),d,p);return Map.of("presets",PRESETS,"mine",mine,"shared",shared);}
 public Map<String,Object> analyze(String d,long p,String key,Map<String,Object> filters,AuthUser u){reports.tree(d,p,u);Long system=number(filters.get("physical_subsystem_id"));Long round=number(filters.get("round_id"));Long cycle=number(filters.get("cycle_id"));List<String> sections=List.of("OVERVIEW","SCOPE_STAT","EXECUTION_STAT","DEFECT_STAT");Map<String,Object> summary=reports.snapshot(d,p,system,round,cycle,sections,u);Map<String,Object> out=new LinkedHashMap<>();out.put("report_key",key);out.put("summary",summary);out.put("table",table(d,p,key,system,round,cycle,u));out.put("filters",Map.of("physical_subsystem_id",system==null?"":system,"round_id",round==null?"":round,"cycle_id",cycle==null?"":cycle));out.put("chart",chart(key,out));return out;}
 public List<Map<String,Object>> drilldown(String d,long p,String entity,Map<String,Object> filters,AuthUser u){reports.tree(d,p,u);Long sys=number(filters.get("physical_subsystem_id"));Long round=number(filters.get("round_id"));Long cycle=number(filters.get("cycle_id"));String base=" tenant_id=? AND test_domain=? AND project_id=? AND deleted=0"+(sys==null?"":" AND physical_subsystem_id=?");Object[] a=sys==null?new Object[]{u.tenantId(),d,p}:new Object[]{u.tenantId(),d,p,sys};String executionBase=base.replace("tenant_id","e.tenant_id").replace("test_domain","e.test_domain").replace("project_id","e.project_id").replace("deleted","e.deleted")+(round==null?"":" AND e.round_id="+round)+(cycle==null?"":" AND e.cycle_id="+cycle);String defectBase=base+(round==null?"":" AND round_id="+round)+(cycle==null?"":" AND cycle_id="+cycle);return switch(entity.toUpperCase(Locale.ROOT)){case "SCOPE"->jdbc.queryForList("SELECT scope_code,scope_name,function_type,importance,invalidated,created_at FROM tm_test_scope WHERE"+base+" ORDER BY scope_code LIMIT 1000",a);case "CASE"->jdbc.queryForList("SELECT case_code,case_name,case_type,priority,invalidated,created_at FROM tm_test_case WHERE"+base+" ORDER BY case_code LIMIT 1000",a);case "EXECUTION"->jdbc.queryForList("SELECT e.id,c.case_code,c.case_name,e.execution_status,e.executed_at FROM tm_test_execution e JOIN tm_test_case c ON c.id=e.case_id WHERE"+executionBase+" ORDER BY e.updated_at DESC LIMIT 1000",a);default->jdbc.queryForList("SELECT defect_code,summary,defect_category,severity,priority,urgency,status,proposed_at FROM tm_test_defect WHERE"+defectBase+" ORDER BY proposed_at DESC LIMIT 1000",a);};}
 @Transactional public Map<String,Object> save(String d,long p,Long id,Map<String,Object> body,AuthUser u){reports.tree(d,p,u);String name=required(body.get("report_name"),"报表名称",50);String key=String.valueOf(body.getOrDefault("report_key","CUSTOM")).trim().toUpperCase(Locale.ROOT);Map<String,Object> config=body.get("config") instanceof Map<?,?> raw?copy(raw):Map.of("dimensions",List.of(),"metrics",List.of(),"charts",List.of("TABLE"));if(id==null){Long exists=jdbc.queryForObject("SELECT COUNT(*) FROM tm_test_analytics_report WHERE tenant_id=? AND test_domain=? AND project_id=? AND owner_id=? AND report_name=?",Long.class,u.tenantId(),d,p,u.id(),name);if(exists!=null&&exists>0)throw conflict("个人报表名称已存在");id=next();jdbc.update("INSERT INTO tm_test_analytics_report(id,tenant_id,test_domain,project_id,report_name,report_key,owner_id,shared,config_json) VALUES(?,?,?,?,?,?,?,?,?)",id,u.tenantId(),d,p,name,key,u.id(),false,json(config));}else{own(id,d,p,u);jdbc.update("UPDATE tm_test_analytics_report SET report_name=?,report_key=?,config_json=? WHERE id=? AND tenant_id=?",name,key,json(config),id,u.tenantId());}audit(d,p,id,"SAVE",u);return jdbc.queryForMap("SELECT id,report_name,report_key,shared,config_json,updated_at FROM tm_test_analytics_report WHERE id=? AND tenant_id=?",id,u.tenantId());}
 @Transactional public void publish(String d,long p,long id,boolean shared,AuthUser u){reports.tree(d,p,u);own(id,d,p,u);jdbc.update("UPDATE tm_test_analytics_report SET shared=?,published_by=? WHERE id=? AND tenant_id=?",shared,u.id(),id,u.tenantId());audit(d,p,id,shared?"PUBLISH":"UNPUBLISH",u);}
 @Transactional public void delete(String d,long p,long id,AuthUser u){own(id,d,p,u);jdbc.update("DELETE FROM tm_test_analytics_report WHERE id=? AND tenant_id=?",id,u.tenantId());audit(d,p,id,"DELETE",u);}
 @Transactional public List<Map<String,Object>> archive(String d,long p,long round,AuthUser u){reports.tree(d,p,u);Long exists=jdbc.queryForObject("SELECT COUNT(*) FROM tm_test_round WHERE id=? AND tenant_id=? AND test_domain=? AND project_id=? AND deleted=0",Long.class,round,u.tenantId(),d,p);if(exists==null||exists==0)throw bad("轮次不存在");List<Map<String,Object>> saved=new ArrayList<>();for(Map<String,String> preset:PRESETS){Map<String,Object> data=analyze(d,p,preset.get("key"),Map.of("round_id",round),u);long id=next();jdbc.update("INSERT INTO tm_test_analytics_snapshot(id,tenant_id,test_domain,project_id,round_id,report_key,snapshot_json,archived_by) VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE snapshot_json=VALUES(snapshot_json),archived_by=VALUES(archived_by),archived_at=CURRENT_TIMESTAMP",id,u.tenantId(),d,p,round,preset.get("key"),json(data),u.id());saved.add(Map.of("report_key",preset.get("key"),"archived_at",LocalDateTime.now().toString()));}audit(d,p,null,"ARCHIVE",u);return saved;}
 public List<Map<String,Object>> snapshots(String d,long p,Long round,AuthUser u){reports.tree(d,p,u);return jdbc.queryForList("SELECT id,round_id,report_key,archived_at,(SELECT display_name FROM sys_user u WHERE u.id=s.archived_by AND u.tenant_id=s.tenant_id AND u.deleted=0) AS archiver_name FROM tm_test_analytics_snapshot s WHERE tenant_id=? AND test_domain=? AND project_id=?"+(round==null?"":" AND round_id=?")+" ORDER BY archived_at DESC",round==null?new Object[]{u.tenantId(),d,p}:new Object[]{u.tenantId(),d,p,round});}
 private List<Map<String,Object>> table(String d,long p,String key,Long sys,Long round,Long cycle,AuthUser u){String systems=" s.tenant_id=? AND s.test_domain=? AND s.project_id=? AND s.enabled=1 AND s.deleted=0"+(sys==null?"":" AND s.physical_subsystem_id=?");Object[] a=sys==null?new Object[]{u.tenantId(),d,p}:new Object[]{u.tenantId(),d,p,sys};if("DEFECT_DISTRIBUTION".equals(key))return jdbc.queryForList("SELECT defect_category AS dimension,COUNT(*) AS value FROM tm_test_defect WHERE tenant_id=? AND test_domain=? AND project_id=? AND deleted=0"+(sys==null?"":" AND physical_subsystem_id=?")+" GROUP BY defect_category ORDER BY value DESC",a);if("PERSONNEL_WORKLOAD".equals(key))return jdbc.queryForList("SELECT COALESCE(u.display_name,'未分配') AS dimension,COUNT(*) AS value FROM tm_test_defect d LEFT JOIN sys_user u ON u.id=d.handler_id AND u.tenant_id=d.tenant_id WHERE d.tenant_id=? AND d.test_domain=? AND d.project_id=? AND d.deleted=0"+(sys==null?"":" AND d.physical_subsystem_id=?")+" GROUP BY u.display_name ORDER BY value DESC",a);String execFilter=" e.tenant_id=? AND e.test_domain=? AND e.project_id=? AND e.deleted=0"+(sys==null?"":" AND e.physical_subsystem_id=?")+(round==null?"":" AND e.round_id="+round)+(cycle==null?"":" AND e.cycle_id="+cycle);return jdbc.queryForList("SELECT COALESCE(NULLIF(p.short_name,''),REPLACE(p.name,'物理子系统','')) AS dimension,COUNT(e.id) AS execution_total,SUM(e.execution_status='SUCCESS') AS success_count,SUM(e.execution_status='FAILED') AS failed_count,SUM(e.execution_status='BLOCKED') AS blocked_count FROM tm_test_participating_system s JOIN arch_physical_subsystem p ON p.id=s.physical_subsystem_id LEFT JOIN tm_test_execution e ON e.physical_subsystem_id=s.physical_subsystem_id AND "+execFilter+" WHERE"+systems+" GROUP BY s.physical_subsystem_id,p.name,p.short_name ORDER BY dimension",concat(a,a));}
 private Map<String,Object> chart(String key,Map<String,Object> data){return Map.of("type","DEFECT_DISTRIBUTION".equals(key)?"PIE":"BAR","title",PRESETS.stream().filter(x->x.get("key").equals(key)).findFirst().map(x->x.get("name")).orElse("自定义统计"),"rows",data.get("table"));}private void own(long id,String d,long p,AuthUser u){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM tm_test_analytics_report WHERE id=? AND tenant_id=? AND test_domain=? AND project_id=? AND owner_id=?",Long.class,id,u.tenantId(),d,p,u.id());if(n==null||n==0)throw bad("报表不存在或无修改权限");}private void audit(String d,long p,Long id,String a,AuthUser u){jdbc.update("INSERT INTO tm_test_analytics_trace(id,tenant_id,test_domain,project_id,analytics_report_id,action_code,operator_id,detail_json) VALUES(?,?,?,?,?,?,?,?)",next(),u.tenantId(),d,p,id,a,u.id(),"{}");}private String json(Object o){try{return mapper.writeValueAsString(o);}catch(Exception e){throw bad("配置保存失败");}}private Map<String,Object> copy(Map<?,?> input){Map<String,Object> out=new LinkedHashMap<>();input.forEach((k,v)->out.put(String.valueOf(k),v));return out;}private Object[] concat(Object[] x,Object[] y){Object[] all=Arrays.copyOf(x,x.length+y.length);System.arraycopy(y,0,all,x.length,y.length);return all;}private static Long number(Object v){try{return v==null||String.valueOf(v).isBlank()?null:Long.parseLong(String.valueOf(v));}catch(Exception e){throw bad("编号无效");}}private static String required(Object v,String n,int max){String s=v==null?"":String.valueOf(v).trim();if(s.isBlank()||s.length()>max)throw bad(n+"无效");return s;}private static long next(){return System.currentTimeMillis()*1000+ThreadLocalRandom.current().nextInt(1000);}private static BusinessException bad(String s){return new BusinessException(ErrorCode.BAD_REQUEST,s);}private static BusinessException conflict(String s){return new BusinessException(ErrorCode.CONFLICT,s);}
}
