package com.ccb.testmanagement.analytics;

import com.ccb.common.exception.BusinessException;
import com.ccb.common.exception.ErrorCode;
import com.ccb.security.model.AuthUser;
import com.ccb.testmanagement.report.TestReportService;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;
import java.util.stream.Stream;

/** 固定统计的唯一入口：每个 RPT/CHT 编号都有明确事实查询，不得退化为概览占位数据。 */
@Service public class TestAnalyticsAdvancedService {
 private final JdbcTemplate jdbc; private final ObjectMapper json; private final TestReportService reports;
 public TestAnalyticsAdvancedService(JdbcTemplate jdbc,ObjectMapper json,TestReportService reports){this.jdbc=jdbc;this.json=json;this.reports=reports;}
 public Map<String,Object> filters(String d,long p,AuthUser u){Map<String,Object> root=reports.tree(d,p,u);return Map.of("systems",root.get("systems"),"institutions",root.get("institutions"),"rounds",jdbc.queryForList("SELECT id,round_name,planned_start_date,planned_end_date,status FROM tm_test_round WHERE tenant_id=? AND test_domain=? AND project_id=? AND deleted=0 ORDER BY sort_no,id",u.tenantId(),d,p),"cycles",jdbc.queryForList("SELECT c.id,c.round_id,c.cycle_name,c.planned_start_date,c.planned_end_date,c.status FROM tm_test_cycle c JOIN tm_test_round r ON r.id=c.round_id AND r.tenant_id=c.tenant_id WHERE c.tenant_id=? AND r.test_domain=? AND r.project_id=? AND c.deleted=0 AND r.deleted=0 ORDER BY c.sort_no,c.id",u.tenantId(),d,p),"case_types",options(d,p,"case_type",u),"priorities",options(d,p,"priority",u),"severities",options(d,p,"severity",u));}
 public Map<String,Object> preset(String d,long p,String raw,Map<String,Object> f,AuthUser u){reports.tree(d,p,u);String key=raw.toUpperCase(Locale.ROOT);Map<String,String> definition=fixed().stream().filter(x->x.get("code").equals(key)).findFirst().orElseThrow(()->bad("固定报表或图表编号不存在"));Long sys=num(f.get("physical_subsystem_id")),round=num(f.get("round_id")),cycle=num(f.get("cycle_id"));Map<String,Object> out=new LinkedHashMap<>();out.put("key",key);out.put("name",definition.get("name"));out.put("filters",Map.of("physical_subsystem_id",sys==null?"":sys,"round_id",round==null?"":round,"cycle_id",cycle==null?"":cycle));out.put("summary",reports.snapshot(d,p,sys,round,cycle,TestReportService.CHAPTERS,u));populate(out,d,p,key,sys,round,cycle,u);localize(out);return out;}
 private void populate(Map<String,Object> out,String d,long p,String key,Long sys,Long round,Long cycle,AuthUser u){switch(key){
  case "RPT-001"->execution(out,d,p,sys,round,cycle,"系统",u); case "RPT-002"->execution(out,d,p,sys,round,null,"周期",u); case "RPT-003","RPT-018"->execution(out,d,p,sys,null,null,"轮次",u);
  case "RPT-004"->execution(out,d,p,sys,round,null,"机构+周期",u); case "RPT-005"->execution(out,d,p,sys,null,null,"机构+轮次",u); case "RPT-006"->caseDetails(out,d,p,sys,round,cycle,u); case "RPT-007"->defectDetails(out,d,p,sys,round,cycle,u);
  case "RPT-008","CHT-002"->defectGroup(out,d,p,sys,round,cycle,"status",u); case "RPT-009","CHT-003"->defectGroup(out,d,p,sys,round,cycle,"severity",u); case "RPT-010","RPT-019","CHT-005","CHT-012"->systemQuality(out,d,p,sys,round,cycle,u);
  case "RPT-011","CHT-006"->coverage(out,d,p,sys,u); case "RPT-012","CHT-009"->workload(out,d,p,sys,round,cycle,u); case "RPT-013","RPT-026"->lifecycle(out,d,p,sys,round,cycle,u); case "RPT-014","CHT-011"->execution(out,d,p,sys,round,cycle,"案例类型",u);
  case "RPT-015"->execution(out,d,p,sys,round,cycle,"优先级",u); case "RPT-016"->execution(out,d,p,sys,round,cycle,"核算相关",u); case "RPT-017"->efficiency(out,d,p,sys,round,cycle,u); case "RPT-020","RPT-023","RPT-025","CHT-004","CHT-013"->execution(out,d,p,sys,round,cycle,"日期",u);
  case "RPT-021"->execution(out,d,p,sys,round,cycle,"周",u); case "RPT-022"->execution(out,d,p,sys,round,cycle,"月",u); case "RPT-024"->execution(out,d,p,sys,round,cycle,"机构",u); case "CHT-001"->states(out,d,p,sys,round,cycle,u); case "CHT-007"->executionStateMatrix(out,d,p,sys,round,null,"系统",u); case "CHT-008"->severityStatus(out,d,p,sys,round,cycle,u); case "CHT-010","CHT-014"->defectTrend(out,d,p,sys,round,cycle,u); case "CHT-015"->executionHeatmap(out,d,p,sys,round,cycle,u); case "CHT-016"->executionStateMatrix(out,d,p,sys,null,null,"轮次",u); default->throw bad("固定统计编号尚未登记");}out.put("chart_type",chart(key));}
 /** 每个案例取筛选范围内最新一条执行记录，执行中不会进入已执行数。 */
 private void execution(Map<String,Object> out,String d,long p,Long sys,Long round,Long cycle,String group,AuthUser u){String dim=switch(group){case "系统"->"COALESCE(NULLIF(ps.short_name,''),REPLACE(ps.name,'物理子系统',''))";case "机构"->"COALESCE(NULLIF(ps.responsible_team_name_snapshot,''),'未设置责任团队')";case "周期"->"COALESCE(cy.cycle_name,'未归属周期')";case "轮次"->"COALESCE(ro.round_name,'未归属轮次')";case "日期"->"COALESCE(DATE_FORMAT(le.executed_at,'%Y-%m-%d'),'未执行')";case "周"->"COALESCE(DATE_FORMAT(le.executed_at,'%x-第%v周'),'未执行')";case "月"->"COALESCE(DATE_FORMAT(le.executed_at,'%Y-%m'),'未执行')";case "案例类型"->"COALESCE(NULLIF(tc.case_type,''),'未分类')";case "优先级"->"COALESCE(NULLIF(tc.priority,''),'未设置')";case "核算相关"->"CASE WHEN tc.case_name LIKE '%核算%' OR tc.case_name LIKE '%账务%' THEN '核算相关' ELSE '非核算相关' END";case "系统+周期"->"CONCAT(COALESCE(NULLIF(ps.short_name,''),REPLACE(ps.name,'物理子系统','')),' / ',COALESCE(cy.cycle_name,'未归属周期'))";case "机构+周期"->"CONCAT(COALESCE(NULLIF(ps.responsible_team_name_snapshot,''),'未设置责任团队'),' / ',COALESCE(cy.cycle_name,'未归属周期'))";case "机构+轮次"->"CONCAT(COALESCE(NULLIF(ps.responsible_team_name_snapshot,''),'未设置责任团队'),' / ',COALESCE(ro.round_name,'未归属轮次'))";default->"'项目汇总'";};String lf="e.tenant_id=? AND e.test_domain=? AND e.project_id=? AND e.deleted=0"+(sys==null?"":" AND e.physical_subsystem_id=?")+(round==null?"":" AND e.round_id="+round)+(cycle==null?"":" AND e.cycle_id="+cycle);Object[] a=args(d,p,sys,u);Object[] both=concat(a,a);String cf="tc.tenant_id=? AND tc.test_domain=? AND tc.project_id=? AND tc.deleted=0 AND tc.invalidated=0"+(sys==null?"":" AND tc.physical_subsystem_id=?");String sql="SELECT "+dim+" AS dimension,COUNT(tc.id) AS effective_case_total,SUM(le.execution_status IN ('SUCCESS','FAILED','BLOCKED')) AS execution_total,SUM(le.execution_status='SUCCESS') AS success_count,SUM(le.execution_status='FAILED') AS failed_count,SUM(le.execution_status='BLOCKED') AS blocked_count,SUM(le.execution_status IN ('IN_PROGRESS','RUNNING')) AS in_progress_count,SUM(le.id IS NULL OR le.execution_status='UNEXECUTED') AS unexecuted_count FROM tm_test_case tc JOIN arch_physical_subsystem ps ON ps.id=tc.physical_subsystem_id LEFT JOIN (SELECT e.* FROM tm_test_execution e JOIN (SELECT case_id,MAX(id) id FROM tm_test_execution e WHERE "+lf+" GROUP BY case_id) x ON x.id=e.id) le ON le.case_id=tc.id LEFT JOIN tm_test_cycle cy ON cy.id=le.cycle_id LEFT JOIN tm_test_round ro ON ro.id=le.round_id WHERE "+cf+" GROUP BY dimension ORDER BY dimension";List<Map<String,Object>> rows=jdbc.queryForList(sql,both);for(Map<String,Object> row:rows)rates(row);out.put("rows",rows);out.put("trend",rows);}
 private void caseDetails(Map<String,Object> out,String d,long p,Long sys,Long round,Long cycle,AuthUser u){out.put("rows",jdbc.queryForList("SELECT tc.case_code,tc.case_name,tc.case_type,tc.priority,COALESCE(e.execution_status,'UNEXECUTED') execution_status,e.executed_at,r.round_name,c.cycle_name FROM tm_test_case tc LEFT JOIN tm_test_execution e ON e.id=(SELECT MAX(x.id) FROM tm_test_execution x WHERE x.case_id=tc.id AND x.tenant_id=tc.tenant_id AND x.deleted=0"+range("x",round,cycle)+") LEFT JOIN tm_test_round r ON r.id=e.round_id LEFT JOIN tm_test_cycle c ON c.id=e.cycle_id WHERE "+base("tc",d,p,sys,true),args(d,p,sys,u)));out.put("trend",List.of());}
 private void defectDetails(Map<String,Object> out,String d,long p,Long sys,Long round,Long cycle,AuthUser u){out.put("rows",jdbc.queryForList("SELECT defect_code,summary,defect_category,severity,priority,urgency,status,proposed_at,CASE WHEN status IN ('RESOLVED','CLOSED') THEN updated_at END resolved_at,(SELECT display_name FROM sys_user x WHERE x.id=d.handler_id AND x.tenant_id=d.tenant_id) handler_name FROM tm_test_defect d WHERE "+base("d",d,p,sys,false)+range("d",round,cycle)+" ORDER BY proposed_at DESC",args(d,p,sys,u)));out.put("trend",List.of());}
 private void defectGroup(Map<String,Object> out,String d,long p,Long sys,Long round,Long cycle,String field,AuthUser u){List<Map<String,Object>> rows=jdbc.queryForList("SELECT "+field+" dimension,COUNT(*) value FROM tm_test_defect d WHERE "+base("d",d,p,sys,false)+range("d",round,cycle)+" GROUP BY "+field+" ORDER BY value DESC",args(d,p,sys,u));out.put("rows",rows);out.put("trend",rows);}
 private void coverage(Map<String,Object> out,String d,long p,Long sys,AuthUser u){List<Map<String,Object>> rows=jdbc.queryForList("SELECT COALESCE(NULLIF(ps.short_name,''),REPLACE(ps.name,'物理子系统','')) dimension,COUNT(sc.id) scope_total,SUM(EXISTS(SELECT 1 FROM tm_test_case tc WHERE tc.scope_id=sc.id AND tc.tenant_id=sc.tenant_id AND tc.deleted=0 AND tc.invalidated=0)) covered_total FROM tm_test_scope sc JOIN arch_physical_subsystem ps ON ps.id=sc.physical_subsystem_id WHERE "+base("sc",d,p,sys,true)+" GROUP BY dimension",args(d,p,sys,u));for(Map<String,Object> x:rows){long total=n(x.get("scope_total"));x.put("uncovered_total",total-n(x.get("covered_total")));x.put("coverage_rate",rate(n(x.get("covered_total")),total));}out.put("rows",rows);out.put("trend",rows);}
 private void workload(Map<String,Object> out,String d,long p,Long sys,Long round,Long cycle,AuthUser u){List<Map<String,Object>> rows=jdbc.queryForList("SELECT COALESCE(x.display_name,'未分派') dimension,COUNT(e.id) execution_total,SUM(e.execution_status='SUCCESS') success_count,SUM(e.execution_status='FAILED') failed_count,SUM(e.execution_status IN ('IN_PROGRESS','RUNNING')) in_progress_count FROM tm_test_execution e LEFT JOIN sys_user x ON x.id=e.executor_id AND x.tenant_id=e.tenant_id WHERE "+base("e",d,p,sys,false)+range("e",round,cycle)+" GROUP BY x.display_name",args(d,p,sys,u));out.put("rows",rows);out.put("trend",rows);}
 private void systemQuality(Map<String,Object> out,String d,long p,Long sys,Long round,Long cycle,AuthUser u){execution(out,d,p,sys,round,cycle,"系统",u);for(Map<String,Object> row:rows(out)){long cases=n(row.get("effective_case_total"));Long defects=jdbc.queryForObject("SELECT COUNT(*) FROM tm_test_defect x JOIN arch_physical_subsystem ps ON ps.id=x.physical_subsystem_id WHERE x.tenant_id=? AND x.test_domain=? AND x.project_id=? AND x.deleted=0 AND COALESCE(NULLIF(ps.short_name,''),REPLACE(ps.name,'物理子系统',''))=?"+range("x",round,cycle),Long.class,u.tenantId(),d,p,String.valueOf(row.get("dimension")));row.put("defect_total",defects==null?0:defects);row.put("defect_density",rate(defects==null?0:defects,cases));}}
 private void states(Map<String,Object> out,String d,long p,Long sys,Long round,Long cycle,AuthUser u){execution(out,d,p,sys,round,cycle,"项目",u);Map<String,Object> s=rows(out).isEmpty()?Map.of():rows(out).get(0);List<Map<String,Object>> r=List.of(row("未执行",s.get("unexecuted_count")),row("执行中",s.get("in_progress_count")),row("成功",s.get("success_count")),row("失败",s.get("failed_count")),row("阻塞",s.get("blocked_count")));out.put("rows",r);out.put("trend",r);}
 /** 二维状态矩阵保留行、列语义，供堆叠图和交叉统计表共同使用。 */
 private void executionStateMatrix(Map<String,Object> out,String d,long p,Long sys,Long round,Long cycle,String group,AuthUser u){boolean byCycle="系统".equals(group);String dimension=byCycle?"CONCAT(COALESCE(NULLIF(ps.short_name,''),REPLACE(ps.name,'物理子系统','')),' / ',COALESCE(cy.cycle_name,'未归属周期'))":"COALESCE(ro.round_name,'未归属轮次')";String lf="e.tenant_id=? AND e.test_domain=? AND e.project_id=? AND e.deleted=0"+(sys==null?"":" AND e.physical_subsystem_id=?")+(round==null?"":" AND e.round_id="+round)+(cycle==null?"":" AND e.cycle_id="+cycle);Object[] a=args(d,p,sys,u);String cf="tc.tenant_id=? AND tc.test_domain=? AND tc.project_id=? AND tc.deleted=0 AND tc.invalidated=0"+(sys==null?"":" AND tc.physical_subsystem_id=?");String latestGroup=byCycle?"case_id,cycle_id":"case_id,round_id";String sql="SELECT "+dimension+" row_dimension,COALESCE(NULLIF(le.execution_status,''),'UNEXECUTED') column_dimension,COUNT(tc.id) value FROM tm_test_case tc JOIN arch_physical_subsystem ps ON ps.id=tc.physical_subsystem_id LEFT JOIN (SELECT e.* FROM tm_test_execution e JOIN (SELECT "+latestGroup+",MAX(id) id FROM tm_test_execution e WHERE "+lf+" GROUP BY "+latestGroup+") latest ON latest.id=e.id) le ON le.case_id=tc.id LEFT JOIN tm_test_round ro ON ro.id=le.round_id LEFT JOIN tm_test_cycle cy ON cy.id=le.cycle_id WHERE "+cf+" GROUP BY row_dimension,column_dimension ORDER BY row_dimension,column_dimension";List<Map<String,Object>> result=jdbc.queryForList(sql,concat(a,a));out.put("rows",result);out.put("trend",result);}
 /** 横轴为执行日期、纵轴为参测系统；不把未执行案例伪造为日期数据。 */
 private void executionHeatmap(Map<String,Object> out,String d,long p,Long sys,Long round,Long cycle,AuthUser u){String sql="SELECT COALESCE(NULLIF(ps.short_name,''),REPLACE(ps.name,'物理子系统','')) row_dimension,DATE_FORMAT(e.executed_at,'%Y-%m-%d') column_dimension,COUNT(e.id) value FROM tm_test_execution e JOIN arch_physical_subsystem ps ON ps.id=e.physical_subsystem_id JOIN tm_test_case tc ON tc.id=e.case_id AND tc.tenant_id=e.tenant_id AND tc.deleted=0 AND tc.invalidated=0 WHERE "+base("e",d,p,sys,false)+range("e",round,cycle)+" AND e.executed_at IS NOT NULL GROUP BY row_dimension,column_dimension ORDER BY row_dimension,column_dimension";List<Map<String,Object>> result=jdbc.queryForList(sql,args(d,p,sys,u));out.put("rows",result);out.put("trend",result);}
 private void severityStatus(Map<String,Object> out,String d,long p,Long sys,Long round,Long cycle,AuthUser u){List<Map<String,Object>> r=jdbc.queryForList("SELECT severity row_dimension,status column_dimension,COUNT(*) value FROM tm_test_defect d WHERE "+base("d",d,p,sys,false)+range("d",round,cycle)+" GROUP BY severity,status",args(d,p,sys,u));out.put("rows",r);out.put("trend",r);}
 private void defectTrend(Map<String,Object> out,String d,long p,Long sys,Long round,Long cycle,AuthUser u){String where=base("d",d,p,sys,false)+range("d",round,cycle);String sql="SELECT dimension,SUM(raised_count) raised_count,SUM(resolved_count) resolved_count FROM (SELECT DATE_FORMAT(d.proposed_at,'%Y-%m-%d') dimension,COUNT(*) raised_count,0 resolved_count FROM tm_test_defect d WHERE "+where+" GROUP BY DATE_FORMAT(d.proposed_at,'%Y-%m-%d') UNION ALL SELECT DATE_FORMAT(d.updated_at,'%Y-%m-%d') dimension,0 raised_count,COUNT(*) resolved_count FROM tm_test_defect d WHERE "+where+" AND d.status IN ('RESOLVED','CLOSED') GROUP BY DATE_FORMAT(d.updated_at,'%Y-%m-%d')) trend GROUP BY dimension ORDER BY dimension";Object[] a=args(d,p,sys,u);List<Map<String,Object>> r=jdbc.queryForList(sql,concat(a,a));out.put("rows",r);out.put("trend",r);}
 private void lifecycle(Map<String,Object> out,String d,long p,Long sys,Long round,Long cycle,AuthUser u){List<Map<String,Object>> r=jdbc.queryForList("SELECT status dimension,COUNT(*) defect_total,SUM(status IN ('RESOLVED','CLOSED')) closed_total,ROUND(AVG(DATEDIFF(CASE WHEN status IN ('RESOLVED','CLOSED') THEN updated_at ELSE CURRENT_TIMESTAMP END,proposed_at)),2) average_days FROM tm_test_defect d WHERE "+base("d",d,p,sys,false)+range("d",round,cycle)+" GROUP BY status",args(d,p,sys,u));out.put("rows",r);out.put("trend",r);}
 private void efficiency(Map<String,Object> out,String d,long p,Long sys,Long round,Long cycle,AuthUser u){List<Map<String,Object>> r=jdbc.queryForList("SELECT COALESCE(x.display_name,'未分派') dimension,COUNT(d.id) defect_total,SUM(d.status IN ('RESOLVED','CLOSED')) closed_total,ROUND(AVG(DATEDIFF(CASE WHEN d.status IN ('RESOLVED','CLOSED') THEN d.updated_at ELSE CURRENT_TIMESTAMP END,d.proposed_at)),2) average_close_days FROM tm_test_defect d LEFT JOIN sys_user x ON x.id=d.handler_id AND x.tenant_id=d.tenant_id WHERE "+base("d",d,p,sys,false)+range("d",round,cycle)+" GROUP BY x.display_name",args(d,p,sys,u));out.put("rows",r);out.put("trend",r);}
 @Transactional public List<Map<String,Object>> archive(String d,long p,long round,AuthUser u){reports.tree(d,p,u);List<Map<String,Object>> out=new ArrayList<>();for(Map<String,String> item:fixed()){Map<String,Object> data=preset(d,p,item.get("code"),Map.of("round_id",round),u);long id=next();jdbc.update("INSERT INTO tm_test_analytics_snapshot(id,tenant_id,test_domain,project_id,round_id,report_key,snapshot_json,archived_by) VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE snapshot_json=VALUES(snapshot_json),archived_by=VALUES(archived_by),archived_at=CURRENT_TIMESTAMP",id,u.tenantId(),d,p,round,item.get("code"),encode(data),u.id());out.add(Map.of("report_key",item.get("code"),"report_name",item.get("name"),"archived_at",LocalDateTime.now().toString()));}return out;}
 public List<Map<String,Object>> compare(String d,long p,List<Long> rounds,AuthUser u){reports.tree(d,p,u);if(rounds==null||rounds.size()<2)throw bad("请选择至少两个已归档轮次");List<Map<String,Object>> out=new ArrayList<>();for(Long r:rounds){Map<String,Object> row=new LinkedHashMap<>();row.put("round_id",r);row.put("round_name",jdbc.queryForObject("SELECT round_name FROM tm_test_round WHERE id=? AND tenant_id=?",String.class,r,u.tenantId()));row.putAll((Map<String,Object>)preset(d,p,"RPT-001",Map.of("round_id",r),u).get("summary"));out.add(row);}return out;}
 private static String base(String a,String d,long p,Long s,boolean invalid){return a+".tenant_id=? AND "+a+".test_domain=? AND "+a+".project_id=? AND "+a+".deleted=0"+(invalid?" AND "+a+".invalidated=0":"")+(s==null?"":" AND "+a+".physical_subsystem_id=?");}private static String range(String a,Long r,Long c){return(r==null?"":" AND "+a+".round_id="+r)+(c==null?"":" AND "+a+".cycle_id="+c);}private static Object[] args(String d,long p,Long s,AuthUser u){return s==null?new Object[]{u.tenantId(),d,p}:new Object[]{u.tenantId(),d,p,s};}private static Object[] concat(Object[] a,Object[] b){Object[] x=Arrays.copyOf(a,a.length+b.length);System.arraycopy(b,0,x,a.length,b.length);return x;}@SuppressWarnings("unchecked")private static List<Map<String,Object>> rows(Map<String,Object> x){return(List<Map<String,Object>>)x.get("rows");}private static Map<String,Object> row(String d,Object v){return new LinkedHashMap<>(Map.of("dimension",d,"value",v==null?0:v));}private static void rates(Map<String,Object> x){long total=n(x.get("effective_case_total")),done=n(x.get("execution_total"));x.put("execution_rate",rate(done,total));x.put("case_success_rate",rate(n(x.get("success_count")),total));x.put("executed_case_success_rate",rate(n(x.get("success_count")),done));}private static long n(Object x){return x instanceof Number v?v.longValue():0;}private static double rate(long a,long b){return b==0?0D:Math.round(a*10000D/b)/100D;}
 private static String chart(String key){return switch(key){case "CHT-001","CHT-002","CHT-003"->"PIE";case "CHT-007","CHT-008","CHT-016"->"STACKED_BAR";case "CHT-012"->"RADAR";case "CHT-015"->"HEATMAP";case "CHT-004","CHT-010","CHT-013","CHT-014"->"LINE";default->"BAR";};}private static List<Map<String,String>> fixed(){return Stream.concat(TestAnalyticsMetricCatalog.FIXED_REPORTS.stream(),TestAnalyticsMetricCatalog.FIXED_CHARTS.stream()).toList();}private List<Map<String,Object>> options(String d,long p,String code,AuthUser u){return jdbc.queryForList("SELECT o.option_code,o.option_name FROM tm_test_dictionary_option o JOIN tm_test_dictionary x ON x.id=o.dictionary_id AND x.tenant_id=o.tenant_id WHERE x.tenant_id=? AND x.test_domain=? AND x.project_id=? AND x.dictionary_code=? AND x.deleted=0 AND o.deleted=0 AND o.enabled=1 ORDER BY o.sort_no,o.id",u.tenantId(),d,p,code);}
 @SuppressWarnings("unchecked")private void localize(Map<String,Object> out){if(out.get("rows") instanceof List<?> r)for(Object x:r)if(x instanceof Map<?,?> row)for(Object k:new ArrayList<>(row.keySet())){Object v=row.get(k);if(v instanceof String s)((Map<Object,Object>)row).put(k,labels().getOrDefault(s,s));}}private static Map<String,String> labels(){return Map.ofEntries(Map.entry("UNEXECUTED","未执行"),Map.entry("IN_PROGRESS","执行中"),Map.entry("RUNNING","执行中"),Map.entry("SUCCESS","成功"),Map.entry("FAILED","失败"),Map.entry("BLOCKED","阻塞"),Map.entry("RAISED","已提出"),Map.entry("ANALYZING","分析中"),Map.entry("RESOLVED","已解决"),Map.entry("CLOSED","已关闭"),Map.entry("FATAL","致命"),Map.entry("SERIOUS","严重"),Map.entry("NORMAL","一般"),Map.entry("MINOR","轻微"));}private static Long num(Object x){try{return x==null||String.valueOf(x).isBlank()?null:Long.valueOf(String.valueOf(x));}catch(Exception e){throw bad("筛选编号无效");}}private String encode(Object x){try{return json.writeValueAsString(x);}catch(Exception e){throw bad("统计快照序列化失败");}}private static long next(){return System.currentTimeMillis()*1000+ThreadLocalRandom.current().nextInt(1000);}private static BusinessException bad(String x){return new BusinessException(ErrorCode.BAD_REQUEST,x);}
}
