package com.ccb.testmanagement.analytics;

import com.ccb.common.exception.BusinessException;
import com.ccb.common.exception.ErrorCode;
import com.ccb.security.model.AuthUser;
import com.ccb.testmanagement.report.TestReportService;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;

/** Preset report composition. Queries are owned by TestAnalyticsRepository. */
@Service public class TestAnalyticsAdvancedService {
 private final TestAnalyticsRepository repository;private final ObjectMapper json;private final TestReportService reports;
 public TestAnalyticsAdvancedService(TestAnalyticsRepository repository,ObjectMapper json,TestReportService reports){this.repository=repository;this.json=json;this.reports=reports;}
 public Map<String,Object> filters(String d,long p,AuthUser u){Map<String,Object> root=reports.tree(d,p,u);Map<String,Object>x=params(d,p,u);return Map.of("systems",root.get("systems"),"rounds",repository.rounds(x),"cycles",repository.cycles(x),"case_types",options(x,"case_type"),"defect_categories",options(x,"defect_category"),"severities",options(x,"severity"),"priorities",options(x,"priority"),"urgencies",options(x,"urgency"));}
 public Map<String,Object> preset(String d,long p,String key,Map<String,Object> f,AuthUser u){reports.tree(d,p,u);Map<String,Object>x=params(d,p,u);x.put("systemId",num(f.get("physical_subsystem_id")));x.put("roundId",num(f.get("round_id")));x.put("cycleId",num(f.get("cycle_id")));x.put("view",String.valueOf(f.getOrDefault("view","TABLE")).toUpperCase(Locale.ROOT));x.put("perspective",String.valueOf(f.getOrDefault("perspective","EXECUTOR")).toUpperCase(Locale.ROOT));Map<String,Object> out=new LinkedHashMap<>();out.put("key",key);out.put("view",x.get("view"));out.put("filters",f);switch(key){case "SCOPE_COVERAGE"->coverage(x,out);case "EXECUTION_PROGRESS"->execution(x,out);case "DEFECT_DISTRIBUTION"->defects(x,out);case "PERSONNEL_WORKLOAD"->workload(x,out);default->throw bad("预置报表不存在");}return out;}
 @Transactional public List<Map<String,Object>> archive(String d,long p,long round,AuthUser u){reports.tree(d,p,u);Map<String,Object>x=params(d,p,u);x.put("roundId",round);if(n(repository.roundCount(x))==0)throw bad("轮次不存在");List<Map<String,Object>> saved=new ArrayList<>();for(String key:List.of("SCOPE_COVERAGE","EXECUTION_PROGRESS","DEFECT_DISTRIBUTION","PERSONNEL_WORKLOAD")){Map<String,Object> data=preset(d,p,key,Map.of("round_id",round),u);Map<String,Object> snapshot=params(d,p,u);snapshot.put("id",next());snapshot.put("roundId",round);snapshot.put("reportKey",key);snapshot.put("snapshotJson",encode(data));repository.upsertSnapshot(snapshot);saved.add(Map.of("report_key",key,"archived_at",String.valueOf(java.time.LocalDateTime.now())));}return saved;}
 public List<Map<String,Object>> compare(String d,long p,List<Long> rounds,AuthUser u){reports.tree(d,p,u);if(rounds==null||rounds.size()<2)throw bad("请选择至少两个已归档轮次");List<Map<String,Object>> out=new ArrayList<>();for(Long round:rounds){Map<String,Object>x=params(d,p,u);x.put("roundId",round);List<Map<String,Object>> rows=repository.snapshotRows(x);Map<String,Object> item=new LinkedHashMap<>();item.put("round_id",round);item.put("round_name",repository.roundName(x));item.put("archived_at",rows.isEmpty()?null:rows.get(0).get("archived_at"));for(Map<String,Object> row:rows){Map<String,Object> summary=map(map(row.get("snapshot_json")).get("summary"));String key=String.valueOf(row.get("report_key"));item.put(key+"_scope_total",summary.getOrDefault("scope_total",0));item.put(key+"_case_total",summary.getOrDefault("case_total",0));item.put(key+"_success_rate",summary.getOrDefault("success_rate",0));item.put(key+"_defect_total",summary.getOrDefault("defect_total",0));}out.add(item);}return out;}
 private void coverage(Map<String,Object>x,Map<String,Object> out){List<Map<String,Object>> rows=repository.scopeCoverage(x);for(Map<String,Object> row:rows){long total=n(row.get("scope_total"));row.put("coverage_rate",total==0?0:Math.round(n(row.get("covered_total"))*10000D/total)/100D);}out.put("rows",rows);out.put("charts",Map.of("BAR",rows,"TABLE",rows));}
 private void execution(Map<String,Object>x,Map<String,Object> out){List<Map<String,Object>> rows=repository.executionRows(x);for(Map<String,Object> r:rows){long total=n(r.get("execution_total"));r.put("execution_rate",total==0?0:Math.round((n(r.get("success_count"))+n(r.get("failed_count"))+n(r.get("blocked_count")))*10000D/total)/100D);r.put("success_rate",total==0?0:Math.round(n(r.get("success_count"))*10000D/total)/100D);}out.put("rows",rows);out.put("trend",repository.executionTrend(x));}
 private void defects(Map<String,Object>x,Map<String,Object> out){out.put("rows",repository.defectRows(x));out.put("trend",repository.defectTrend(x));}
 private void workload(Map<String,Object>x,Map<String,Object> out){out.put("rows",repository.workloadRows(x));}
 private List<Map<String,Object>> options(Map<String,Object> x,String code){Map<String,Object> p=new HashMap<>(x);p.put("dictionaryCode",code);return repository.dictionaryOptions(p);}private static Map<String,Object> params(String d,long p,AuthUser u){Map<String,Object>x=new HashMap<>();x.put("tenantId",u.tenantId());x.put("domain",d);x.put("projectId",p);x.put("userId",u.id());return x;}private long n(Object v){return v instanceof Number x?x.longValue():0;}private Long num(Object x){try{return x==null||String.valueOf(x).isBlank()?null:Long.valueOf(String.valueOf(x));}catch(Exception e){throw bad("筛选编号无效");}}private String encode(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw bad("统计快照序列化失败");}}private Map<String,Object> map(Object value){try{return value==null?Map.of():json.readValue(String.valueOf(value),new TypeReference<>(){});}catch(Exception e){return Map.of();}}private static long next(){return System.currentTimeMillis()*1000+ThreadLocalRandom.current().nextInt(1000);}private static BusinessException bad(String s){return new BusinessException(ErrorCode.BAD_REQUEST,s);}
}
