package com.ccb.system.service;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.context.annotation.Configuration;

import java.util.List;
import java.util.Map;

/** SQL contract for the system administration aggregate. */
@Mapper
public interface SystemMapper {
    List<Map<String, Object>> selectUsers(@Param("p") Map<String, Object> p); long countUsers(@Param("p") Map<String, Object> p); Map<String, Object> selectUser(@Param("id") long id, @Param("tenantId") long tenantId); int insertUser(@Param("p") Map<String, Object> p); int updateUser(@Param("p") Map<String, Object> p); int updateUserStatus(@Param("id") long id, @Param("tenantId") long tenantId, @Param("status") int status); int deleteUser(@Param("id") long id, @Param("tenantId") long tenantId); String selectAvatarObjectKey(@Param("id") long id, @Param("tenantId") long tenantId); int updateAvatar(@Param("id") long id, @Param("tenantId") long tenantId, @Param("objectKey") String objectKey);
    List<Map<String, Object>> selectRoles(@Param("p") Map<String, Object> p); long countRoles(@Param("p") Map<String, Object> p); Map<String, Object> selectRole(@Param("id") long id, @Param("tenantId") long tenantId); int insertRole(@Param("p") Map<String, Object> p); int updateRole(@Param("p") Map<String, Object> p); int updateRoleStatus(@Param("id") long id, @Param("tenantId") long tenantId, @Param("status") int status); int deleteRole(@Param("id") long id, @Param("tenantId") long tenantId);
    List<Map<String, Object>> selectOrganizations(@Param("p") Map<String, Object> p); long countOrganizations(@Param("p") Map<String, Object> p); Map<String, Object> selectOrganization(@Param("id") long id, @Param("tenantId") long tenantId); int insertOrganization(@Param("p") Map<String, Object> p); int updateOrganization(@Param("p") Map<String, Object> p); int updateOrganizationStatus(@Param("id") long id, @Param("tenantId") long tenantId, @Param("status") int status); int deleteOrganization(@Param("id") long id, @Param("tenantId") long tenantId); long countOrganization(@Param("id") long id, @Param("tenantId") long tenantId); Long selectOrganizationParent(@Param("id") long id, @Param("tenantId") long tenantId); String selectOrganizationName(@Param("id") long id, @Param("tenantId") long tenantId);
    List<Map<String, Object>> selectMenus(@Param("p") Map<String, Object> p); long countMenus(@Param("p") Map<String, Object> p); Map<String, Object> selectMenu(@Param("id") long id, @Param("tenantId") long tenantId); int insertMenu(@Param("p") Map<String, Object> p); int updateMenu(@Param("p") Map<String, Object> p); int updateMenuStatus(@Param("id") long id, @Param("tenantId") long tenantId, @Param("status") int status); int deleteMenu(@Param("id") long id, @Param("tenantId") long tenantId);
    List<Map<String, Object>> selectDictionaryTypes(@Param("p") Map<String, Object> p); long countDictionaryTypes(@Param("p") Map<String, Object> p); Map<String, Object> selectDictionaryType(@Param("id") long id, @Param("tenantId") long tenantId); int insertDictionaryType(@Param("p") Map<String, Object> p); int updateDictionaryType(@Param("p") Map<String, Object> p); int updateDictionaryTypeStatus(@Param("id") long id, @Param("tenantId") long tenantId, @Param("status") int status); int deleteDictionaryType(@Param("id") long id, @Param("tenantId") long tenantId);
    List<Map<String, Object>> selectParameters(@Param("p") Map<String, Object> p); long countParameters(@Param("p") Map<String, Object> p); Map<String, Object> selectParameter(@Param("id") long id, @Param("tenantId") long tenantId); int insertParameter(@Param("p") Map<String, Object> p); int updateParameter(@Param("p") Map<String, Object> p); int updateParameterStatus(@Param("id") long id, @Param("tenantId") long tenantId, @Param("status") int status); int deleteParameter(@Param("id") long id, @Param("tenantId") long tenantId); String selectDictionaryName(@Param("id") long id, @Param("tenantId") long tenantId);
    List<Map<String, Object>> selectConfigurations(@Param("p") Map<String, Object> p); long countConfigurations(@Param("p") Map<String, Object> p); Map<String, Object> selectConfiguration(@Param("id") long id, @Param("tenantId") long tenantId); int insertConfiguration(@Param("p") Map<String, Object> p); int updateConfiguration(@Param("p") Map<String, Object> p); int updateConfigurationStatus(@Param("id") long id, @Param("tenantId") long tenantId, @Param("status") int status); int deleteConfiguration(@Param("id") long id, @Param("tenantId") long tenantId);
    long countPermittedAction(@Param("userId") long userId, @Param("tenantId") long tenantId, @Param("permissionCode") String permissionCode, @Param("action") String action); List<Map<String, Object>> selectEnabledRoles(@Param("tenantId") long tenantId); List<Long> selectUserRoleIds(@Param("userId") long userId, @Param("tenantId") long tenantId); long countActiveUser(@Param("userId") long userId, @Param("tenantId") long tenantId); int deleteUserRoles(@Param("userId") long userId, @Param("tenantId") long tenantId); int insertUserRoleIfEnabled(@Param("userId") long userId, @Param("roleId") long roleId, @Param("tenantId") long tenantId); int deleteRoleLinks(@Param("roleId") long roleId, @Param("tenantId") long tenantId); int deleteRoleMenus(@Param("roleId") long roleId, @Param("tenantId") long tenantId); int deleteRolePermissions(@Param("roleId") long roleId, @Param("tenantId") long tenantId);
    List<Map<String, Object>> selectPermissionMenus(@Param("tenantId") long tenantId); List<Map<String, Object>> selectMenuActions(@Param("menuId") long menuId, @Param("tenantId") long tenantId); List<Map<String, Object>> selectPermissions(@Param("p") Map<String, Object> p); long countPermissions(@Param("p") Map<String, Object> p); Map<String, Object> selectPermission(@Param("id") long id, @Param("tenantId") long tenantId); long countPermissionDuplicate(@Param("tenantId") long tenantId, @Param("permissionCode") String permissionCode, @Param("menuId") long menuId, @Param("actionCode") String actionCode); int insertPermission(@Param("p") Map<String, Object> p); int updatePermission(@Param("p") Map<String, Object> p); int updatePermissionStatus(@Param("id") long id, @Param("tenantId") long tenantId, @Param("status") int status); int deletePermission(@Param("id") long id, @Param("tenantId") long tenantId); long countPermission(@Param("id") long id, @Param("tenantId") long tenantId); long countPermissionReferences(@Param("id") long id, @Param("tenantId") long tenantId); long countMenu(@Param("id") long id, @Param("tenantId") long tenantId);
    long countRole(@Param("id") long id, @Param("tenantId") long tenantId); List<Long> selectRolePermissionIds(@Param("roleId") long roleId, @Param("tenantId") long tenantId); int deleteRolePermissionLinks(@Param("roleId") long roleId, @Param("tenantId") long tenantId); long countEnabledPermission(@Param("id") long id, @Param("tenantId") long tenantId); int insertRolePermission(@Param("roleId") long roleId, @Param("permissionId") long permissionId, @Param("tenantId") long tenantId); Long selectPermissionMenuId(@Param("id") long id, @Param("tenantId") long tenantId); int deleteRoleMenuLinks(@Param("roleId") long roleId, @Param("tenantId") long tenantId); int insertRoleMenu(@Param("roleId") long roleId, @Param("menuId") long menuId, @Param("tenantId") long tenantId); Long selectMenuParent(@Param("id") long id, @Param("tenantId") long tenantId);
    int insertAudit(@Param("id") long id, @Param("tenantId") long tenantId, @Param("operatorId") long operatorId, @Param("operation") String operation);
}

@Configuration
@MapperScan(basePackageClasses = SystemMapper.class)
class SystemMapperConfiguration {
}
