package com.ccb.testmanagement.announcement;

import com.ccb.attachment.integration.AttachmentBindingCommand;
import com.ccb.attachment.integration.AttachmentGateway;
import com.ccb.attachment.integration.AttachmentItem;
import com.ccb.common.api.PageQuery;
import com.ccb.common.api.PageResult;
import com.ccb.common.exception.BusinessException;
import com.ccb.common.exception.ErrorCode;
import com.ccb.security.model.AuthUser;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;
import java.util.concurrent.ThreadLocalRandom;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Service
public class TestAnnouncementService {
    public static final String BUSINESS_TYPE = "TEST_ANNOUNCEMENT";
    private static final Set<String> DOMAINS = Set.of("application-assembly", "user-testing", "non-functional", "security");
    private static final Pattern STYLE_ATTRIBUTE = Pattern.compile("(?is)\\sstyle\\s*=\\s*(['\"])(.*?)\\1");
    private final TestAnnouncementRepository repository; private final AttachmentGateway attachments;
    public TestAnnouncementService(TestAnnouncementRepository repository, AttachmentGateway attachments) { this.repository = repository; this.attachments = attachments; }
    public List<Map<String,Object>> projects(AuthUser user) { return repository.projects(p("tenantId",user.tenantId())); }
    public List<Map<String,Object>> current(String domain,long projectId,AuthUser user) { scope(domain,projectId,user); List<Map<String,Object>> rows=repository.pinned(scopeParams(domain,projectId,user)); return detailRows(rows.isEmpty()?repository.newest(scopeParams(domain,projectId,user)):rows,user); }
    public PageResult<Map<String,Object>> list(String domain,long projectId,PageQuery page,String keyword,String publisher,String from,String to,AuthUser user) { scope(domain,projectId,user); Map<String,Object> params=scopeParams(domain,projectId,user); params.put("keyword",trim(keyword));params.put("publisher",trim(publisher));params.put("from",trim(from));params.put("to",trim(to));long total=repository.count(params);params.put("offset",(page.page()-1)*page.size());params.put("size",page.size());List<Map<String,Object>> rows=repository.page(params);for(Map<String,Object> row:rows)row.put("attachment_count",repository.attachmentCount(p("tenantId",user.tenantId(),"id",number(row.get("id")))));return new PageResult<>(rows,total,page.page(),page.size()); }
    public Map<String,Object> detail(String domain,long projectId,long id,AuthUser user) { scope(domain,projectId,user);return detailRow(announcement(id,domain,projectId,user.tenantId()),user); }
    @Transactional public Map<String,Object> save(String domain,long projectId,Long id,Map<String,Object> body,AuthUser user) { scope(domain,projectId,user);String title=required(body.get("title"),"公告标题",100),html=sanitize(required(body.get("content_html"),"公告正文",100000));if(strip(html).isBlank())throw bad("公告正文不能为空");long saved=id==null?next():id;int pinned=bool(body.get("pinned"))?1:0;if(id==null)repository.insert(p("id",saved,"tenantId",user.tenantId(),"domain",domain,"projectId",projectId,"title",title,"html",html,"pinned",pinned,"userId",user.id()));else {announcement(id,domain,projectId,user.tenantId());repository.update(p("id",saved,"tenantId",user.tenantId(),"title",title,"html",html,"pinned",pinned,"userId",user.id()));}syncAttachments(saved,body.get("attachment_ids"),body.get("inline_attachment_ids"),user);audit(domain,projectId,saved,id==null?"CREATE":"UPDATE",user);return detail(domain,projectId,saved,user); }
    @Transactional public Map<String,Object> pin(String domain,long projectId,long id,boolean pinned,AuthUser user) { scope(domain,projectId,user);announcement(id,domain,projectId,user.tenantId());repository.pin(p("id",id,"tenantId",user.tenantId(),"pinned",pinned?1:0,"userId",user.id()));audit(domain,projectId,id,pinned?"PIN":"UNPIN",user);return detail(domain,projectId,id,user); }
    @Transactional public void delete(String domain,long projectId,long id,AuthUser user) { scope(domain,projectId,user);announcement(id,domain,projectId,user.tenantId());for(Long attachmentId:repository.attachmentIds(p("tenantId",user.tenantId(),"id",id)))attachments.deleteBound(attachmentId,BUSINESS_TYPE,String.valueOf(id),user);repository.deleteAttachments(p("tenantId",user.tenantId(),"id",id));repository.deleteAnnouncement(p("tenantId",user.tenantId(),"id",id,"userId",user.id()));audit(domain,projectId,id,"DELETE",user); }
    private void syncAttachments(long id,Object normal,Object inline,AuthUser user) { Set<Long> wanted=new LinkedHashSet<>(),inlines=ids(inline);wanted.addAll(ids(normal));wanted.addAll(inlines);List<Long> old=repository.attachmentIds(p("tenantId",user.tenantId(),"id",id));for(Long attachmentId:old)if(!wanted.contains(attachmentId)){attachments.deleteBound(attachmentId,BUSINESS_TYPE,String.valueOf(id),user);repository.deleteAttachment(p("tenantId",user.tenantId(),"id",id,"attachmentId",attachmentId));}int sort=0;for(Long attachmentId:wanted){AttachmentItem item=attachments.get(attachmentId,user);if(item.fileSize()>50L*1024*1024)throw bad("单个附件不能超过50MB");if(!old.contains(attachmentId)){attachments.bind(new AttachmentBindingCommand(attachmentId,BUSINESS_TYPE,String.valueOf(id),null),user);repository.insertAttachment(p("id",next(),"tenantId",user.tenantId(),"announcementId",id,"attachmentId",attachmentId,"attachmentType",inlines.contains(attachmentId)?"INLINE":"FILE","sortNo",sort));}sort++;} }
    private List<Map<String,Object>> detailRows(List<Map<String,Object>> rows,AuthUser user) { for(Map<String,Object> row:rows)row.putAll(detailRow(row,user));return rows; }
    private Map<String,Object> detailRow(Map<String,Object> row,AuthUser user) { Map<String,Object> result=new LinkedHashMap<>(row);result.put("attachments",repository.attachments(p("tenantId",user.tenantId(),"id",number(row.get("id")))));return result; }
    private Map<String,Object> announcement(long id,String domain,long projectId,long tenantId) { Map<String,Object> result=repository.find(p("id",id,"tenantId",tenantId,"domain",domain,"projectId",projectId));if(result==null)throw bad("公告不存在或不属于当前项目");return result; }
    private void scope(String domain,long projectId,AuthUser user) { if(!DOMAINS.contains(domain))throw bad("测试大类无效");if(!repository.projectExists(p("projectId",projectId,"tenantId",user.tenantId())))throw bad("项目不存在或无权访问"); }
    private void audit(String domain,long projectId,long announcementId,String action,AuthUser user) { repository.insertAudit(p("id",next(),"tenantId",user.tenantId(),"domain",domain,"projectId",projectId,"announcementId",announcementId,"action",action,"userId",user.id())); }
    private Map<String,Object> scopeParams(String domain,long projectId,AuthUser user){return p("tenantId",user.tenantId(),"domain",domain,"projectId",projectId);} private static Map<String,Object> p(Object... values){Map<String,Object> result=new HashMap<>();for(int i=0;i<values.length;i+=2)result.put((String)values[i],values[i+1]);return result;}private static String trim(String value){return value==null||value.isBlank()?null:value.trim();}
    private static String required(Object value,String name,int max){String result=value==null?"":String.valueOf(value).trim();if(result.isBlank()||result.length()>max)throw bad(name+"无效");return result;}private static boolean bool(Object value){return value instanceof Boolean b?b:"1".equals(String.valueOf(value))||"true".equalsIgnoreCase(String.valueOf(value));}private static long number(Object value){return ((Number)value).longValue();}private static BusinessException bad(String message){return new BusinessException(ErrorCode.BAD_REQUEST,message);}private static long next(){return System.currentTimeMillis()*1000+ThreadLocalRandom.current().nextInt(1000);}private static Set<Long> ids(Object value){Set<Long> result=new LinkedHashSet<>();if(value instanceof Collection<?> collection)for(Object item:collection)try{result.add(Long.parseLong(String.valueOf(item)));}catch(NumberFormatException ignored){}return result;}private static String strip(String value){return value.replaceAll("<[^>]*>","").replace("&nbsp;"," ").trim();}
    private static String sanitize(String value){String result=value.replaceAll("(?is)<(script|style)[^>]*>.*?</\\1>","").replaceAll("(?i)\\s+on\\w+\\s*=\\s*(['\"]).*?\\1","").replaceAll("(?i)\\s+on\\w+\\s*=\\s*[^\\s>]+","").replaceAll("(?i)(javascript|data):","");result=result.replaceAll("(?is)<(?!/?(p|br|strong|b|em|i|s|del|sup|sub|span|h1|h2|h3|h4|h5|ul|ol|li|blockquote|pre|code|hr|table|thead|tbody|tr|th|td|a|img)\\b)[^>]*>","");return sanitizeStyles(result);}private static String sanitizeStyles(String html){Matcher matcher=STYLE_ATTRIBUTE.matcher(html);StringBuffer out=new StringBuffer();while(matcher.find()){String style=sanitizeStyle(matcher.group(2));matcher.appendReplacement(out,Matcher.quoteReplacement(style.isBlank()?"":" style=\""+style+"\""));}matcher.appendTail(out);return out.toString();}private static String sanitizeStyle(String raw){List<String> safe=new ArrayList<>();for(String declaration:raw.split(";")){int colon=declaration.indexOf(':');if(colon<1)continue;String property=declaration.substring(0,colon).trim().toLowerCase(Locale.ROOT),value=declaration.substring(colon+1).trim();if(safeStyle(property,value))safe.add(property+":"+value);}return String.join(";",safe);}private static boolean safeStyle(String property,String value){return switch(property){case "color","background-color"->value.matches("(?i)(#[0-9a-f]{3,8}|rgba?\\([0-9.,%\\s]+\\)|hsla?\\([0-9.,%\\s]+\\)|[a-z]{3,20})");case "font-size"->value.matches("\\d{1,3}(px|pt|em|rem|%)");case "font-family"->value.matches("[\\p{L}\\p{N}\\s,'\"-]{1,80}");case "line-height"->value.matches("(?:\\d(?:\\.\\d{1,2})?|\\d{1,3}(px|pt|em|rem|%))");case "text-align"->value.matches("(?i)(left|right|center|justify)");case "text-indent"->value.matches("\\d{1,3}(px|em|rem|%)");case "font-weight"->value.matches("(?i)(normal|bold|[1-9]00)");case "font-style"->value.matches("(?i)(normal|italic)");case "text-decoration"->value.matches("(?i)(none|underline|line-through)");default->false;};}
}
