-- V183: 数据迁移模块业务码值统一纳入“系统管理/参数管理”。
-- 仅追加、幂等；已经存在的管理员配置不会被覆盖（INSERT IGNORE）。

INSERT IGNORE INTO sys_dict_type (id, tenant_id, dict_code, dict_name, status, deleted)
VALUES
    (5801, 1, 'DM_TOPIC_GRANULARITY', '专题材料颗粒度', 1, 0),
    (5802, 1, 'DM_PLAN_GRANULARITY', '迁移方案颗粒度', 1, 0),
    (5803, 1, 'DM_PLAN_TYPE', '迁移方案类型', 1, 0),
    (5804, 1, 'DM_ISSUE_GRANULARITY', '问题颗粒度', 1, 0),
    (5805, 1, 'DM_ISSUE_SOURCE', '问题来源', 1, 0),
    (5806, 1, 'DM_DEFECT_TYPE', '缺陷类型', 1, 0),
    (5807, 1, 'DM_ISSUE_FREQUENCY', '问题频率', 1, 0),
    (5808, 1, 'DM_MEETING_GRANULARITY', '会议纪要颗粒度', 1, 0),
    (5809, 1, 'DM_MEETING_SOURCE', '会议纪要来源', 1, 0),
    (5810, 1, 'DM_REPORT_PERIOD', '汇报周期', 1, 0),
    (5811, 1, 'DM_TARGET_TABLE_CATEGORY', '目标表/中间表类别', 1, 0);

INSERT IGNORE INTO sys_config (id, tenant_id, category_id, config_key, config_value, config_type, remark, status, deleted)
SELECT v.id, 1, t.id, v.config_key, v.config_value, 'string', '数据迁移业务码值（系统管理/参数管理维护）', 1, 0
FROM (
    SELECT 58101 id, 'DM_TOPIC_GRANULARITY.PROJECT' config_key, '项目级' config_value, 'DM_TOPIC_GRANULARITY' category_code
    UNION ALL SELECT 58102, 'DM_TOPIC_GRANULARITY.SYSTEM', '系统级', 'DM_TOPIC_GRANULARITY'
    UNION ALL SELECT 58103, 'DM_PLAN_GRANULARITY.PROJECT', '项目级', 'DM_PLAN_GRANULARITY'
    UNION ALL SELECT 58104, 'DM_PLAN_GRANULARITY.SYSTEM', '系统级', 'DM_PLAN_GRANULARITY'
    UNION ALL SELECT 58105, 'DM_PLAN_TYPE.BUSINESS', '业务迁移方案', 'DM_PLAN_TYPE'
    UNION ALL SELECT 58106, 'DM_PLAN_TYPE.DATA', '数据迁移方案', 'DM_PLAN_TYPE'
    UNION ALL SELECT 58107, 'DM_ISSUE_GRANULARITY.PROJECT', '项目级', 'DM_ISSUE_GRANULARITY'
    UNION ALL SELECT 58108, 'DM_ISSUE_GRANULARITY.COMPONENT', '组件级', 'DM_ISSUE_GRANULARITY'
    UNION ALL SELECT 58109, 'DM_ISSUE_GRANULARITY.TABLE', '表级', 'DM_ISSUE_GRANULARITY'
    UNION ALL SELECT 58110, 'DM_ISSUE_GRANULARITY.FIELD', '字段级', 'DM_ISSUE_GRANULARITY'
    UNION ALL SELECT 58111, 'DM_ISSUE_SOURCE.MIGRATION_CHECK', '数迁检核', 'DM_ISSUE_SOURCE'
    UNION ALL SELECT 58112, 'DM_ISSUE_SOURCE.SIT_FEEDBACK', 'SIT测试反馈', 'DM_ISSUE_SOURCE'
    UNION ALL SELECT 58113, 'DM_ISSUE_SOURCE.UAT_FEEDBACK', 'UAT测试反馈', 'DM_ISSUE_SOURCE'
    UNION ALL SELECT 58114, 'DM_ISSUE_SOURCE.DATA_LINE_FEEDBACK', '数据线反馈', 'DM_ISSUE_SOURCE'
    UNION ALL SELECT 58115, 'DM_ISSUE_SOURCE.EXPERT_FEEDBACK', '事业群专家反馈', 'DM_ISSUE_SOURCE'
    UNION ALL SELECT 58116, 'DM_ISSUE_SOURCE.RISK_IDENTIFICATION', '风险识别', 'DM_ISSUE_SOURCE'
    UNION ALL SELECT 58117, 'DM_ISSUE_SOURCE.MIGRATION_RELEASE', '数迁投产过程', 'DM_ISSUE_SOURCE'
    UNION ALL SELECT 58118, 'DM_DEFECT_TYPE.REQUIREMENT', '需求问题', 'DM_DEFECT_TYPE'
    UNION ALL SELECT 58119, 'DM_DEFECT_TYPE.DESIGN', '设计问题', 'DM_DEFECT_TYPE'
    UNION ALL SELECT 58120, 'DM_DEFECT_TYPE.CODING', '编码问题', 'DM_DEFECT_TYPE'
    UNION ALL SELECT 58121, 'DM_DEFECT_TYPE.DATA_QUALITY', '数据质量问题', 'DM_DEFECT_TYPE'
    UNION ALL SELECT 58122, 'DM_DEFECT_TYPE.CLEANUP', '清理补录问题', 'DM_DEFECT_TYPE'
    UNION ALL SELECT 58123, 'DM_DEFECT_TYPE.BUSINESS', '业务问题', 'DM_DEFECT_TYPE'
    UNION ALL SELECT 58124, 'DM_DEFECT_TYPE.UNDERSTANDING', '理解问题', 'DM_DEFECT_TYPE'
    UNION ALL SELECT 58125, 'DM_DEFECT_TYPE.PERFORMANCE', '性能问题', 'DM_DEFECT_TYPE'
    UNION ALL SELECT 58126, 'DM_DEFECT_TYPE.MASKING', '脱敏问题', 'DM_DEFECT_TYPE'
    UNION ALL SELECT 58127, 'DM_DEFECT_TYPE.OTHER', '其他问题', 'DM_DEFECT_TYPE'
    UNION ALL SELECT 58128, 'DM_ISSUE_FREQUENCY.CLASSIC', '经典问题', 'DM_ISSUE_FREQUENCY'
    UNION ALL SELECT 58129, 'DM_ISSUE_FREQUENCY.HIGH_FREQ', '高频重复', 'DM_ISSUE_FREQUENCY'
    UNION ALL SELECT 58130, 'DM_ISSUE_FREQUENCY.LOW_FREQ', '低频偶发', 'DM_ISSUE_FREQUENCY'
    UNION ALL SELECT 58131, 'DM_ISSUE_FREQUENCY.SINGLE_CASE', '单次个案', 'DM_ISSUE_FREQUENCY'
    UNION ALL SELECT 58132, 'DM_MEETING_GRANULARITY.PROJECT', '项目级', 'DM_MEETING_GRANULARITY'
    UNION ALL SELECT 58133, 'DM_MEETING_GRANULARITY.COMPONENT', '组件级', 'DM_MEETING_GRANULARITY'
    UNION ALL SELECT 58134, 'DM_MEETING_GRANULARITY.TABLE', '表级', 'DM_MEETING_GRANULARITY'
    UNION ALL SELECT 58135, 'DM_MEETING_GRANULARITY.FIELD', '字段级', 'DM_MEETING_GRANULARITY'
    UNION ALL SELECT 58136, 'DM_MEETING_SOURCE.MEETING_MINUTES', '会议纪要', 'DM_MEETING_SOURCE'
    UNION ALL SELECT 58137, 'DM_MEETING_SOURCE.ISSUE_EXTRACT', '问题提取', 'DM_MEETING_SOURCE'
    UNION ALL SELECT 58138, 'DM_REPORT_PERIOD.DAILY', '日报', 'DM_REPORT_PERIOD'
    UNION ALL SELECT 58139, 'DM_REPORT_PERIOD.WEEKLY', '周报', 'DM_REPORT_PERIOD'
    UNION ALL SELECT 58140, 'DM_REPORT_PERIOD.BIWEEKLY', '双周报', 'DM_REPORT_PERIOD'
    UNION ALL SELECT 58141, 'DM_REPORT_PERIOD.MONTHLY', '月报', 'DM_REPORT_PERIOD'
    UNION ALL SELECT 58142, 'DM_REPORT_PERIOD.IRREGULAR', '不定期汇报', 'DM_REPORT_PERIOD'
    UNION ALL SELECT 58143, 'DM_TARGET_TABLE_CATEGORY.TARGET', '目标表结构', 'DM_TARGET_TABLE_CATEGORY'
    UNION ALL SELECT 58144, 'DM_TARGET_TABLE_CATEGORY.INTERMEDIATE', '中间表结构', 'DM_TARGET_TABLE_CATEGORY'
) v
JOIN sys_dict_type t ON t.tenant_id = 1 AND t.dict_code = v.category_code AND t.deleted = 0;
