-- 补齐迁移工具和 Flowable 事件注册表的元数据注释。
-- 这些表由外部框架维护，本迁移不改变其字段定义。

ALTER TABLE flyway_schema_history
    MODIFY COLUMN installed_rank INT NOT NULL COMMENT '迁移安装顺序',
    MODIFY COLUMN version VARCHAR(50) NULL DEFAULT NULL COMMENT '迁移版本',
    MODIFY COLUMN description VARCHAR(200) NOT NULL COMMENT '迁移描述',
    MODIFY COLUMN type VARCHAR(20) NOT NULL COMMENT '迁移类型',
    MODIFY COLUMN script VARCHAR(1000) NOT NULL COMMENT '迁移脚本名称',
    MODIFY COLUMN checksum INT NULL DEFAULT NULL COMMENT '迁移校验和',
    MODIFY COLUMN installed_by VARCHAR(100) NOT NULL COMMENT '执行迁移的数据库用户',
    MODIFY COLUMN installed_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '迁移执行时间',
    MODIFY COLUMN execution_time INT NOT NULL COMMENT '迁移耗时毫秒',
    MODIFY COLUMN success TINYINT(1) NOT NULL COMMENT '迁移是否成功';

ALTER TABLE FLW_EV_DATABASECHANGELOG COMMENT = 'Flowable事件注册变更日志表';
ALTER TABLE FLW_EV_DATABASECHANGELOG
    MODIFY COLUMN ID VARCHAR(255) NOT NULL COMMENT '变更记录ID',
    MODIFY COLUMN AUTHOR VARCHAR(255) NOT NULL COMMENT '变更作者',
    MODIFY COLUMN FILENAME VARCHAR(255) NOT NULL COMMENT '变更文件',
    MODIFY COLUMN DATEEXECUTED DATETIME NOT NULL COMMENT '执行时间',
    MODIFY COLUMN ORDEREXECUTED INT NOT NULL COMMENT '执行顺序',
    MODIFY COLUMN EXECTYPE VARCHAR(10) NOT NULL COMMENT '执行类型',
    MODIFY COLUMN MD5SUM VARCHAR(35) NULL DEFAULT NULL COMMENT '变更校验和',
    MODIFY COLUMN DESCRIPTION VARCHAR(255) NULL DEFAULT NULL COMMENT '变更描述',
    MODIFY COLUMN COMMENTS VARCHAR(255) NULL DEFAULT NULL COMMENT '变更说明',
    MODIFY COLUMN TAG VARCHAR(255) NULL DEFAULT NULL COMMENT '变更标签',
    MODIFY COLUMN LIQUIBASE VARCHAR(20) NULL DEFAULT NULL COMMENT 'Liquibase版本',
    MODIFY COLUMN CONTEXTS VARCHAR(255) NULL DEFAULT NULL COMMENT '执行上下文',
    MODIFY COLUMN LABELS VARCHAR(255) NULL DEFAULT NULL COMMENT '执行标签',
    MODIFY COLUMN DEPLOYMENT_ID VARCHAR(10) NULL DEFAULT NULL COMMENT '部署标识';

ALTER TABLE FLW_EV_DATABASECHANGELOGLOCK COMMENT = 'Flowable事件注册变更锁表';
ALTER TABLE FLW_EV_DATABASECHANGELOGLOCK
    MODIFY COLUMN ID INT NOT NULL COMMENT '锁记录ID',
    MODIFY COLUMN LOCKED TINYINT NOT NULL COMMENT '是否已锁定',
    MODIFY COLUMN LOCKGRANTED DATETIME NULL DEFAULT NULL COMMENT '锁定时间',
    MODIFY COLUMN LOCKEDBY VARCHAR(255) NULL DEFAULT NULL COMMENT '锁定者';
