CREATE TABLE arch_logical_subsystem (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    code VARCHAR(32) NOT NULL,
    short_name VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL,
    business_org_id BIGINT NOT NULL,
    deployment_platform_code VARCHAR(64) NULL,
    system_type_code VARCHAR(64) NULL,
    system_ownership_code VARCHAR(64) NULL,
    contact_user_id BIGINT NOT NULL,
    description VARCHAR(2000) NULL,
    remark VARCHAR(1000) NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_arch_logical_tenant_id (tenant_id, id),
    UNIQUE KEY uk_arch_logical_code (tenant_id, code),
    UNIQUE KEY uk_arch_logical_name (tenant_id, name),
    KEY idx_arch_logical_list (tenant_id, deleted, id),
    KEY idx_arch_logical_business_org (tenant_id, business_org_id, deleted),
    KEY idx_arch_logical_contact (tenant_id, contact_user_id, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='逻辑子系统表';

CREATE TABLE arch_physical_subsystem (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    code VARCHAR(32) NOT NULL,
    short_name VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL,
    logical_subsystem_id BIGINT NOT NULL,
    business_group_name VARCHAR(100) NULL,
    responsible_team_org_id BIGINT NOT NULL,
    responsible_team_name_snapshot VARCHAR(200) NOT NULL,
    runtime_code VARCHAR(64) NULL,
    system_level_code VARCHAR(64) NULL,
    development_framework_code VARCHAR(64) NULL,
    owner_user_id BIGINT NULL,
    contact_user_id BIGINT NULL,
    description VARCHAR(2000) NULL,
    remark VARCHAR(1000) NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_arch_physical_code (tenant_id, code),
    UNIQUE KEY uk_arch_physical_name (tenant_id, name),
    KEY idx_arch_physical_list (tenant_id, deleted, id),
    KEY idx_arch_physical_logical (tenant_id, logical_subsystem_id, deleted),
    KEY idx_arch_physical_team (tenant_id, responsible_team_org_id, deleted),
    KEY idx_arch_physical_owner (tenant_id, owner_user_id, deleted),
    KEY idx_arch_physical_contact (tenant_id, contact_user_id, deleted),
    CONSTRAINT fk_arch_physical_logical
        FOREIGN KEY (tenant_id, logical_subsystem_id)
        REFERENCES arch_logical_subsystem (tenant_id, id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物理子系统表';
