-- 需求管理平台：新建项目差异清单、存量需求阶段、系统清单、基线、统一改动记录与导入批次。
-- 全部表使用 req_ 前缀，包含 tenant_id、软删除与审计字段；仅追加新表，不修改历史迁移。

CREATE TABLE req_system (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    system_code VARCHAR(64) NOT NULL COMMENT '系统编号',
    system_name VARCHAR(128) NOT NULL COMMENT '系统名称',
    english_name VARCHAR(128) NULL COMMENT '英文简称',
    conglomerate VARCHAR(64) NULL COMMENT '事业群',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE/INACTIVE',
    logical_subsystem_code VARCHAR(64) NULL COMMENT '所属逻辑子系统编号',
    logical_subsystem_name VARCHAR(128) NULL COMMENT '所属逻辑子系统名称',
    business_component_code VARCHAR(64) NULL COMMENT '归属业务组件编号',
    business_component_name VARCHAR(128) NULL COMMENT '归属业务组件名称',
    business_domain VARCHAR(128) NULL COMMENT '业务领域',
    product_view VARCHAR(128) NULL COMMENT '产品视图',
    launch_point VARCHAR(128) NULL COMMENT '投产点',
    category VARCHAR(64) NULL COMMENT '类别',
    introduction VARCHAR(1000) NULL COMMENT '系统介绍',
    disaster_level VARCHAR(64) NULL COMMENT '灾备等级',
    source_type VARCHAR(32) NULL COMMENT '引入/保留',
    created_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_req_system_code (tenant_id, system_code),
    KEY idx_req_system_name (tenant_id, system_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='需求管理系统清单主数据';

CREATE TABLE req_project (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    project_code VARCHAR(64) NOT NULL COMMENT '项目编码',
    project_name VARCHAR(200) NOT NULL COMMENT '项目名称',
    project_type VARCHAR(32) NOT NULL DEFAULT 'NEW_PROJECT' COMMENT '项目类型：NEW_PROJECT 0~1 新建',
    start_time DATE NULL COMMENT '启动时间',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE/BASELINED/CLOSED',
    description VARCHAR(1000) NULL COMMENT '说明',
    created_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_req_project_code (tenant_id, project_code),
    KEY idx_req_project_status (tenant_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='新建项目主数据';

CREATE TABLE req_difference (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    project_id BIGINT NOT NULL COMMENT '所属项目',
    seq_no INT NULL COMMENT '序号',
    business_conglomerate VARCHAR(64) NULL COMMENT '事业群',
    business_section VARCHAR(64) NULL COMMENT '业务板块',
    business_group VARCHAR(64) NULL COMMENT '业务组',
    requirement_no VARCHAR(64) NULL COMMENT '需求编号（组件物理子系统编号+三位序号）',
    category VARCHAR(32) NULL COMMENT '分类：功能/流程/产品/批处理/报表/岗位/菜单/核算/其他',
    name VARCHAR(300) NOT NULL COMMENT '差异点名称',
    system_id BIGINT NULL COMMENT '涉及系统（req_system.id）',
    jinke_practice TEXT NULL COMMENT '金科做法',
    difference_type VARCHAR(64) NULL COMMENT '差异类型',
    monshang_practice TEXT NULL COMMENT '蒙商作法',
    difference_desc TEXT NULL COMMENT '差异描述',
    monshang_dept VARCHAR(128) NULL COMMENT '蒙商分析部门',
    monshang_analyst VARCHAR(64) NULL COMMENT '蒙商分析人',
    jinke_analyst VARCHAR(64) NULL COMMENT '金科分析人',
    adapt_mode VARCHAR(64) NULL COMMENT '适配方式',
    handle_status VARCHAR(64) NULL COMMENT '处理状态',
    coord_group VARCHAR(128) NULL COMMENT '协同组',
    solution TEXT NULL COMMENT '解决方案',
    is_special VARCHAR(4) NULL COMMENT '是否专题：是/否',
    decision_level VARCHAR(64) NULL COMMENT '上升决策层级',
    decision_conclusion TEXT NULL COMMENT '决策结论',
    monshang_confirm_dept VARCHAR(128) NULL COMMENT '蒙商确认部门',
    jinke_confirmer VARCHAR(64) NULL COMMENT '金科确认人',
    review_status VARCHAR(32) NOT NULL DEFAULT 'PENDING_REVIEW' COMMENT '差异状态：PENDING_REVIEW/REVIEWING/REVIEWED/RETURNED',
    review_comment VARCHAR(1000) NULL COMMENT '评审意见/退回意见',
    reviewed_by BIGINT NULL COMMENT '评审人',
    reviewed_at TIMESTAMP NULL COMMENT '评审时间',
    workflow_instance_id VARCHAR(64) NULL COMMENT '预留：审批流实例 ID（审批接入后使用）',
    dev_status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED' COMMENT '开发状态：NOT_STARTED/DEVELOPING/DONE/ONLINE',
    test_status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED' COMMENT '测试状态：NOT_STARTED/TESTING/PASSED',
    baseline_id BIGINT NULL COMMENT '所属基线版本',
    source VARCHAR(16) NOT NULL DEFAULT 'ONLINE' COMMENT '来源：ONLINE/IMPORT',
    import_batch_id BIGINT NULL COMMENT '导入批次',
    created_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    KEY idx_req_difference_project (tenant_id, project_id),
    KEY idx_req_difference_review (tenant_id, review_status),
    KEY idx_req_difference_system (tenant_id, system_id),
    KEY idx_req_difference_no (tenant_id, requirement_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='新建项目需求差异清单（附件1 24 字段 + 生命周期扩展）';

CREATE TABLE req_legacy_requirement (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    legacy_doc_name VARCHAR(200) NULL COMMENT '业需文档名称',
    requirement_no VARCHAR(64) NOT NULL COMMENT '需求编号（维普格式）',
    requirement_name VARCHAR(300) NOT NULL COMMENT '需求名称',
    content_summary VARCHAR(2000) NULL COMMENT '需求内容简述',
    propose_dept VARCHAR(128) NULL COMMENT '需求提出部门',
    proposer VARCHAR(128) NULL COMMENT '需求提出人及电话',
    monshang_ba VARCHAR(64) NULL COMMENT '蒙商 BA',
    monshang_architect VARCHAR(64) NULL COMMENT '蒙商架构',
    expected_launch_date DATE NULL COMMENT '业务期望上线时间',
    regulator VARCHAR(128) NULL COMMENT '外部监管单位',
    regulation_doc_no VARCHAR(200) NULL COMMENT '监管文件名称+文号',
    regulation_desc VARCHAR(2000) NULL COMMENT '监管文件内容描述',
    regulation_launch_date DATE NULL COMMENT '监管要求上线时间',
    requirement_received_date DATE NULL COMMENT '业需入手日',
    requirement_type VARCHAR(32) NULL COMMENT '需求类型：监管/业务/技术',
    regulation_category VARCHAR(32) NULL COMMENT '监管分类：国家级/地方级/处罚整改',
    business_group VARCHAR(64) NOT NULL COMMENT '业务组',
    sub_group VARCHAR(64) NULL COMMENT '分组',
    jinke_contact VARCHAR(128) NULL COMMENT '金科对接人及电话',
    need_jinke_arch_decision VARCHAR(4) NULL COMMENT '是否需要金科架构决策：是/否',
    jinke_architect VARCHAR(64) NULL COMMENT '金科架构人员',
    unified_managed VARCHAR(4) NULL COMMENT '是否纳入蒙商统一管理：是/否',
    ba_review_date DATE NULL COMMENT '业需评审完成日',
    workload_date DATE NULL COMMENT '工作量评估完成日',
    finance_project_date DATE NULL COMMENT '财务立项完成日（任务书）',
    soft_doc_name VARCHAR(200) NULL COMMENT '软需文档名称',
    owner_conglomerate VARCHAR(64) NULL COMMENT '主责事业群',
    owner_system VARCHAR(200) NULL COMMENT '主责物理子系统编号+名称',
    owner_contact VARCHAR(128) NULL COMMENT '主责项目组联系人及电话',
    involve_cooperation VARCHAR(4) NULL COMMENT '是否涉及金科引入组件协同：是/否',
    coord_conglomerate VARCHAR(64) NULL COMMENT '协同事业群',
    coord_system VARCHAR(200) NULL COMMENT '协同系统名称',
    soft_submit_date DATE NULL COMMENT '软需提交日',
    soft_review_date DATE NULL COMMENT '软需评审完成日',
    planned_launch_date DATE NULL COMMENT '计划上线时间',
    actual_launch_date DATE NULL COMMENT '实际上线时间',
    launch_mode VARCHAR(32) NULL COMMENT '上线形式：常规版本/紧急版本',
    requirement_status VARCHAR(32) NULL COMMENT '需求状态：需求分析/业需修订/业需评审通过/立项中/软需编制/软需评审通过/已投产/需求终止',
    remark VARCHAR(1000) NULL COMMENT '备注',
    change_involved VARCHAR(4) NULL COMMENT '是否涉及需求变更：是/否',
    change_info VARCHAR(1000) NULL COMMENT '需求变更信息：谁发起/变更内容/发起阶段',
    change_review_conclusion VARCHAR(32) NULL COMMENT '变更评审结论：评审通过/评审不通过',
    change_conclusion_status VARCHAR(32) NULL COMMENT '变更结论及状态：审核通过/评估工作量/蒙商立项完成',
    change_remark VARCHAR(1000) NULL COMMENT '需求变更备注',
    not_project_developed VARCHAR(4) NULL COMMENT '未立项已开发：是/否',
    current_stage VARCHAR(32) NOT NULL DEFAULT 'PROPOSE' COMMENT '当前阶段：PROPOSE/DOCKING/WORKLOAD/PROJECT/SOFT/LAUNCH',
    propose_stage_status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED' COMMENT '需求提出阶段状态',
    docking_stage_status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED' COMMENT '需求对接阶段状态',
    workload_stage_status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED' COMMENT '工作量评估阶段状态',
    project_stage_status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED' COMMENT '立项阶段状态',
    soft_stage_status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED' COMMENT '软需阶段状态',
    launch_stage_status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED' COMMENT '投产阶段状态',
    source VARCHAR(16) NOT NULL DEFAULT 'ONLINE' COMMENT '来源：ONLINE/IMPORT',
    import_batch_id BIGINT NULL COMMENT '导入批次',
    created_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    KEY idx_req_legacy_group (tenant_id, business_group),
    KEY idx_req_legacy_no (tenant_id, requirement_no),
    KEY idx_req_legacy_stage (tenant_id, current_stage)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='存量项目常态化需求（业务组填写 8 阶段列组）';

CREATE TABLE req_stage_log (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    requirement_id BIGINT NOT NULL COMMENT '存量需求 ID',
    from_stage VARCHAR(32) NULL COMMENT '原阶段',
    to_stage VARCHAR(32) NOT NULL COMMENT '新阶段',
    from_status VARCHAR(32) NULL COMMENT '原状态',
    to_status VARCHAR(32) NOT NULL COMMENT '新状态',
    operator_id BIGINT NOT NULL COMMENT '推进人',
    operator_name VARCHAR(64) NULL COMMENT '推进人姓名',
    comment VARCHAR(500) NULL COMMENT '推进说明',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    KEY idx_req_stage_log_req (tenant_id, requirement_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='存量需求阶段流转记录';

CREATE TABLE req_baseline (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    project_id BIGINT NOT NULL COMMENT '所属项目',
    baseline_no VARCHAR(64) NOT NULL COMMENT '基线版本号',
    baseline_name VARCHAR(200) NULL COMMENT '基线名称',
    status VARCHAR(32) NOT NULL DEFAULT 'RELEASED' COMMENT '基线状态：RELEASED',
    difference_count INT NOT NULL DEFAULT 0 COMMENT '纳入差异数',
    remark VARCHAR(500) NULL COMMENT '备注',
    created_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    KEY idx_req_baseline_project (tenant_id, project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='需求基线版本';

CREATE TABLE req_baseline_item (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    baseline_id BIGINT NOT NULL COMMENT '基线 ID',
    difference_id BIGINT NOT NULL COMMENT '差异 ID',
    snapshot_json TEXT NULL COMMENT '差异快照',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    KEY idx_req_baseline_item_base (tenant_id, baseline_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='需求基线明细（差异快照）';

CREATE TABLE req_change_log (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    biz_type VARCHAR(32) NOT NULL COMMENT '业务类型：NEW_PROJECT_DIFF/LEGACY_REQUIREMENT/SYSTEM/BASELINE',
    biz_id BIGINT NOT NULL COMMENT '业务主键',
    field_name VARCHAR(128) NULL COMMENT '字段名（英文）',
    old_value VARCHAR(1000) NULL COMMENT '旧值',
    new_value VARCHAR(1000) NULL COMMENT '新值',
    change_type VARCHAR(32) NOT NULL COMMENT '操作类型：CREATE/UPDATE/DELETE/SUBMIT_REVIEW/REVIEW_PASS/REVIEW_RETURN/BASELINE/STAGE_TRANSITION/IMPORT',
    operator_id BIGINT NOT NULL COMMENT '操作人',
    operator_name VARCHAR(64) NULL COMMENT '操作人姓名',
    source VARCHAR(16) NOT NULL DEFAULT 'ONLINE' COMMENT '来源：ONLINE/IMPORT',
    trace_id VARCHAR(64) NULL COMMENT 'trace ID',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    KEY idx_req_change_log_biz (tenant_id, biz_type, biz_id),
    KEY idx_req_change_log_created (tenant_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一改动记录';

CREATE TABLE req_import_batch (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    biz_type VARCHAR(32) NOT NULL COMMENT '导入业务：DIFF/LEGACY',
    project_id BIGINT NULL COMMENT '新建项目差异导入时所属项目',
    file_name VARCHAR(200) NULL COMMENT '文件名',
    template_type VARCHAR(32) NULL COMMENT '模板类型',
    total_rows INT NOT NULL DEFAULT 0,
    success_rows INT NOT NULL DEFAULT 0,
    error_rows INT NOT NULL DEFAULT 0,
    errors_json TEXT NULL COMMENT '逐行校验报告',
    status VARCHAR(16) NOT NULL DEFAULT 'IMPORTED' COMMENT '导入状态：IMPORTED',
    operator_id BIGINT NOT NULL,
    operator_name VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    KEY idx_req_import_batch_biz (tenant_id, biz_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='需求导入批次与校验报告';

CREATE TABLE req_attachment (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    biz_type VARCHAR(32) NOT NULL COMMENT '业务类型：NEW_PROJECT_DIFF/LEGACY_REQUIREMENT',
    biz_id BIGINT NOT NULL COMMENT '业务主键',
    file_name VARCHAR(200) NOT NULL COMMENT '文件名',
    file_size BIGINT NULL COMMENT '文件大小',
    content_type VARCHAR(128) NULL COMMENT '内容类型',
    preview_id VARCHAR(64) NULL COMMENT '平台文件预览 ID',
    preview_url VARCHAR(1000) NULL COMMENT '平台返回的受控预览地址',
    operator_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    KEY idx_req_attachment_biz (tenant_id, biz_type, biz_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='需求业务附件绑定（存储地址由平台文件预览能力管理）';

CREATE TABLE req_project_member (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    project_id BIGINT NOT NULL COMMENT '项目 ID',
    user_id BIGINT NOT NULL COMMENT '成员用户 ID',
    member_role VARCHAR(16) NOT NULL DEFAULT 'MEMBER' COMMENT '成员角色：LEADER/MEMBER',
    created_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_req_project_member (tenant_id, project_id, user_id),
    KEY idx_req_project_member_user (tenant_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='新建项目组成员（数据范围）';

CREATE TABLE req_business_group_member (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    business_group VARCHAR(64) NOT NULL COMMENT '业务组名称',
    user_id BIGINT NOT NULL COMMENT '成员用户 ID',
    created_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_req_business_group_member (tenant_id, business_group, user_id),
    KEY idx_req_business_group_user (tenant_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='存量需求业务组数据范围成员';
