spring:
  application:
    name: ccb-platform
  servlet:
    multipart:
      max-file-size: ${FILE_PREVIEW_MAX_FILE_SIZE:50MB}
      max-request-size: ${FILE_PREVIEW_MAX_FILE_SIZE:50MB}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info

flowable:
  database-schema-update: false
  history-level: full
  async-executor-activate: false
  check-process-definitions: false
