package com.ccb.requirement.service;
import org.springframework.stereotype.Repository;
import java.util.*;
@Repository public class RequirementLegacyRepository {
 private final RequirementLegacyMapper m; public RequirementLegacyRepository(RequirementLegacyMapper m){this.m=m;}
 public long count(Map<String,Object> p){return m.count(p);} public List<Map<String,Object>> page(Map<String,Object> p){return m.page(p);} public Map<String,Object> find(long t,long id){return m.find(t,id);} public void insert(Map<String,Object> p){m.insertLegacy(p);} public void update(Map<String,Object> p){m.updateLegacy(p);} public void softDelete(long t,long id,long u){m.softDeleteLegacy(t,id,u);}
 public void deleteChildren(long t,long id){m.deleteSystemItems(t,id);m.deleteFlowLogs(t,id);m.deleteSystemMembers(t,id);m.deleteLegacyMembers(t,id);m.deleteVersions(t,id);m.deleteWorkloads(t,id);m.deleteSoftDocs(t,id);m.deleteCoordinations(t,id);} public void transitionStage(Map<String,Object> p){m.transitionStage(p);} public void insertStageLog(Map<String,Object> p){m.insertStageLog(p);} public List<Map<String,Object>> stageLogs(long t,long id){return m.stageLogs(t,id);}
 public List<Map<String,Object>> members(long t,long id){return m.members(t,id);} public int userCount(long t,long u){return m.userCount(t,u);} public int legacyMemberCount(long t,long r,long u){return m.legacyMemberCount(t,r,u);} public String userName(long t,long u){return m.userName(t,u);} public void insertMember(Map<String,Object> p){m.insertMember(p);} public Map<String,Object> member(long t,long id){return m.member(t,id);} public void deleteMember(long t,long id){m.deleteMember(t,id);}
 public List<Map<String,Object>> systemItems(long t,long id){return m.systemItems(t,id);} public List<Map<String,Object>> systemItemsForRequirements(long t,List<Long> ids){return ids.isEmpty()?List.of():m.systemItemsForRequirements(t,ids);} public List<Map<String,Object>> systemMembersForItems(long t,List<Long> ids){return ids.isEmpty()?List.of():m.systemMembersForItems(t,ids);} public void replaceSystemItems(long t,long id){m.deleteSystemItems(t,id);m.deleteSystemMembers(t,id);} public void insertSystemItem(Map<String,Object> p){m.insertSystemItem(p);} public void upsertSystemMember(Map<String,Object> p){m.upsertSystemMember(p);}
 public List<Map<String,Object>> flowLogs(long t,long id){return m.flowLogs(t,id);} public Map<String,Object> activeUser(long t,long id){return m.activeUser(t,id);} public void updateFlow(long t,long id,Long u,String n,long by){m.updateFlow(t,id,u,n,by);} public Map<String,Object> latestSender(long t,long id){return m.latestSender(t,id);} public void insertFlowLog(Map<String,Object> p){m.insertFlowLog(p);} public List<Map<String,Object>> versions(long t,long id){return m.versions(t,id);} public void updateVersion(long t,long id,String v,long by){m.updateVersion(t,id,v,by);} public void upsertVersion(Map<String,Object> p){m.upsertVersion(p);} public boolean exists(long t,long id){return m.exists(t,id)>0;}
}
