/*
 * 文件：server/src/modules/test-management/src/main/java/com/ccb/testmanagement/execution/TestExecutionService.java
 * 说明：测试执行的服务、策略或接口实现。
 * 用途：承载模块边界内的查询、校验、事务、权限或文件处理职责。
 * 作者：hengguan
 */
package com.ccb.testmanagement.execution;

// 关键逻辑：所有读写以认证用户的租户、测试大类和项目为共同边界；写入由事务与审计保持一致性。

import com.ccb.attachment.integration.AttachmentBindingCommand;
import com.ccb.attachment.integration.AttachmentGateway;
import com.ccb.attachment.integration.AttachmentItem;
import com.ccb.common.api.PageQuery;
import com.ccb.common.api.PageResult;
import com.ccb.common.exception.BusinessException;
import com.ccb.common.exception.ErrorCode;
import com.ccb.security.model.AuthUser;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

/** 测试执行：案例实时引用、目录、结果、批量操作和执行轨迹。 */
@Service
public class TestExecutionService {
    public static final String BUSINESS_TYPE = "TEST_EXECUTION";
    private static final Set<String> DOMAINS=Set.of("application-assembly","user-testing","non-functional","security");
    private static final Set<String> STATUSES=Set.of("UNEXECUTED","RUNNING","SUCCESS","FAILED","INVALID","BLOCKED");
    private static final AtomicLong IDS=new AtomicLong(System.currentTimeMillis()*1000);
    private final JdbcTemplate jdbc; private final AttachmentGateway attachments; private final ObjectMapper mapper;
    public TestExecutionService(JdbcTemplate jdbc,AttachmentGateway attachments,ObjectMapper mapper){this.jdbc=jdbc;this.attachments=attachments;this.mapper=mapper;}

    public Map<String,Object> tree(String domain,long projectId,AuthUser user){scope(domain,projectId,user);long t=user.tenantId();
        List<Map<String,Object>> systems=jdbc.queryForList("SELECT s.physical_subsystem_id id,s.physical_subsystem_id physical_subsystem_id,p.code,p.short_name,COALESCE(NULLIF(p.short_name,''),REPLACE(p.name,'物理子系统','')) name FROM tm_test_participating_system s JOIN arch_physical_subsystem p ON p.id=s.physical_subsystem_id AND p.tenant_id=s.tenant_id AND p.deleted=0 WHERE s.tenant_id=? AND s.test_domain=? AND s.project_id=? AND s.enabled=1 AND s.deleted=0 ORDER BY p.code",t,domain,projectId);
        List<Map<String,Object>> rounds=jdbc.queryForList("SELECT id,round_code,round_name,status,sort_no FROM tm_test_round WHERE tenant_id=? AND test_domain=? AND project_id=? AND deleted=0 ORDER BY sort_no,id",t,domain,projectId);
        List<Map<String,Object>> cycles=jdbc.queryForList("SELECT c.id,c.round_id,c.cycle_code,c.cycle_name,c.status,c.sort_no FROM tm_test_cycle c JOIN tm_test_round r ON r.id=c.round_id AND r.tenant_id=c.tenant_id AND r.deleted=0 WHERE c.tenant_id=? AND r.test_domain=? AND r.project_id=? AND c.deleted=0 ORDER BY c.sort_no,c.id",t,domain,projectId);
        List<Map<String,Object>> directories=jdbc.queryForList("SELECT d.id,d.physical_subsystem_id,d.round_id,d.cycle_id,d.parent_id,d.directory_name,d.sort_no,(SELECT COUNT(*) FROM tm_test_execution e WHERE e.tenant_id=d.tenant_id AND e.directory_id=d.id AND e.deleted=0) execution_count FROM tm_test_execution_directory d WHERE d.tenant_id=? AND d.test_domain=? AND d.project_id=? AND d.deleted=0 ORDER BY d.sort_no,d.id",t,domain,projectId);
        return Map.of("systems",systems,"rounds",rounds,"cycles",cycles,"directories",directories);
    }

    public PageResult<Map<String,Object>> list(String d,long p,Long system,Long round,Long cycle,Long directory,String keyword,Collection<String> statuses,Long executor,String defectLink,String validity,String sortBy,String sortOrder,PageQuery page,AuthUser u){scope(d,p,u);StringBuilder w=new StringBuilder(" WHERE e.tenant_id=? AND e.test_domain=? AND e.project_id=? AND e.deleted=0");List<Object>a=new ArrayList<>(List.of(u.tenantId(),d,p));
        if(system!=null){enabled(d,p,system,u.tenantId());w.append(" AND e.physical_subsystem_id=?");a.add(system);} if(round!=null){round(round,d,p,u.tenantId());w.append(" AND e.round_id=?");a.add(round);} if(cycle!=null){cycle(cycle,d,p,u.tenantId());w.append(" AND e.cycle_id=?");a.add(cycle);} if(directory!=null){directory(directory,d,p,u.tenantId());w.append(" AND e.directory_id=?");a.add(directory);}
        String q=text(keyword,200,"关键字");if(q!=null){w.append(" AND (c.case_code LIKE ? OR c.case_name LIKE ?)");a.add("%"+q+"%");a.add("%"+q+"%");} if(executor!=null){w.append(" AND e.executor_id=?");a.add(executor);} List<String> ss=values(statuses,STATUSES,"执行状态");if(!ss.isEmpty()){w.append(" AND e.execution_status IN (").append(qs(ss.size())).append(")");a.addAll(ss);} if("LINKED".equalsIgnoreCase(defectLink))w.append(" AND EXISTS(SELECT 1 FROM tm_test_defect_execution x WHERE x.tenant_id=e.tenant_id AND x.execution_id=e.id AND x.relation_state='ACTIVE')");if("UNLINKED".equalsIgnoreCase(defectLink))w.append(" AND NOT EXISTS(SELECT 1 FROM tm_test_defect_execution x WHERE x.tenant_id=e.tenant_id AND x.execution_id=e.id AND x.relation_state='ACTIVE')");if("INVALID".equalsIgnoreCase(validity))w.append(" AND c.invalidated=1");if("NORMAL".equalsIgnoreCase(validity))w.append(" AND c.invalidated=0");
        String from=" FROM tm_test_execution e JOIN tm_test_case c ON c.id=e.case_id AND c.tenant_id=e.tenant_id JOIN tm_test_scope s ON s.id=c.scope_id AND s.tenant_id=c.tenant_id LEFT JOIN sys_user x ON x.id=e.executor_id AND x.tenant_id=e.tenant_id AND x.deleted=0";Long total=jdbc.queryForObject("SELECT COUNT(*)"+from+w,Long.class,a.toArray());
        Map<String,String> sortable=Map.of("case_code","c.case_code","case_name","c.case_name","execution_status","e.execution_status","executed_at","e.executed_at","updated_at","e.updated_at");
        String order=sortable.getOrDefault(sortBy==null?"":sortBy,"e.updated_at")+("ascending".equalsIgnoreCase(sortOrder)?" ASC":" DESC")+",e.id DESC";
        String sql="SELECT e.id,e.case_id,e.directory_id,e.round_id,e.cycle_id,e.execution_status,e.executor_id,x.display_name executor_name,e.executed_at,e.actual_result_html,e.remark_html,c.case_code,c.case_name,c.case_type,c.test_level case_nature,c.priority,c.invalidated,c.updated_at case_updated_at,s.scope_code,s.scope_name,(SELECT COUNT(*) FROM tm_test_defect_execution l JOIN tm_test_defect f ON f.id=l.defect_id AND f.tenant_id=l.tenant_id AND f.deleted=0 AND f.status<>'RESOLVED' WHERE l.tenant_id=e.tenant_id AND l.execution_id=e.id AND l.relation_state='ACTIVE') defect_count"+from+w+" ORDER BY "+order+" LIMIT ?,?";List<Object>b=new ArrayList<>(a);b.add((page.page()-1)*page.size());b.add(page.size());return new PageResult<>(jdbc.queryForList(sql,b.toArray()),total==null?0:total,page.page(),page.size());}

    public Map<String,Object> previewImport(String d,long p,Map<String,Object> body,AuthUser u){scope(d,p,u);long target=positive(body.get("directory_id"),"目标执行目录");Map<String,Object> dir=directory(target,d,p,u.tenantId());Set<Long> ids=new LinkedHashSet<>();List<Map<String,Object>> requestedInvalid=new ArrayList<>();for(Object x:list(body.get("case_ids")))ids.add(positive(x,"案例"));for(Object x:list(body.get("scope_ids")))for(Long id:jdbc.queryForList("SELECT id FROM tm_test_case WHERE tenant_id=? AND test_domain=? AND project_id=? AND scope_id=? AND invalidated=0 AND deleted=0",Long.class,u.tenantId(),d,p,positive(x,"范围")))ids.add(id);for(String code:codes(body.get("case_codes"))){List<Long> matches=jdbc.queryForList("SELECT id FROM tm_test_case WHERE tenant_id=? AND test_domain=? AND project_id=? AND case_code=? AND deleted=0",Long.class,u.tenantId(),d,p,code);if(matches.isEmpty())requestedInvalid.add(Map.of("case_code",code,"reason","案例编号不存在或不属于当前项目"));else ids.addAll(matches);}
        List<Map<String,Object>> valid=new ArrayList<>(),duplicate=new ArrayList<>(),invalid=new ArrayList<>(requestedInvalid);for(long id:ids){List<Map<String,Object>> rows=jdbc.queryForList("SELECT id,case_code,case_name,physical_subsystem_id,invalidated FROM tm_test_case WHERE id=? AND tenant_id=? AND test_domain=? AND project_id=? AND deleted=0",id,u.tenantId(),d,p);if(rows.isEmpty()){invalid.add(Map.of("case_id",id,"reason","案例不存在"));continue;}Map<String,Object> c=rows.get(0);if(number(c.get("physical_subsystem_id"))!=number(dir.get("physical_subsystem_id"))){invalid.add(Map.of("case_code",c.get("case_code"),"reason","案例不属于当前系统"));continue;}if(bool(c.get("invalidated"))){invalid.add(Map.of("case_code",c.get("case_code"),"reason","案例已无效"));continue;}Long n=jdbc.queryForObject("SELECT COUNT(*) FROM tm_test_execution WHERE tenant_id=? AND directory_id=? AND case_id=? AND deleted=0",Long.class,u.tenantId(),target,id);if(n!=null&&n>0)duplicate.add(c);else valid.add(c);}return Map.of("directory_id",target,"valid",valid,"duplicates",duplicate,"invalid",invalid,"valid_count",valid.size());}

    @Transactional public Map<String,Object> confirmImport(String d,long p,Map<String,Object>b,AuthUser u){Map<String,Object> preview=previewImport(d,p,b,u);long dir=number(preview.get("directory_id"));Map<String,Object> row=directory(dir,d,p,u.tenantId());int created=0;for(Map<String,Object> c:maps(preview.get("valid"))){long id=next();jdbc.update("INSERT INTO tm_test_execution(id,tenant_id,test_domain,project_id,physical_subsystem_id,round_id,cycle_id,directory_id,case_id,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)",id,u.tenantId(),d,p,row.get("physical_subsystem_id"),row.get("round_id"),row.get("cycle_id"),dir,c.get("id"),u.id(),u.id());trace(d,p,id,"IMPORT",u,Map.of("case_code",c.get("case_code")));created++;}return Map.of("created",created,"skipped_duplicates",maps(preview.get("duplicates")).size(),"invalid",maps(preview.get("invalid")).size());}

    @Transactional public Map<String,Object> saveDirectory(String d,long p,Long id,Map<String,Object>b,AuthUser u){scope(d,p,u);long system=positive(b.get("physical_subsystem_id"),"参测系统"),round=positive(b.get("round_id"),"轮次"),cycle=positive(b.get("cycle_id"),"周期");enabled(d,p,system,u.tenantId());round(round,d,p,u.tenantId());cycle(cycle,d,p,u.tenantId());Long parent=nullable(b.get("parent_id"));if(parent!=null){Map<String,Object>x=directory(parent,d,p,u.tenantId());if(number(x.get("physical_subsystem_id"))!=system||number(x.get("cycle_id"))!=cycle)throw bad("父目录必须属于相同系统和周期");}String name=required(b.get("directory_name"),"目录名称",100);int sort=integer(b.get("sort_no"));long saved=id==null?next():id;if(id==null)jdbc.update("INSERT INTO tm_test_execution_directory(id,tenant_id,test_domain,project_id,physical_subsystem_id,round_id,cycle_id,parent_id,directory_name,sort_no,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",saved,u.tenantId(),d,p,system,round,cycle,parent,name,sort,u.id(),u.id());else{directory(id,d,p,u.tenantId());jdbc.update("UPDATE tm_test_execution_directory SET parent_id=?,directory_name=?,sort_no=?,updated_by=? WHERE id=? AND tenant_id=?",parent,name,sort,u.id(),id,u.tenantId());}return directory(saved,d,p,u.tenantId());}
    @Transactional public void deleteDirectory(String d,long p,long id,AuthUser u){Map<String,Object>x=directory(id,d,p,u.tenantId());Long n=jdbc.queryForObject("SELECT COUNT(*) FROM tm_test_execution WHERE tenant_id=? AND directory_id=? AND deleted=0",Long.class,u.tenantId(),id);Long child=jdbc.queryForObject("SELECT COUNT(*) FROM tm_test_execution_directory WHERE tenant_id=? AND parent_id=? AND deleted=0",Long.class,u.tenantId(),id);if((n!=null&&n>0)||(child!=null&&child>0))throw conflict("该目录下已有执行记录或子目录，禁止删除");jdbc.update("UPDATE tm_test_execution_directory SET deleted=1,deleted_at=CURRENT_TIMESTAMP,updated_by=? WHERE id=? AND tenant_id=?",u.id(),id,u.tenantId());}

    public Map<String,Object> detail(String d,long p,long id,AuthUser u){Map<String,Object> e=execution(id,d,p,u.tenantId());Map<String,Object> out=new LinkedHashMap<>(jdbc.queryForMap("SELECT e.*,c.case_code,c.case_name,c.case_type,c.test_level case_nature,c.priority,c.invalidated,c.precondition_html,c.steps_html,c.expected_result_html,c.remark case_remark,c.updated_at case_updated_at,s.scope_code,s.scope_name FROM tm_test_execution e JOIN tm_test_case c ON c.id=e.case_id AND c.tenant_id=e.tenant_id JOIN tm_test_scope s ON s.id=c.scope_id AND s.tenant_id=c.tenant_id WHERE e.id=? AND e.tenant_id=?",id,u.tenantId()));out.put("attachments",attachmentRows("tm_test_execution_attachment","execution_id",id,u.tenantId()));out.put("defects",defects(id,u.tenantId()));out.put("traces",jdbc.queryForList("SELECT t.*,u.display_name operator_name FROM tm_test_execution_trace t LEFT JOIN sys_user u ON u.id=t.operator_id AND u.tenant_id=t.tenant_id AND u.deleted=0 WHERE t.tenant_id=? AND t.execution_id=? ORDER BY t.created_at DESC,t.id DESC",u.tenantId(),id));return out;}

    @Transactional public Map<String,Object> saveResult(String d,long p,long id,Map<String,Object>b,AuthUser u){Map<String,Object> e=execution(id,d,p,u.tenantId());writeAllowed(d,p,number(e.get("physical_subsystem_id")),u);String status=status(b.get("execution_status"));String actual=b.containsKey("actual_result_html")?html(b.get("actual_result_html")):(String)e.get("actual_result_html");String remark=b.containsKey("remark_html")?html(b.get("remark_html")):(String)e.get("remark_html");Set<Long> defectIds=ids(b.get("defect_ids"));if(("INVALID".equals(status)||"BLOCKED".equals(status))&&plain(remark).isBlank())throw bad("无效或阻塞时备注必填");if("FAILED".equals(status)&&defectIds.isEmpty()&&activeDefectCount(id,u.tenantId())==0)throw bad("失败必须关联或新建缺陷");if(!defectIds.isEmpty())associate(id,defectIds,d,p,u);String old=String.valueOf(e.get("execution_status"));jdbc.update("UPDATE tm_test_execution SET execution_status=?,actual_result_html=?,remark_html=?,executor_id=?,executed_at=CURRENT_TIMESTAMP,updated_by=? WHERE id=? AND tenant_id=?",status,actual,remark,u.id(),u.id(),id,u.tenantId());if(b.containsKey("attachment_ids"))syncAttachments(id,b.get("attachment_ids"),u);trace(d,p,id,"SAVE_RESULT",u,Map.of("old_status",old,"new_status",status));return detail(d,p,id,u);}
    @Transactional public Map<String,Object> batchStatus(String d,long p,Map<String,Object>b,AuthUser u){Set<Long> selected=ids(b.get("ids"));if(selected.isEmpty())throw bad("请选择执行记录");int changed=0;for(long id:selected){saveResult(d,p,id,b,u);changed++;}return Map.of("changed",changed);}
    @Transactional public Map<String,Object> move(String d,long p,Collection<Long> ids,long target,AuthUser u){Map<String,Object> dir=directory(target,d,p,u.tenantId());manager(d,u);int moved=0;for(long id:ids){Map<String,Object> e=execution(id,d,p,u.tenantId());if(number(e.get("physical_subsystem_id"))!=number(dir.get("physical_subsystem_id"))||number(e.get("cycle_id"))!=number(dir.get("cycle_id")))throw bad("目标目录必须属于相同系统和周期");jdbc.update("UPDATE tm_test_execution SET directory_id=?,updated_by=? WHERE id=? AND tenant_id=?",target,u.id(),id,u.tenantId());trace(d,p,id,"MOVE",u,Map.of("target_directory_id",target));moved++;}return Map.of("moved",moved);}
    @Transactional public Map<String,Object> remove(String d,long p,Collection<Long> ids,AuthUser u){manager(d,u);List<Long> blocked=new ArrayList<>();int removed=0;for(long id:ids){execution(id,d,p,u.tenantId());if(unresolved(id,u.tenantId())>0){blocked.add(id);continue;}snapshot(id,u);jdbc.update("UPDATE tm_test_execution SET deleted=1,deleted_at=CURRENT_TIMESTAMP,updated_by=? WHERE id=? AND tenant_id=?",u.id(),id,u.tenantId());removed++;}return Map.of("removed",removed,"blocked_execution_ids",blocked);}
    @Transactional public void associate(long executionId,Collection<Long> defectIds,String d,long p,AuthUser u){Map<String,Object> e=execution(executionId,d,p,u.tenantId());for(long defectId:defectIds){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM tm_test_defect WHERE id=? AND tenant_id=? AND test_domain=? AND project_id=? AND deleted=0",Long.class,defectId,u.tenantId(),d,p);if(n==null||n==0)throw bad("缺陷不存在或不属于当前项目");Long exists=jdbc.queryForObject("SELECT COUNT(*) FROM tm_test_defect_execution WHERE tenant_id=? AND defect_id=? AND execution_id=? AND relation_state='ACTIVE'",Long.class,u.tenantId(),defectId,executionId);if(exists==null||exists==0)jdbc.update("INSERT INTO tm_test_defect_execution(id,tenant_id,defect_id,execution_id,relation_state,created_by,updated_by) VALUES(?,?,?,?,?,?,?)",next(),u.tenantId(),defectId,executionId,"ACTIVE",u.id(),u.id());}trace(d,p,executionId,"ASSOCIATE_DEFECT",u,Map.of("defect_ids",defectIds));}
    @Transactional public void detach(long executionId,long defectId,String d,long p,AuthUser u){manager(d,u);execution(executionId,d,p,u.tenantId());Long n=jdbc.queryForObject("SELECT COUNT(*) FROM tm_test_defect_execution WHERE tenant_id=? AND defect_id=? AND execution_id=? AND relation_state='ACTIVE'",Long.class,u.tenantId(),defectId,executionId);if(n==null||n==0)throw bad("缺陷关联不存在");snapshotOne(executionId,defectId,u);trace(d,p,executionId,"DETACH_DEFECT",u,Map.of("defect_id",defectId));}
    public List<Map<String,Object>> exportRows(String d,long p,Map<String,Object>b,AuthUser u){return list(d,p,nullable(b.get("physical_subsystem_id")),nullable(b.get("round_id")),nullable(b.get("cycle_id")),nullable(b.get("directory_id")),text(b.get("keyword"),200,"关键字"),strings(b.get("status")),nullable(b.get("executor_id")),text(b.get("defect_link"),20,"缺陷关联"),text(b.get("validity"),20,"案例有效性"),"case_code","ascending",new PageQuery(1,2000),u).records();}

    private void snapshot(long id,AuthUser u){for(Map<String,Object> r:jdbc.queryForList("SELECT defect_id FROM tm_test_defect_execution WHERE tenant_id=? AND execution_id=? AND relation_state='ACTIVE'",u.tenantId(),id))snapshotOne(id,number(r.get("defect_id")),u);}
    private void snapshotOne(long execution,long defect,AuthUser u){Map<String,Object> x=jdbc.queryForMap("SELECT c.case_code,c.case_name,s.scope_code,s.scope_name FROM tm_test_execution e JOIN tm_test_case c ON c.id=e.case_id AND c.tenant_id=e.tenant_id JOIN tm_test_scope s ON s.id=c.scope_id AND s.tenant_id=c.tenant_id WHERE e.id=? AND e.tenant_id=?",execution,u.tenantId());jdbc.update("UPDATE tm_test_defect_execution SET execution_id=NULL,relation_state='SNAPSHOT',snapshot_case_code=?,snapshot_case_name=?,snapshot_scope_code=?,snapshot_scope_name=?,updated_by=? WHERE tenant_id=? AND defect_id=? AND execution_id=? AND relation_state='ACTIVE'",x.get("case_code"),x.get("case_name"),x.get("scope_code"),x.get("scope_name"),u.id(),u.tenantId(),defect,execution);}
    private List<Map<String,Object>> defects(long execution,long tenant){return jdbc.queryForList("SELECT f.id,f.defect_code,f.summary,f.status FROM tm_test_defect_execution l JOIN tm_test_defect f ON f.id=l.defect_id AND f.tenant_id=l.tenant_id WHERE l.tenant_id=? AND l.execution_id=? AND l.relation_state='ACTIVE' ORDER BY f.proposed_at DESC",tenant,execution);}
    private int unresolved(long execution,long tenant){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM tm_test_defect_execution l JOIN tm_test_defect f ON f.id=l.defect_id AND f.tenant_id=l.tenant_id AND f.deleted=0 AND f.status<>'RESOLVED' WHERE l.tenant_id=? AND l.execution_id=? AND l.relation_state='ACTIVE'",Long.class,tenant,execution);return n==null?0:n.intValue();} private int activeDefectCount(long execution,long tenant){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM tm_test_defect_execution WHERE tenant_id=? AND execution_id=? AND relation_state='ACTIVE'",Long.class,tenant,execution);return n==null?0:n.intValue();}
    private void syncAttachments(long id,Object raw,AuthUser u){Set<Long>wanted=ids(raw);for(Map<String,Object>r:jdbc.queryForList("SELECT attachment_id FROM tm_test_execution_attachment WHERE tenant_id=? AND execution_id=? AND deleted=0",u.tenantId(),id)){long aid=number(r.get("attachment_id"));if(!wanted.contains(aid)){attachments.deleteBound(aid,BUSINESS_TYPE,String.valueOf(id),u);jdbc.update("UPDATE tm_test_execution_attachment SET deleted=1,deleted_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND execution_id=? AND attachment_id=?",u.tenantId(),id,aid);}}int sort=0;for(long aid:wanted){AttachmentItem item=attachments.get(aid,u);if(item.fileSize()>50L*1024*1024)throw bad("单个附件不能超过50MB");Long n=jdbc.queryForObject("SELECT COUNT(*) FROM tm_test_execution_attachment WHERE tenant_id=? AND execution_id=? AND attachment_id=? AND deleted=0",Long.class,u.tenantId(),id,aid);if(n==null||n==0){attachments.bind(new AttachmentBindingCommand(aid,BUSINESS_TYPE,String.valueOf(id),null),u);jdbc.update("INSERT INTO tm_test_execution_attachment(id,tenant_id,execution_id,attachment_id,sort_no,created_by) VALUES(?,?,?,?,?,?)",next(),u.tenantId(),id,aid,sort,u.id());}sort++;}}
    private List<Map<String,Object>> attachmentRows(String table,String field,long id,long tenant){return jdbc.queryForList("SELECT a.attachment_id id,f.file_name,f.file_size,f.content_type,a.sort_no FROM "+table+" a LEFT JOIN att_file f ON f.id=a.attachment_id AND f.tenant_id=a.tenant_id WHERE a.tenant_id=? AND a."+field+"=? AND a.deleted=0 ORDER BY a.sort_no,a.id",tenant,id);}
    private void trace(String d,long p,long id,String action,AuthUser u,Map<String,Object> detail){try{jdbc.update("INSERT INTO tm_test_execution_trace(id,tenant_id,test_domain,project_id,execution_id,action_code,operator_id,detail_json) VALUES(?,?,?,?,?,?,?,?)",next(),u.tenantId(),d,p,id,action,u.id(),mapper.writeValueAsString(detail));}catch(Exception e){throw new BusinessException(ErrorCode.INTERNAL_ERROR,"执行轨迹写入失败");}}
    private void scope(String d,long p,AuthUser u){if(!DOMAINS.contains(d))throw bad("测试大类无效");Long n=jdbc.queryForObject("SELECT COUNT(*) FROM pm_project WHERE id=? AND tenant_id=? AND deleted=0",Long.class,p,u.tenantId());if(n==null||n==0)throw bad("项目不存在或无权访问");} private void enabled(String d,long p,long s,long t){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM tm_test_participating_system WHERE tenant_id=? AND test_domain=? AND project_id=? AND physical_subsystem_id=? AND enabled=1 AND deleted=0",Long.class,t,d,p,s);if(n==null||n==0)throw bad("请选择已启用的参测系统");} private void round(long id,String d,long p,long t){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM tm_test_round WHERE id=? AND tenant_id=? AND test_domain=? AND project_id=? AND deleted=0",Long.class,id,t,d,p);if(n==null||n==0)throw bad("测试轮次不存在");} private void cycle(long id,String d,long p,long t){Long n=jdbc.queryForObject("SELECT COUNT(*) FROM tm_test_cycle c JOIN tm_test_round r ON r.id=c.round_id AND r.tenant_id=c.tenant_id WHERE c.id=? AND c.tenant_id=? AND r.test_domain=? AND r.project_id=? AND c.deleted=0 AND r.deleted=0",Long.class,id,t,d,p);if(n==null||n==0)throw bad("测试周期不存在");}
    private Map<String,Object> directory(long id,String d,long p,long t){List<Map<String,Object>>r=jdbc.queryForList("SELECT * FROM tm_test_execution_directory WHERE id=? AND tenant_id=? AND test_domain=? AND project_id=? AND deleted=0",id,t,d,p);if(r.isEmpty())throw bad("执行目录不存在或不属于当前项目");return r.get(0);}private Map<String,Object> execution(long id,String d,long p,long t){List<Map<String,Object>>r=jdbc.queryForList("SELECT * FROM tm_test_execution WHERE id=? AND tenant_id=? AND test_domain=? AND project_id=? AND deleted=0",id,t,d,p);if(r.isEmpty())throw bad("执行记录不存在或不属于当前项目");return r.get(0);} private void writeAllowed(String d,long p,long system,AuthUser u){enabled(d,p,system,u.tenantId());Long n=jdbc.queryForObject("SELECT COUNT(*) FROM tm_test_system_role WHERE tenant_id=? AND test_domain=? AND project_id=? AND physical_subsystem_id=? AND user_id=? AND role_code IN ('TEST_MANAGER','TESTER') AND deleted=0",Long.class,u.tenantId(),d,p,system,u.id());if((n==null||n==0)&&!authority("test-management:"+d+":execution:update"))throw new BusinessException(ErrorCode.FORBIDDEN,"未分配到该系统，不能填写执行结果");} private void manager(String d,AuthUser u){if(!authority("test-management:"+d+":execution:delete")&&!authority("test-management:"+d+":execution:update"))throw new BusinessException(ErrorCode.FORBIDDEN,"仅测试经理及以上可执行此操作");}private boolean authority(String a){var x=org.springframework.security.core.context.SecurityContextHolder.getContext().getAuthentication();return x!=null&&x.getAuthorities().stream().anyMatch(v->a.equals(v.getAuthority()));}
    private String status(Object x){String s=required(x,"执行状态",24).toUpperCase(Locale.ROOT);if(!STATUSES.contains(s))throw bad("执行状态无效");return s;}private static long next(){return IDS.incrementAndGet();}private static long number(Object x){return ((Number)x).longValue();}private static boolean bool(Object x){return x instanceof Boolean b?b:"1".equals(String.valueOf(x))||"true".equalsIgnoreCase(String.valueOf(x));}private static String plain(String x){return x==null?"":x.replaceAll("<[^>]*>","").replace("&nbsp;"," ").trim();}private static String html(Object x){String s=text(x,200000,"富文本");return s==null?null:s.replaceAll("(?is)<script[^>]*>.*?</script>","").replaceAll("(?i)\\son\\w+\\s*=\\s*(['\"]).*?\\1","");}private static String required(Object x,String n,int max){String s=text(x,max,n);if(s==null)throw bad(n+"不能为空");return s;}private static String text(Object x,int max,String n){if(x==null)return null;String s=String.valueOf(x).trim();if(s.isBlank()||"null".equals(s))return null;if(s.length()>max)throw bad(n+"不能超过"+max+"个字符");return s;}private static long positive(Object x,String n){Long v=nullable(x);if(v==null||v<=0)throw bad(n+"无效");return v;}private static Long nullable(Object x){if(x==null||String.valueOf(x).isBlank()||"null".equals(String.valueOf(x)))return null;try{return Long.parseLong(String.valueOf(x));}catch(Exception e){throw bad("编号无效");}}private static int integer(Object x){if(x==null||String.valueOf(x).isBlank())return 0;try{return Integer.parseInt(String.valueOf(x));}catch(Exception e){throw bad("排序无效");}}private static List<?> list(Object x){return x instanceof Collection<?> c?new ArrayList<>(c):x==null?List.of():List.of(x);}private static Set<Long> ids(Object x){Set<Long>s=new LinkedHashSet<>();for(Object v:list(x))s.add(positive(v,"编号"));return s;}private static List<String> codes(Object x){List<String>s=new ArrayList<>();for(Object v:list(x))for(String part:String.valueOf(v).split("[,\\n\\r]+")){String z=part.trim();if(!z.isEmpty())s.add(z);}return s;}private static List<String> strings(Object x){List<String>s=new ArrayList<>();for(Object v:list(x))s.add(String.valueOf(v));return s;}private static List<String> values(Collection<String>x,Set<String>a,String n){List<String>s=new ArrayList<>();if(x!=null)for(String v:x){String z=text(v,32,n);if(z!=null){z=z.toUpperCase(Locale.ROOT);if(!a.contains(z))throw bad(n+"无效");s.add(z);}}return s;}@SuppressWarnings("unchecked")private static List<Map<String,Object>> maps(Object x){return x instanceof Collection<?> c?(List<Map<String,Object>>)(List<?>)new ArrayList<>(c):List.of();}private static String qs(int n){return String.join(",",Collections.nCopies(n,"?"));}private static BusinessException bad(String s){return new BusinessException(ErrorCode.BAD_REQUEST,s);}private static BusinessException conflict(String s){return new BusinessException(ErrorCode.CONFLICT,s);}
}
