package com.ccb.testmanagement.plan;

import com.ccb.attachment.integration.AttachmentBindingCommand;
import com.ccb.attachment.integration.AttachmentGateway;
import com.ccb.attachment.integration.AttachmentItem;
import com.ccb.common.api.PageQuery;
import com.ccb.common.api.PageResult;
import com.ccb.common.exception.BusinessException;
import com.ccb.common.exception.ErrorCode;
import com.ccb.security.model.AuthUser;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;

/** 测试方案服务：业务校验、事务和附件绑定由服务层负责，持久化由 Repository/Mapper 承担。 */
@Service
public class TestPlanService {
    public static final String BUSINESS_TYPE="TEST_PLAN_VERSION";
    private static final Set<String> DOMAINS=Set.of("application-assembly","user-testing","non-functional","security"), NODE_TYPES=Set.of("PROJECT","SYSTEM","SPECIAL");
    private final TestPlanRepository repository; private final AttachmentGateway attachments;
    public TestPlanService(TestPlanRepository repository,AttachmentGateway attachments){this.repository=repository;this.attachments=attachments;}
    public Map<String,Object> tree(String d,long p,AuthUser u){scope(d,p,u);Map<String,Object> x=base(d,p,u);return Map.of("project",repository.project(x),"systems",repository.systems(x),"specials",repository.specials(x));}
    public PageResult<Map<String,Object>> plans(String d,long p,Map<String,Object> node,PageQuery page,AuthUser u){Node n=requireNode(d,p,node,u);Map<String,Object>x=nodeParams(d,p,n,u);long total=repository.planCount(x);x.put("offset",(page.page()-1)*page.size());x.put("size",page.size());return new PageResult<>(repository.plans(x),total,page.page(),page.size());}
    public Map<String,Object> current(String d,long p,Map<String,Object> node,AuthUser u){var result=plans(d,p,node,new PageQuery(1,1),u);return result.records().isEmpty()?Map.of():result.records().get(0);}
    public List<Map<String,Object>> versions(String d,long p,long id,AuthUser u){requirePlan(id,d,p,u.tenantId());return repository.versions(params("tenantId",u.tenantId(),"planId",id));}
    @Transactional public Map<String,Object> createSpecial(String d,long p,Map<String,Object>b,AuthUser u){scope(d,p,u);String name=required(b.get("node_name"),"专项名称",100);Map<String,Object>x=base(d,p,u);x.put("name",name);if(repository.specialNameCount(x)>0)throw conflict("专项名称已存在");long id=next();x.put("id",id);repository.insertSpecial(x);audit(d,p,null,null,"CREATE_SPECIAL",u);return repository.special(params("id",id,"tenantId",u.tenantId()));}
    @Transactional public Map<String,Object> updateSpecial(String d,long p,long id,Map<String,Object>b,AuthUser u){scope(d,p,u);requireSpecial(id,d,p,u.tenantId());String name=required(b.get("node_name"),"专项名称",100);Map<String,Object>x=base(d,p,u);x.put("id",id);x.put("name",name);if(repository.specialNameCount(x)>0)throw conflict("专项名称已存在");repository.updateSpecial(x);audit(d,p,null,null,"UPDATE_SPECIAL",u);return repository.special(params("id",id,"tenantId",u.tenantId()));}
    @Transactional public void deleteSpecial(String d,long p,long id,AuthUser u){scope(d,p,u);requireSpecial(id,d,p,u.tenantId());Map<String,Object>x=base(d,p,u);x.put("id",id);if(repository.specialPlanCount(x)>0)throw conflict("该专项下已有方案，不能删除");repository.deleteSpecial(x);audit(d,p,null,null,"DELETE_SPECIAL",u);}
    @Transactional public Map<String,Object> upload(String d,long p,Long planId,Map<String,Object>b,AuthUser u){scope(d,p,u);String note=required(b.get("version_note"),"版本说明",200);long attachmentId=positive(b.get("attachment_id"),"方案文件");AttachmentItem a=attachments.get(attachmentId,u);validateAttachment(a,u);long saved;String name;Node node;if(planId!=null){Map<String,Object> plan=requirePlan(planId,d,p,u.tenantId());saved=planId;name=String.valueOf(plan.get("plan_name"));node=new Node(String.valueOf(plan.get("node_type")),numberOrNull(plan.get("physical_subsystem_id")),numberOrNull(plan.get("special_node_id")));}else{node=requireNode(d,p,b,u);name=required(b.get("plan_name"),"方案名称",100);Map<String,Object>x=nodeParams(d,p,node,u);x.put("name",name);List<Map<String,Object>>same=repository.matchingPlans(x);if(!same.isEmpty()){saved=number(same.get(0).get("id"));int version=nextVersion(saved,u.tenantId());if(!bool(b.get("confirm_version")))return Map.of("version_confirmation_required",true,"plan_id",saved,"next_version",version,"plan_name",name);}else{saved=next();x.put("id",saved);repository.insertPlan(x);}}
        int version=nextVersion(saved,u.tenantId());long versionId=next();attachments.bind(new AttachmentBindingCommand(attachmentId,BUSINESS_TYPE,String.valueOf(versionId),String.valueOf(p)),u);repository.insertVersion(params("id",versionId,"tenantId",u.tenantId(),"planId",saved,"versionNo",version,"note",note,"attachmentId",attachmentId,"fileName",a.fileName(),"fileExtension",extension(a),"fileSize",a.fileSize(),"userId",u.id()));repository.touchPlan(params("planId",saved,"tenantId",u.tenantId(),"userId",u.id()));audit(d,p,saved,versionId,version==1?"CREATE":"UPLOAD_VERSION",u);return repository.version(params("versionId",versionId,"planId",saved,"tenantId",u.tenantId()));}
    @Transactional public void deletePlan(String d,long p,long id,AuthUser u){scope(d,p,u);requirePlan(id,d,p,u.tenantId());repository.deletePlan(params("planId",id,"tenantId",u.tenantId(),"userId",u.id()));audit(d,p,id,null,"DELETE",u);}
    private Node requireNode(String d,long p,Map<String,Object>b,AuthUser u){String type=String.valueOf(b.getOrDefault("node_type","")).trim().toUpperCase(Locale.ROOT);if(!NODE_TYPES.contains(type))throw bad("方案节点无效");if("PROJECT".equals(type))return new Node(type,null,null);if("SYSTEM".equals(type)){long id=positive(b.get("physical_subsystem_id"),"参测系统");if(!repository.participatingSystem(params("tenantId",u.tenantId(),"domain",d,"projectId",p,"systemId",id)))throw bad("请选择已参测系统");return new Node(type,id,null);}long id=positive(b.get("special_node_id"),"专项节点");requireSpecial(id,d,p,u.tenantId());return new Node(type,null,id);}
    private Map<String,Object> requirePlan(long id,String d,long p,long tenant){Map<String,Object> x=repository.plan(params("planId",id,"tenantId",tenant,"domain",d,"projectId",p));if(x==null||x.isEmpty())throw bad("测试方案不存在或不属于当前项目");return x;}private void requireSpecial(long id,String d,long p,long tenant){if(!repository.specialExists(params("id",id,"tenantId",tenant,"domain",d,"projectId",p)))throw bad("专项节点不存在或不属于当前项目");}private int nextVersion(long plan,long tenant){return repository.nextVersion(params("planId",plan,"tenantId",tenant));}private void scope(String d,long p,AuthUser u){if(!DOMAINS.contains(d))throw bad("测试大类无效");if(!repository.projectExists(params("projectId",p,"tenantId",u.tenantId())))throw bad("项目不存在或无权访问");}
    private Map<String,Object> base(String d,long p,AuthUser u){return params("tenantId",u.tenantId(),"domain",d,"projectId",p,"userId",u.id());}private Map<String,Object> nodeParams(String d,long p,Node n,AuthUser u){Map<String,Object>x=base(d,p,u);x.put("nodeType",n.type());x.put("systemId",n.systemId());x.put("specialId",n.specialId());return x;}private void audit(String d,long p,Long plan,Long version,String action,AuthUser u){repository.insertAudit(params("id",next(),"tenantId",u.tenantId(),"domain",d,"projectId",p,"planId",plan,"versionId",version,"action",action,"userId",u.id()));}
    private void validateAttachment(AttachmentItem x,AuthUser u){String extension=extension(x);if(!Set.of("docx","xlsx").contains(extension))throw bad("仅支持 .docx 或 .xlsx 格式，请另存为新格式后上传");if(x.fileSize()>50L*1024*1024)throw bad("单个方案文件不能超过50MB");if(x.uploaderId()!=u.id())throw bad("只能绑定本人上传的方案文件");}private static String extension(AttachmentItem x){String v=x.fileExtension();if(v==null||v.isBlank()){String n=x.fileName();int i=n==null?-1:n.lastIndexOf('.');v=i<0?"":n.substring(i+1);}return v.toLowerCase(Locale.ROOT).replaceFirst("^\\.","");}private static Map<String,Object> params(Object...v){Map<String,Object>x=new HashMap<>();for(int i=0;i<v.length;i+=2)x.put(String.valueOf(v[i]),v[i+1]);return x;}private static long next(){return System.currentTimeMillis()*1000+ThreadLocalRandom.current().nextInt(1000);}private static long positive(Object v,String n){try{long i=Long.parseLong(String.valueOf(v));if(i>0)return i;}catch(Exception ignored){}throw bad(n+"无效");}private static Long numberOrNull(Object v){return v instanceof Number n?n.longValue():v==null?null:Long.parseLong(String.valueOf(v));}private static long number(Object v){return ((Number)v).longValue();}private static String required(Object v,String n,int max){String x=v==null?"":String.valueOf(v).trim();if(x.isBlank()||x.length()>max)throw bad(n+"无效");return x;}private static boolean bool(Object v){return v instanceof Boolean b?b:"true".equalsIgnoreCase(String.valueOf(v))||"1".equals(String.valueOf(v));}private static BusinessException bad(String s){return new BusinessException(ErrorCode.BAD_REQUEST,s);}private static BusinessException conflict(String s){return new BusinessException(ErrorCode.CONFLICT,s);}private record Node(String type,Long systemId,Long specialId){}
}
